### ISSUE TITLE
Support for Razer Basilisk V3

### ISSUE THREAD

**Issue by yochananmarqos** [openrazer/razer-drivers#1610]
### Device Info

* Name: Razer Basilisk v3
* Product Number: <See under device>
* Model Number: RZ01-04000100-R3U1

### Device Information
```
Bus 001 Device 002: ID 1532:0099 Razer USA, Ltd Razer Basilisk V3
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0099 
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer Basilisk V3
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x006d
    bNumInterfaces          4
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      79
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        3
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      22
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
```

```
lrwxrwxrwx 1 root root  10 Sep 19 19:53 usb-Razer_Razer_Basilisk_V3-event-if01 -> ../event20
lrwxrwxrwx 1 root root  10 Sep 19 19:53 usb-Razer_Razer_Basilisk_V3-event-mouse -> ../event18
lrwxrwxrwx 1 root root  10 Sep 19 19:53 usb-Razer_Razer_Basilisk_V3-if01-event-kbd -> ../event19
lrwxrwxrwx 1 root root  10 Sep 19 19:53 usb-Razer_Razer_Basilisk_V3-if02-event-kbd -> ../event21
lrwxrwxrwx 1 root root   9 Sep 19 19:53 usb-Razer_Razer_Basilisk_V3-mouse -> ../mouse2
```

### Packet Captures
I'll get back to you...

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots

![2021-09-20 (1)](https://user-images.githubusercontent.com/5437803/134047495-bac51bf2-6a62-42cf-bde6-7b3eb5125731.png)
![2021-09-20 (2)](https://user-images.githubusercontent.com/5437803/134047499-2c85229e-f48d-4a3f-b69f-311cfeceabcb.png)
![2021-09-20 (3)](https://user-images.githubusercontent.com/5437803/134047500-450d0258-d938-424c-a079-48eb735b5d16.png)
![2021-09-20 (4)](https://user-images.githubusercontent.com/5437803/134047501-3d1514b2-af8b-4983-a09b-a7bff87854c3.png)

**Comment by TheNaschkatze** [comment]
Is this feature comming? D:

**Comment by laxuscullen** [comment]
> Is this feature comming? D:

Same question :(

Did you find an alternative? @TheNaschkatze

**Comment by TheNaschkatze** [comment]
@laxuscullen I plug in the mouse and the keyboard at the same time, so at least they change color at the same time xD

**Comment by laxuscullen** [comment]
@TheNaschkatze That made me laugh lmao.
I would love to customize my mouse but sadly it does not seem like it will be getting supported anytime supported considering the time this issue was open :(

**Comment by TheNaschkatze** [comment]
@laxuscullen I mean the issue is open, and not that long ago. The mouse release date is about the same as this issues date. What I'm unsure about, is the meaning of the `need pcap` tag. But I have a good feeling about the support :D

**Comment by lah7** [comment]
`need pcap` means it needs packet captures in order to understand what protocol the device speaks. Usually a matter of having a Windows VM handy and [following this guide](https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol).

If you like to get your hands dirty, try modifying the source files yourself and look at [commits implementing other Basilisk devices](https://github.com/openrazer/openrazer/search?q=Basilisk&type=commits) as a reference, such as 7ac21a93c74cc2b6511d73c6f7fa4cf5147bbee5.

**Comment by laxuscullen** [comment]
any luck with the pcap? @yochananmarqos

**Comment by bin4rym4ge** [comment]
I just got this mouse because my last mouse broke. Why is this so difficult?

**Comment by laxuscullen** [comment]
> I just got this mouse because my last mouse broke. Why is this so difficult?

it needs pcap, read lah7's reply. I tried to read through the documentation but welp

**Comment by TheNaschkatze** [comment]
> > I just got this mouse because my last mouse broke. Why is this so difficult?
> 
> it needs pcap, read lah7's reply. I tried to read through the documentation but welp

I dont have a wndows VM :/

**Comment by tildearrow** [comment]
> > > I just got this mouse because my last mouse broke. Why is this so difficult?
> > 
> > 
> > it needs pcap, read lah7's reply. I tried to read through the documentation but welp
> 
> I dont have a wndows VM :/

It's possible to set up a Windows virtual machine and give it some USB passthrough so that the Razer device in question is passed to the virtual machine so the official Razer drivers interact with it and therefore allow you to look what do the drivers exactly do with the device.
The instructions might be a bit difficult though...

`need pcap` means needs packet capture. A packet capture is a file that Wireshark generates which contains packets, and packets are the things that make these devices do things.

**Comment by bdach** [comment]
As a heads up, I'm in the middle of attempting to add this support as I own the device. I believe I've got packet captures of at least the basic parts I need, and I've already got some code in place that looks to be at least part way there. However it still doesn't work because apparently I am seeing `-ETIMEDOUT` errnos from `usb_control_msg` calls and I'm not sure whether this is a device quirk and I need to fiddle with it to increase timeouts somehow, or if I'm just not doing whatever else right.

**Comment by TheNaschkatze** [comment]
is mergeeeeed <3

**Comment by laxuscullen** [comment]
Much love to you @bdach ✨

**Comment by wheelhub155** [comment]
are there any updates if there will ever be a release for the Razer Basilsk v3? i just purchased it and non of the released software supports it. let alone i can only get up to version 4.5 to work on my mac due to java script error. please , someone let me know:)

**Comment by laxuscullen** [comment]
@wheelhub155 use daily instead of stable branch and v3 is supported. Not sure how the error you are facing will be fixed tho

**Comment by wheelhub155** [comment]
> 

Can you please explain what you mean by use daily instead of stable branch? Plz and thx.
Also, I am using macOS. version 10.3.2

I'm using keyboard Razer Black Widow v3 and works with no issues.

**Comment by lah7** [comment]
@wheelhub155 OpenRazer doesn't support macOS. It sounds like you're mistaking this project for [1kc/razer-macos](https://github.com/1kc/razer-macos), which studies OpenRazer's driver to add each device separately.

Please see their repository. It looks like they are working on it: https://github.com/1kc/razer-macos/issues/557

**Comment by JoanaRoqueOS** [comment]
Hi guys. any changes about the supporting of the basilisk v3? I just bought it yesterday and discover the incompatibility with macOS... I have a macbook pro from 2018 with macOS Monterey version 12.2.1.

I installed the app, but the mouse is not recognized... i already did multiple times the 'refresh device list' and nothing... restarted the mac to see if it makes a difference, and nothing.... But then i discover that this 'issue' was open... Any news about when you will be able to got it to work with the app???
I'm really appreciate your hard work guys!

**Comment by z3ntu** [comment]
To reiterate, this project **does not** support macOS, projects that do have their issue tracker somewhere else.
