### ISSUE TITLE
Feature suggestion: Activate effect based on foreground application

### ISSUE THREAD

**Issue by sgofferj** [openrazer/razer-drivers#1629]
I have been going through the issues and I haven't found anything similar with my search phrases.

I would like to suggest a function which allows the user to map certain effects or presets to applications in the Polychromatic GUI. The color effect would then change automatically based on what application is in the foreground.
This function would be extremely useful for anybody who often switches between application as part of their workflow.
The easiest way to implement this would probably be to get the title of the window which currently has the focus.

**Comment by z3ntu** [comment]
This sounds like something you could do in a custom script, or if you want this feature in polychromatic please go to their issue tracker. This is not in scope of openrazer.

**Comment by sgofferj** [comment]
Oops, wrong repo. Apologies!
