### ISSUE TITLE
Change ID for Razer Keyboard

### ISSUE THREAD

**Issue by g0lr** [openrazer/razer-drivers#1644]
I buy a Razer Cynapse Keyboard, and i install openrazer in debian, but the problem is the ID is different, i read i can change the ID to match with the ID of my keyboard.

But i dont find how i can do that, where i need to change that value?

**Comment by z3ntu** [comment]
Can you please post the output of `lsusb | grep 1532`?

**Comment by Khraut** [comment]
Just saw this open Issue, i think my problem also fits in:

I have the Razer Book 13 running on Manjaro. However the per Key RGB Keyboard is not recognized. 

Here is the output of `lsusb | grep 1532`:

`Bus 003 Device 004: ID 1532:026a Razer USA, Ltd Razer Blade`

It says Razer Blade, but that ist not correct. Maybe the wrong Id causes the issue with the missing effects support?

**Comment by z3ntu** [comment]
@Khraut Please open a new issue for that. But a quick answer already, if the device supports that then it hasn't been implemented yet in openrazer https://github.com/openrazer/openrazer/blob/master/driver/razerkbd_driver.c#L3033
