### ISSUE TITLE
Bountysource or similar

### ISSUE THREAD

**Issue by Trollwut** [openrazer/razer-drivers#1650]
Hey mates!

Love your software, thanks for that!

Are there any intentions to get this project on bountysource.com or similar services?

Short description: People can set a bounty on issues to give open source contributors a little bit more motivation. :) 

For example, [adding Analog key support for the "Huntsman V2 Analog"](https://github.com/openrazer/openrazer/pull/1554) won't be an easy task, but if some people gather a little money for it, some hacker might invest the time in doing that.

Nonetheless, going to donate now to your project, as it is a bless for us Razer-weebs on Linux. Keep on with the awesome work!

**Comment by z3ntu** [comment]
I don't really see the point in doing that, if people are interested in adding support for their device they can of course do the implementation. But device support can mostly only be done if you have the physical device so this is unlike other projects where e.g. a great feature can be developed on any device. But of course people can do a free-text "Hey, I'm donating 20€ to whoever implements for support for this device" but I don't see the point in adding a 3rd party that takes a % of the money for themselves. So far it has worked out without it and I don't see why it would change if we added that.
I hope that answers your question.
