### ISSUE TITLE
Razer Firefly V2

### ISSUE THREAD

**Issue by sirmax1** [openrazer/razer-drivers#1683]
### Distribution

Razer Firefly V2 (Mouse Pad)

### Support
While trying to open the editor i get the below message 
"Please open an issue in the RazerGenie repository. 
Device name: Razer Firefly V2 - matrix dimens: 1 19"

**Comment by z3ntu** [comment]
Please copy this over to https://github.com/z3ntu/RazerGenie/issues

As a workaround you can build RazerGenie from source with `-Dinclude_matrix_discovery=true` passed to meson so you can control the matrix from the UI even though there's no proper support present.
