### ISSUE TITLE
The description of how to build in the wiki is a bit wrong.

### ISSUE THREAD

**Issue by yoshida-ryuhei** [openrazer/razer-drivers#1685]
### Distribution
- Archlinux
- Razer DEATHADDER ESSENTIAL

### Support
- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

### description
Thank you for your good repository and the wiki.

I tried to build this repository from a source in Archlinux.
However, the pkg build was failed because the configuration of `PKGBUILD`, written in [wiki](https://github.com/openrazer/openrazer/wiki/Building-a-package#build-packages-from-a-source-directory) was not good.

The difference of the file `PKGBUILD` should be like this.
 A function `prepare` was added after the wiki page was written, I think.
```diff
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -11,8 +11,8 @@ arch=('any')
 url="https://github.com/openrazer/openrazer"
 license=('GPL2')
 makedepends=('git' 'python-setuptools')
-source=("git+https://github.com/openrazer/openrazer.git")
-sha256sums=('SKIP')
+source=()
+sha256sums=()

 pkgver() {
   cd "$_pkgbase"
@@ -20,13 +20,7 @@ pkgver() {
 }

 prepare() {
-  # Do a sanity check in the environment of the builder so the build process doesn't place files into a wrong directory.
-  # If you think this is incorrect you can always remove this from the PKGBUILD, but then please don't complain if it doesn't work.
-  if [ "$(which python3)" != "/usr/bin/python3" ]; then
-    echo "ERROR: Your 'python3' does not point to /usr/bin/python3 but to $(which python3), likely a custom environment like anaconda."
-    echo "Please build this package in a clean chroot (e.g. with https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot) or point your PATH variable to prefer /usr/bin/ temporarily."
-    return 1
-  fi
+       cp -ar "/path/to/your/openrazer/source/tree" "$srcdir/openrazer"
 }

 package_python-openrazer-git() {
```

I would appreciate it if you update the  [wiki](https://github.com/openrazer/openrazer/wiki/Building-a-package#build-packages-from-a-source-directory) page.
I want to send a pull request, but I cannot send a pull request for wiki, so please forgive for that.

**Comment by z3ntu** [comment]
Fixed: https://github.com/openrazer/openrazer/wiki/Building-a-package/_compare/c38b113a1bdaea871826da62e82ed697b91f97f9...449e5999f77593fdb40f45cc97f41d47fe32e968
