### ISSUE TITLE
Where can I get archived Fedora 32 packages?

### ISSUE THREAD

**Issue by rpgdev** [openrazer/razer-drivers#1688]
Current repos hold versions for Fedora 33 and up which is understandable but can someone please tell me where can I get archived Fedora 32 packages? For reasons out of my control I can go through the upgrade process now.

**Comment by z3ntu** [comment]
I don't think OBS archives disabled repositories, but you can build for Fedora 32 yourself from source https://github.com/openrazer/openrazer/wiki/Building-a-package

Or alternatively even build it for Fedora 32 in your own OBS project depending on your needs

**Comment by rpgdev** [comment]
@z3ntu OBS archives? Can you please point what are those? I tried replacing the 33 for a 32 in the opensuse repo settings but it didn't work https://software.opensuse.org/download.html?project=hardware%3Arazer&package=openrazer-meta

**Comment by rpgdev** [comment]
Never mind, I was able to build my own package using the link you posted and I was able to install it. I am getting issue #181 but I was able to work around it changing the python path. Thanks!
