### ISSUE TITLE
Openrazer crashing

### ISSUE THREAD

**Issue by PlamenStilyianov** [openrazer/razer-drivers#1689]
openrazer-daemon.service - Daemon to manage razer devices in userspace
   Loaded: loaded (/usr/lib/systemd/user/openrazer-daemon.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2021-11-28 13:14:16 GMT; 24s ago
     Docs: man:openrazer-daemon(8)
  Process: 3206 ExecStart=/usr/bin/openrazer-daemon -F (code=exited, status=1/FAILURE)
 Main PID: 3206 (code=exited, status=1/FAILURE)

**Comment by z3ntu** [comment]
Can you post the output of `openrazer-daemon -Fv` ?

**Comment by PlamenStilyianov** [comment]
razergenie does not open the above is log from the GUI, command prompt does not write any output out
orajava@suse152:~> razergenie 
Translation loaded: false

**Comment by z3ntu** [comment]
I didn't ask about anything from RazerGenie, can you please run the command `openrazer-daemon -Fv` in your terminal and copy-paste the output here?

**Comment by PlamenStilyianov** [comment]
orajava@suse152:~> openrazer-daemon -Fv
Starting daemon.
2021-11-28 13:31:30 | razer                          | CRITICAL | User is not a member of the plugdev group
2021-11-28 13:31:30 | razer                          | CRITICAL | Please run the command 'sudo gpasswd -a $USER plugdev' and then reboot!
Stopping daemon.

**Comment by jeffreyvangorkum** [comment]
It literally tells you what the issue is and what you have to do ;)

In short, your user is no member of the group "plugdev". To fix this run the command 'sudo gpasswd -a $USER plugdev'
