### ISSUE TITLE
Support for Anzu (Glasses)

### ISSUE THREAD

**Issue by cow-killer** [openrazer/razer-drivers#1694]
### Device Info

* Name: Razer Anzu
* Product Number: RZ82-03630800
* Model Number: RZ40-0363

### Device Information
```
Please post the output of
    lsusb -d 1532: -v
```
Nothing, it's Bluetooth (is there an equivalent command for this?)
```
Please post the output of
    ls -lah /dev/input/by-id/

total 0
drwxr-xr-x 2 root root 160 Dec  3 09:41 .
drwxr-xr-x 4 root root 580 Dec  3 10:07 ..
lrwxrwxrwx 1 root root  10 Dec  3 09:41 usb-1ea7_2.4G_Mouse-event-if00 -> ../event20
lrwxrwxrwx 1 root root  10 Dec  3 09:41 usb-1ea7_2.4G_Mouse-event-mouse -> ../event21
lrwxrwxrwx 1 root root   9 Dec  3 09:41 usb-1ea7_2.4G_Mouse-mouse -> ../mouse0
lrwxrwxrwx 1 root root  10 Dec  3 09:41 usb-Corsair_Corsair_STRAFE_Gaming_Keyboard_0E033015AEBA086455D6647FF5001946-event-if01 -> ../event18
lrwxrwxrwx 1 root root  10 Dec  3 09:41 usb-Corsair_Corsair_STRAFE_Gaming_Keyboard_0E033015AEBA086455D6647FF5001946-event-kbd -> ../event16
lrwxrwxrwx 1 root root  10 Dec  3 09:41 usb-Corsair_Corsair_STRAFE_Gaming_Keyboard_0E033015AEBA086455D6647FF5001946-if01-event-kbd -> ../event17
```

### Packet Captures
Not using USB...guess I will need to capture Bluetooth packets?

### Synapse Screenshots
I don't have Windows...

Sorry for the lack of info, if there's anything else I can provide let me know. Bluetooth connection works great on Arch -- audio output works as intended. But it won't pick up the mic, even though it's listed under input sources. Any ideas?

**Comment by z3ntu** [comment]
Your problem sounds like pulseaudio/pipewire has some problem with the device. And definitely not in the scope of openrazer, sorry.
