### ISSUE TITLE
Please add support for xfce4-session and xflock4 | Viper Ultimate + Dock

### ISSUE THREAD

**Issue by greatbaracus** [openrazer/razer-drivers#1700]
### Distribution

Manjaro 21.2.0 - XFCE 4.16

### Support

- [ x] Have you tried rebooting?
- [ x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Hi,

When i put my system into sleep mode (suspend) or when i lock my session with the default commands (by using the buttons on Whisker Menu or with Actions Buttons applet ) it does not turn off the devices. 
In sleep mode the dock is turned off which is normal because it's not powered anymore, but the mouse stays powered.
In lock mode, dock and devices stay on.

![sleep](https://user-images.githubusercontent.com/38059479/145256034-0cb5dcd4-e2fa-41ab-80fd-897de7efd753.png)

Apparently, both (Whisker Menu and Action Buttons applet) use xfce4-session to sleep/hibernate/logout, and also xflock4 to lock the session.

ps : By the way, thank you for added xfce4-screensaver support few months ago, the dock and the mouse turn-off very well when the screensaver is activated.

**Comment by z3ntu** [comment]
Not really an openrazer problem. You can probably configure in Linux somewhere which USB devices should still keep power during suspend. I'm sure you'll find something online.
