### ISSUE TITLE
Support for Viper 8k

### ISSUE THREAD

**Issue by gitrazorhub** [openrazer/razer-drivers#1706]
### Device Info

* Name: Viper 8k
* Product Number: RZ01-03580100
* Model Number: RZ01-0358

### Device Information
```
Please post the output of
    lsusb -d 1532: -v
```
Bus 009 Device 002: ID 1532:0091 Razer USA, Ltd Razer Viper 8KHz
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0091 
  bcdDevice            1.01
  iManufacturer           1 Razer
  iProduct                2 Razer Viper 8KHz
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.00
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.00
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
Device Qualifier (for other device speed):
  bLength                10
  bDescriptorType         6
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  bNumConfigurations      0
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0001
  Self Powered

```
Please post the output of
    ls -lah /dev/input/by-id/
```
total 0
drwxr-xr-x 2 root root 160 Dec 14 05:16 .
drwxr-xr-x 6 root root 600 Dec 14 05:16 ..
lrwxrwxrwx 1 root root   9 Dec 14 05:16 ckb-CORSAIR_K70_RGB_MK.2_LOW_PROFILE_Mechanical_Gaming_vKB_-event -> ../event8
lrwxrwxrwx 1 root root   9 Dec 14 05:16 ckb-CORSAIR_K70_RGB_MK.2_LOW_PROFILE_Mechanical_Gaming_vM_-event -> ../event9
lrwxrwxrwx 1 root root   9 Dec 14 05:16 usb-Razer_Razer_Viper_8KHz-event-mouse -> ../event2
lrwxrwxrwx 1 root root  10 Dec 14 05:16 usb-Razer_Razer_Viper_8KHz-if01-event-kbd -> ../event17
lrwxrwxrwx 1 root root   9 Dec 14 05:16 usb-Razer_Razer_Viper_8KHz-if02-event-kbd -> ../event7
lrwxrwxrwx 1 root root   9 Dec 14 05:16 usb-Razer_Razer_Viper_8KHz-mouse -> ../mouse0

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on **Razer Synapse** in a Windows Environment>
[Screenshot at 2021-12-14 17-18-00](https://user-images.githubusercontent.com/96154975/146105354-23a858f3-d225-433e-ab38-17214b466b30.png)

**Comment by gitrazorhub** [comment]
Will we be able to reprogram the side buttons?

**Comment by z3ntu** [comment]
This device is already supported since OpenRazer v3.2.0. Side buttons can be remapped with e.g. https://github.com/sezanzeb/input-remapper
