### ISSUE TITLE
Persistant `device_mode`

### ISSUE THREAD

**Issue by G-M0N3Y-2503** [openrazer/razer-drivers#1708]
### Distribution
Description:    Manjaro Linux
Release:         21.2rc
Codename:     Qonos

### Support
It looks like [`device_mode` isn't written to the persistent config file](https://github.com/openrazer/openrazer/blob/master/daemon/openrazer_daemon/daemon.py#L305), So I tried to create `/etc/udev/rules.d/99-razermouse.rules` with the following:
```
DRIVER=="razermouse", ATTR{device_type}=="Razer Naga 2014", ATTR{device_mode}=e"\x03\x00"
```
But it appears that [udev doesn't support the `\0` characters in the value](https://github.com/systemd/systemd/blob/main/src/shared/udev-util.c#L381).
I'm working around this by setting the `param` byte to `\x01` instead, but it [looks like this is relying on temporary behaviour](https://github.com/openrazer/openrazer/blob/master/driver/razerchromacommon.c#L29).

Is there an official way to configure this attribute that I'm missing?

**Comment by z3ntu** [comment]
You can make udev run a normal shell script where you can set it then. But no there isn't a way to make device_mode what you want persistently, the daemon always sets it to the value is wants on launch.
