### ISSUE TITLE
Wiki build instructions for RHEL-like OS'

### ISSUE THREAD

**Issue by DejfCold** [openrazer/razer-drivers#1712]
### Distribution

v3.2.0. from source 

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Hi! I'm using Rocky Linux 8.5 (basically CentOS). I tried Mooz's link from the home page, but that didn't work.
So I went to try to build it from source according to the Fedora guide. For that I was missing the `xautomation` dependency.
I tried to use the rpm from Fedora 35, but that required too new stuff, so I settled with the xautomation from Fedora 34 (got it from here: https://fedora.pkgs.org/34/fedora-x86_64/xautomation-1.09-4.fc34.x86_64.rpm.html).
Everything started to work fine after I rebooted. Thanks!

Do you think you could add the CentOS/Rocky/Alma/RHEL workaround to the wiki? Maybe like a foot note next to the Fedora build instructions?

(or, like, it would be preferable if it wouldn't depend on the xautomation, but I've no idea what does it do and why is it needed)

**Comment by z3ntu** [comment]
xautomation is used by some ancient macro code which I want to remove at some point.

@moozhub Is your RHEL/CentOS repo still maintained?
