### ISSUE TITLE
Ripple thread overrides custom effects

### ISSUE THREAD

**Issue by lah7** [openrazer/razer-drivers#1714]
> Originally reported in https://github.com/polychromatic/polychromatic/issues/372

If the daemon is playing the "ripple" effect and the user wishes to play a custom effect via a script or application, it ends up competing with the daemon as they are both drawing frames, causing flickers between the two.

The workaround is to apply a hardware effect (such as None, or Static) and then proceed with the custom effect, so the daemon terminates the ripple thread. Currently, the daemon does not persist or have any knowledge about custom API calls.

Is this something that should be fixed in OpenRazer?

### 💡 Ideas

1. Add a conditional check in `draw()` that if ripple is running, terminate thread?
    * Maybe not? Sounds inefficient to me. 🐢 
1. Add a conditional check in the ripple thread to terminate if `draw()` was called?
1. A new function to the API like `fx.stop_ripple()` or `fx.advanced.init()` so the daemon can terminate the ripple thread upon request.
1. Leave it up to the script/app to pick a hardware effect.

What are your thoughts?

**Comment by SamantazFox** [comment]
If this is required, I'll gladly provide the USB PCAP of the official Razer app for that keyboard (via a Linux host, a Windows VM and USB passthrough).

**Comment by lah7** [comment]
@SamantazFox Thanks for the offer, but it's pretty much specific to the OpenRazer daemon. [There's a ripple thread](https://github.com/openrazer/openrazer/blob/master/daemon/openrazer_daemon/misc/ripple_effect.py) in the background that needs to stop, _somehow_. 🤔  Technically, Ripple is a custom software effect.

**Comment by z3ntu** [comment]
I would assume that once setCustom is called that the effect is switched to that, like you switch to any effect. So that ripple stops being ripple.

**Comment by z3ntu** [comment]
This was discussed in chat a bit, my suggestion: make an internal setCustom function that e.g. ripple is using as `def refresh_keyboard :         self._parent.setCustom()`.

And then make the public setCustom function do the notify that tells everybody custom effect (non-ripple) is on. Then the `daemon/openrazer_daemon/misc/ripple_effect.py` line 217 `def notify` notices this and stops doing the ripple. And this public function should use the internal function to actually write to sysfs.

(hope this summary is clear)

**Comment by z3ntu** [comment]
Please check if #2117 resolves this.

**Comment by lah7** [comment]
Can confirm that fixes the problem, thanks 👍🏼
