### ISSUE TITLE
Support for [Razer Basilisk V3]

### ISSUE THREAD

**Issue by thatshadycodeboi** [openrazer/razer-drivers#1715]
### Device Info

* Name: <Razer Basilisk V3>
* Product Number: <rz01-04000100>
* Model Number: <rz01-0400>

**Comment by thatshadycodeboi** [comment]
yeah, take it and leave it

**Comment by DavidNiehues** [comment]
There is already Issue #1610 for this.

**Comment by z3ntu** [comment]
Closing as duplicate as per last comment.
