### ISSUE TITLE
request installation support for slackware 14.2 64 bit

### ISSUE THREAD

**Issue by 10ked** [openrazer/razer-drivers#1716]
### Distribution
slackware 14.2 64 bit (multilib if possible and or needed)

### Support
 i can compile the package (kernel modules) but not install using a standard slackbuild as there is not one
- [ ] Have you tried rebooting?
- [ ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

the package may be open source (which is a good start) but as i said before there is no standard slackbuild so
i cannot install the package and try it out although i do have dkms support.

**Comment by z3ntu** [comment]
Hi, because demand for Slackware is really low and I'm not familiar with their packaging system, I probably won't spend time working on this. If you manage to create a package and you keep it updated, I'll gladly link to it from our website openrazer.github.io
