### ISSUE TITLE
 Razer DeathAdder Essential (2021) dosen't support scroll wheel brightness

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [openrazer/razer-drivers#1722]
basically what the title says, double checked using razer synapse.

**Comment by konstantinos-chatzis** [comment]
It is the same with the windows version of the app. The mouse itself doesn't support an independent scroll wheel brightness setting.

**Comment by Etaash-mathamsetty** [comment]
this is an extremely simple pr, I am wondering why nobody has fixed it yet
edit: lemme try making a pr
