### ISSUE TITLE
Cant find my Razer Deathadder V2 on RazerGenie

### ISSUE THREAD

**Issue by xerikperez** [openrazer/razer-drivers#1723]
Hi,
i have downloaded RazerGenie as said on the webpage. But when i open the application, the mouse can't be found.
how do i fix this?
thanks.

**Comment by 9mbre** [comment]
Hello,
I have the same problem with my Deathadder Essential: neither RazerGenie nor razerCommander manage to find it.

**Comment by z3ntu** [comment]
Please provide output of `lsusb | grep 1532` . Please also check the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page to see if that helps you.
