### ISSUE TITLE
Support for [Razer Blade 15 Advanced late 2019]

### ISSUE THREAD

**Issue by napsterred** [openrazer/razer-drivers#1727]
Please incorporate device support changes for dev id 24B   of Razer Blade 15 Advanced Late 2019  from the link

https://github.com/napsterred/openrazer.github.io

**Comment by napsterred** [comment]
i have altered the code to make it work with the model , pleas incorporate the changes in main open razer program so i can install it from GitHub ,

**Comment by z3ntu** [comment]
Can you please open a proper pull request with your changes, and not stuff them into the website repo?
If not possible at all I can spend some time extracting your changes but it's rather tedious.

**Comment by napsterred** [comment]
I don't know how to do it, its my first try at working on GitHub for anything, if ya send me instructions I could try.

**Comment by z3ntu** [comment]
I'm sure you can find many tutorials online but I unfortunately don't have the time to explain to you in detail.

**Comment by napsterred** [comment]
I almost cramped up everything trying to do it, **if you guys could extract the changes** that would be awesome. Even if a specific dev helps me out i could patreon them.

**Comment by lah7** [comment]
Done - #1737, as I had some time to spare. I took a copy of your files, deleted the website files, [cloned `openrazer/openrazer`](https://github.com/openrazer/openrazer), pasted them and checked/updated the diffs using the Git client so it can be integrated into main repository.

**Comment by z3ntu** [comment]
Closing as #1737 has been created from this, we still have #1041 to track the device in general.
