### ISSUE TITLE
Help. I require assistance.

### ISSUE THREAD

**Issue by somerandomeperson** [openrazer/razer-drivers#1731]
![Screenshot from 2022-01-13 10-35-02](https://user-images.githubusercontent.com/97696098/149389083-33fe4c3e-9f41-4960-b514-78a36e50a9b6.png)

I use fedora, and openrazer-daemon -Fv doesn't do anything.

**Comment by somerandomeperson** [comment]
when I do run openrazer-daemon -Fv it says "| CRITICAL | User is not a member of the plugdev group  | CRITICAL | Please run the command 'sudo gpasswd -a $USER plugdev' and then reboot!"    when I run "sudo gpasswd -a $USER plugdev" nothing happens

**Comment by z3ntu** [comment]
Did you reboot after running that command?

**Comment by somerandomeperson** [comment]
yes, but I typed in the command wrong, it works now! thank you!

**Comment by z3ntu** [comment]
Great!
