### ISSUE TITLE
BlackWidow V3 Pro, media buttons needs support

### ISSUE THREAD

**Issue by mariasoderstrom** [openrazer/razer-drivers#1732]
### Distribution
Ubuntu Linux
Ubuntu 21.10 64-Bit
Gnome 40.4.0

### Support
BlackWidow V3 Pro's media buttons are not working with openrazer

![image](https://user-images.githubusercontent.com/37001536/149610337-3e54b536-ecc9-4c0e-b3a9-15b86bcb1616.png)

Media buttons are not seen as a key and is used as regular input, this is what happens when you push in example mute button:

![image](https://user-images.githubusercontent.com/37001536/149610474-550055a0-f946-4f25-89bf-2a31973753a4.png)

You cannot change keyboard shortcuts due to this

**Comment by lah7** [comment]
Similar to #1552.

An identical model (`024E`) had the same problem: https://github.com/openrazer/openrazer/pull/1572#issuecomment-893598938 but I'm guessing it was only fixed for that specific PID (yours is `025A`).

For now, it should be possible to workaround the issue by stopping the daemon, putting the keyboard back into "generic" mode:

    openrazer-daemon -s

As soon as the daemon runs again (which can be triggered by opening any frontend), the keyboard's back into "driver" mode where the bug resides in the driver's key handling.

**Comment by geodox** [comment]
I’ll fix this this afternoon! My apologies for missing it in the pr.

**Comment by mariasoderstrom** [comment]
> I’ll fix this this afternoon! My apologies for missing it in the pr.

No problem! Happy to report issues

**Comment by hlriffel** [comment]
Hello,

Is there any update on this? I'm also having this media keys issue with the same device (`025A`).

I'm available to help with anything if needed.

**Comment by samoht9277** [comment]
Same, I'm still having the same issue on `025A`. Media keys are not working.

**Comment by wyattearp** [comment]
I just noticed this issue as well. ~~Looks like the fix *might* be as easy as:~~ disregard, testing confirms this doesn't fix it.

```diff
diff --git a/driver/razerkbd_driver.c b/driver/razerkbd_driver.c
index e1eb551..578871d 100644
--- a/driver/razerkbd_driver.c
+++ b/driver/razerkbd_driver.c
@@ -2614,6 +2614,7 @@ static int razer_event(struct hid_device *hdev, struct hid_field *field, struct
         break;
 
     case USB_DEVICE_ID_RAZER_BLACKWIDOW_V3:
+    case USB_DEVICE_ID_RAZER_BLACKWIDOW_V3_PRO_WIRED:
         translation = find_translation(chroma_keys_5, usage->code);
         break;
```

@GeoDoX is that your understanding as well?

**Comment by wyattearp** [comment]
Could anyone test my PR to see if it works for you? It "works for me" but I think there should be a little bit more testing than that :)

My current system info:

OS Details:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

Keyboard firmware version: v2.2

![image](https://user-images.githubusercontent.com/80254/153979845-a60d0c40-515b-4577-b248-ffd0810df78e.png)

**Comment by hlriffel** [comment]
@wyattearp 

I'm using the changes from your PR and it seems to be working perfectly initially. I'll be using it for a few days to make sure.

Thanks!

**Comment by wyattearp** [comment]
Anyone else try this?

**Comment by geodox** [comment]
@wyattearp That wasn’t what I was going to do, but if that seems to fix it, go ahead with it.

I was just going to reset the “mode” back to device mode as referenced in other issues and PRs related to media keys not working.

I appreciate someone tackling this as I just haven’t had the time to get to it.

**Comment by samoht9277** [comment]
Can confirm that @wyattearp PR is in fact working properly. Media buttons now work as intended, thanks!


    Operating System: Arch Linux
    Kernel: Linux 5.16.10-arch1-1
    Architecture: x86-64
