### ISSUE TITLE
On ubuntu login screen my keyboard and mouse go black

### ISSUE THREAD

**Issue by basprins** [openrazer/razer-drivers#1740]
Hi,
When I logoff my keyboard and mouse no longer have visual feedback (the leds switch off). Is that some configuration setting I need to adjust?

**Comment by lah7** [comment]
Hi. You can change the config for this setting in this file:

    ~/.config/openrazer/razer.conf

(In your home folder, press CTRL+H to reveal the hidden folder)

Then disable the screen saver feature by setting it to `False`:

```diff
[Startup]
-devices_off_on_screensaver = True
+devices_off_on_screensaver = False
```

The next time the daemon loads (so, after the next login), the lights will no longer turn off.
