### ISSUE TITLE
Disabling configuration dont work with Polychromatic

### ISSUE THREAD

**Issue by sonalys** [openrazer/razer-drivers#1755]
### Distribution

v3.2.0

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Im trying to disable notifications with polychromatic.

![image](https://user-images.githubusercontent.com/15274059/154296091-56f02bd0-7f3a-417d-bd75-c00e2f90318f.png)

~/.config/openrazer/razer.conf
```
[General]
verbose_logging = False

[Startup]
sync_effects_enabled = True
devices_off_on_screensaver = True
mouse_battery_notifier = True
mouse_battery_notifier_freq = 600
restore_persistence = True
battery_notifier = False
battery_notifier_freq = 9999
```

Even with these configurations, I still receive battery notifications for my keyboard every couple minutes, am I doing everything right?

**Comment by lah7** [comment]
It might be because there's a `mouse_battery_notifier` and `mouse_battery_notifier_freq` key present in the actual `razer.conf` file, try deleting those lines and restart the daemon.
