### ISSUE TITLE
Support for [device name here]

### ISSUE THREAD

**Issue by Rakansami** [openrazer/razer-drivers#1757]
### Device Info

* Name: <See under device>
* Product Number: <See under device>
* Model Number: <See under device>

### Device Information
```
Please post the output of
    lsusb -d 1532: -v
```

```
Please post the output of
    ls -lah /dev/input/by-id/
```

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on **Razer Synapse** in a Windows Environment>

**Comment by z3ntu** [comment]
Please fill in the issue template.

**Comment by z3ntu** [comment]
Closing since there is no response.
