### ISSUE TITLE
RB15 Early 2021 base stopped working

### ISSUE THREAD

**Issue by CasperBruning** [openrazer/razer-drivers#1760]
### Distribution

Ubuntu 20.04 LTS

### Support

- [x] Have you tried rebooting?
      YES
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?
     YES

Hi. my openrazer just stopped working on the RazerBladeEarly2021. it worked before but now its just not working. When it starts via Polychromatic it says unrecognised device while it did work. im on the 3.2.0 version so that should include the Early2021 blade (base).

i did try to run the troubleshooter and the troubleshoot page and all came out perfectly
i also tried reinstalling it but to no luck.

Any help would be appreciated.

**Comment by LinuxDonald** [comment]
Manjaro
Openrazer 3.2.0
Polychromatic last git version

![rb15](https://user-images.githubusercontent.com/1757651/157996642-d523992a-4c5a-4924-8c76-78451224c409.jpg)
