### ISSUE TITLE
Side mouse button support?

### ISSUE THREAD

**Issue by epilimic** [openrazer/razer-drivers#1763]
### Distribution

Linux Mint 20.2

### Support

- [x] Have you tried rebooting?
- [x] Yes
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?
- [x] Yes

I'm using a Naga Trinity and neither of the side mouse buttons work. I've tried both the standard and the most recent daily builds. xev doesn't even recognize either of them when being pressed.

**Comment by z3ntu** [comment]
I believe we would need to set the device to driver mode (instead of device mode) and handle some additional things in the driver itself - then we can also get the side button inputs.
Contributions welcome!
