### ISSUE TITLE
Cynosa Chroma

### ISSUE THREAD

**Issue by pstallinga** [openrazer/razer-drivers#1771]
Cynosa Chroma listed here as 1532:022A is in fact detected as 1532:110d by lsusb. Might be a reason it does not work

**Comment by nightsky30** [comment]
1532:110d is one of the identified bootloader IDs Razer devices report when they are in the process of updating their firmware. This can be seen when updating these devices through VirtualBox and the like. Perhaps your device is stuck that way after a firmware update or the product arrived that way from the factory?

I own a Cynosa Chroma. For reference:
```
$ lsusb|grep 1532
Bus 003 Device 002: ID 1532:0c00 Razer USA, Ltd RZ02-0135 Hard Gaming Mouse Mat [Firefly]
Bus 001 Device 011: ID 1532:022a Razer USA, Ltd Cynosa Chroma
Bus 001 Device 008: ID 1532:0f20 Razer USA, Ltd Razer Base Station V2 Chroma
Bus 001 Device 007: ID 1532:48f0 Razer USA, Ltd Razer Base Station V2 Chroma
Bus 001 Device 006: ID 1532:0f1d Razer USA, Ltd Razer Mouse Bungee V3 Chroma
Bus 001 Device 005: ID 1532:0060 Razer USA, Ltd RZ01-0213 Gaming Mouse [Lancehead Tournament Edition]
Bus 001 Device 010: ID 1532:026c Razer USA, Ltd Razer Huntsman V2
```
EDIT:
Your hardware might be fine, but looks like your firmware is in some inconsistent state. Openrazer can't fix that. To my knowledge this keyboard doesn't have any released firmware updates.

I would reach out to official Razer support and see if they can send you a firmware fix. And unfortunately you would need a Windows system/VM to apply it if you received a fix from them.
