### ISSUE TITLE
Orochi V2 not recognised

### ISSUE THREAD

**Issue by ghost** [openrazer/razer-drivers#1774]
### Distribution
EndeavourOS

### Support

- [ X] Have you tried rebooting?
- [ X] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I installed openrazer-meta-git, added myself to plugdev, started the daemon and rebooted. But my mouse is still not recognized. On polychromatic troubleshoot, it says my PID is not supported, 1532:0094, but on the github page it shows as supported.

**Comment by z3ntu** [comment]
Make sure these versions are all the same: `pacman -Q openrazer-meta-git openrazer-driver-dkms-git openrazer-daemon-git python-openrazer-git`

**Comment by ghost** [comment]
installed all of the mentioned packages, and rebooted. openrazer-daemon is also running but on razergenie, it says no devices are connected. My mouse is connected via bluetooth.

**Comment by z3ntu** [comment]
What's the output of `sudo dkms install openrazer-driver/3.2.0` ?

**Comment by ghost** [comment]
Module openrazer-driver/3.2.0 already installed on kernel 5.16.16-zen1-1-zen (x86_64).

**Comment by z3ntu** [comment]
`openrazer-daemon -Fv` ?

**Comment by ghost** [comment]
Unable to lock on the pidfile.

**Comment by z3ntu** [comment]
Can you post the output of `pacman -Q openrazer-meta-git openrazer-driver-dkms-git openrazer-daemon-git python-openrazer-git` ?

**Comment by ghost** [comment]
openrazer-meta-git 3.2.0.r11.g43423b7b-1
openrazer-driver-dkms-git 3.2.0.r11.g43423b7b-1
openrazer-daemon-git 3.2.0.r11.g43423b7b-1
python-openrazer-git 3.2.0.r11.g43423b7b-1

**Comment by z3ntu** [comment]
Output of `ls -al /sys/bus/hid/drivers/razermouse/0*/` and `sudo modprobe razerkbd` please

**Comment by ghost** [comment]
zsh: no matches found: /sys/bus/hid/drivers/razermouse/0*/

for the modprobe, no output

**Comment by z3ntu** [comment]
`sudo journalctl -b | grep -i razer_mount` ?

**Comment by ghost** [comment]
no output
