### ISSUE TITLE
Add support for Razer-Blade Model 15 Late 2021

### ISSUE THREAD

**Issue by Pretuer** [openrazer/razer-drivers#1775]
Hi, I'm wondering what the process is to add support for the Razer Blade 15 (Late 2021)

**Comment by LinuxDonald** [comment]
This pr is an example:

https://github.com/openrazer/openrazer/pull/1766/files

**Comment by Pretuer** [comment]
1532:0268 is it's device number

**Comment by z3ntu** [comment]
Duplicate of #1524
