### ISSUE TITLE
Razer Basilisk V3 is not recognized as a supported device.

### ISSUE THREAD

**Issue by GaVenga** [openrazer/razer-drivers#1784]
Razer Basilisk V3 wird nicht als unterstütztes Gerät erkannt.
Razergenie Version: 0.9.0 / Openrazer Daemon Version: 3.2.0
Model: RZ01-04000100.
Razer Basilisk V3
Manufacturer: Razer
Speed: 12Mb/s (full)
Bus:   1
Address:   6
USB Version:  2.00
Device Class: 00
Device Subclass: 00
Device Protocol: 00
Maximum Default Endpoint Size: 64
Number of Configurations: 1
Vendor Id: 1532
Product Id: 0099
Revision Number: 02.00

**Comment by z3ntu** [comment]
The Razer Basilisk V3 isn't supported in v3.2.0 but will be part of the next version. If you want to use it now, you have to use e.g. the daily packages on Ubuntu or the -git packages on Arch Linux.

---

Die Razer Basilisk V3 ist noch nicht unterstützt in v3.2.0 aber wird Teil von der nächsten Version sein. Wenn du es jetzt benutzen willst, musst du zB die daily Pakete auf Ubuntu oder die -git Pakete auf Arch Linux benutzen.
