### ISSUE TITLE
Audio Buttons - Huntsman V2 Not Working

### ISSUE THREAD

**Issue by westfarn** [openrazer/razer-drivers#1800]
### Device 
Razer Huntsman V2

### Operating System
Ubuntu 20.04 LTS

### Driver Version
openrazer-daemon 3.3.0

### Problem
The dedicated media keys (last, pause/play, skip) do not register with the Operating System anymore. When in gedit, all three buttons now type 'bcd' in the terminal. Looking at other issues, it looks like this could be an issue in the keyboard.py. I was unable to verify if that was a valid fix given that I don't have access to that file on my computer given my companies IT policies. Side note, the volume wheel still works.

**Comment by Arsimael-zz** [comment]
I don't want to reopen #1799, but after another reboot: I have the same issue again, The "Mute/Unmute" also only writes"bcd".

OS: Arch Linux (Kernel 5.17.1)
Huntsman V2 (GER Layout) 
OR-Vers: 3.3.0

**Comment by testcenter** [comment]
same for me.

OS: `pop!_OS 21.10` (Kernel: `5.16.15`)
Huntsman V2 (US Layout)
OpenRazer version: `3.3.0`

**Comment by kierun** [comment]
Came here to say the same thing… Sadly, when the keyboard was unsupported, they worked fine for me! :raised_eyebrow: 

OS: Fedora 36 with kernel `5.16.20-200.fc35.x86_64`
Huntsmnan V2 (UK Layout)
OpenRazer version: 

```
openrazer-kernel-modules-dkms-3.3.0-1.1.noarch
openrazer-daemon-3.3.0-1.1.noarch
python3-openrazer-3.3.0-1.1.noarch
openrazer-meta-3.3.0-1.1.noarch
```

**Comment by dlukitsch** [comment]
similar result with Ubuntu 22.04, when pressing them they always write `bcd`

OS: `Ubuntu 22.04 (Kernel: 5.17.5)`
Huntsman V2 (German Layout)
OpenRazer version: 3.3.0

**Comment by patrickscholz** [comment]
same problem here, pushing the media buttons always writes bcs...

OS: Ubuntu 20.04 (Kernel: 5.13.0)
Huntsman V2 (German Layout)
OpenRazer version: 3.3.0

I could make the media buttons work again by switching of the openrazor-deamon by hand with the command "openrazor-deamon -s"

**Comment by patrickscholz** [comment]
looks like one workaround can be found here https://github.com/openrazer/openrazer/issues/1398#issuecomment-961242268, at least that worked for me as well.

**Comment by Mai-Lapyst** [comment]
Tinkered a bit around with the driver and found out that following changes seems to fix the issue:

```
diff --git a/driver/razerkbd_driver.c b/driver/razerkbd_driver.c
index 9bd4212..434e339 100644
--- a/driver/razerkbd_driver.c
+++ b/driver/razerkbd_driver.c
@@ -2682,6 +2682,7 @@ static int razer_event(struct hid_device *hdev, struct hid_field *field, struct
 
     case USB_DEVICE_ID_RAZER_BLACKWIDOW_V3:
     case USB_DEVICE_ID_RAZER_BLACKWIDOW_V3_PRO_WIRED:
+    case USB_DEVICE_ID_RAZER_HUNTSMAN_V2:
         translation = find_translation(chroma_keys_5, usage->code);
         break;
 
@@ -2974,6 +2975,7 @@ static int razer_raw_event(struct hid_device *hdev, struct hid_report *report, u
     case USB_DEVICE_ID_RAZER_BLACKWIDOW_V3:
     case USB_DEVICE_ID_RAZER_ORNATA_V2:
     case USB_DEVICE_ID_RAZER_BLACKWIDOW_V3_PRO_WIRED:
+    case USB_DEVICE_ID_RAZER_HUNTSMAN_V2:
         return razer_raw_event_bitfield(hdev, asc, intf, report, data, size);
     default:
         return razer_raw_event_standard(hdev, asc, intf, report, data, size);
```

**Comment by kierun** [comment]
@Mai-Lapyst Could you please open a PR with the changes? Thank you.

**Comment by kierun** [comment]
@Mai-Lapyst Does your fix only work for play/pause or for previous and next as well?

**Comment by Mai-Lapyst** [comment]
@kierun It fixes all four buttons (play/pause, previous and next, mute)

**Comment by kierun** [comment]
> @kierun It fixes all four buttons (play/pause, previous and next, mute)

@Mai-Lapyst Awesome! Thank you so much.

**Comment by aprilborn** [comment]
2025 - still same problem))))))
Ubuntu 24.04 DeathStalker v2 wired.
Something with openrazer.
`pkill openrazer` fixes all media buttons, but after opening Polychromatic "bcd" comes back.

**Comment by z3ntu** [comment]
@EasySigh Please don't 'revive' years old issues that were about different devices. Check with the daily PPA, maybe #2503 has fixed it for you, not sure what exact device you own. Otherwise please open a new issue, feel free to reference this one so it's cross-linked.
