### ISSUE TITLE
Naga pro no battery notifications while turned off (wireless)

### ISSUE THREAD

**Issue by Ersmipe** [openrazer/razer-drivers#1801]
### Distribution

Ubuntu 21.10

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

My Naga pro notifies me every 10 minutes about 0% battery (which is not true) when turned off with wireless dongle connected.
I use naga only for gaming and my mx vertical for work, so it is a little annoying. Partial solution is to disconnect wireless dongle every time when I stop using naga.

Here is log (appears every ten minutes when notification is displayed):
kernel: razermouse: Command timed out. Start Marker: 04 id: 1f Num Params: 02 Reserved: 07 Command: 80 Params: 00000000000000000000000000000000 .

**Comment by greatbaracus** [comment]
I would be interested with any solution for your issue because, i also have a wireless mouse (but a Viper) and have more or less the same issue https://github.com/openrazer/openrazer/issues/1796

But also here https://github.com/openrazer/openrazer/issues/1749
