### ISSUE TITLE
Changes persist even after uninstalling

### ISSUE THREAD

**Issue by SpoodyTheOne** [openrazer/razer-drivers#1806]
After messing around with openrazer and razercommander i realized it had messed with my sensitivity (which i had no idea how to match the settings it had before, which i had grown accustomed to) so i uninstalled it, yet the changes to my keyboard lighting and sensitivity are still present, even when theres no trace of openrazer left.

**Comment by z3ntu** [comment]
Possibly that the device remembers the changed DPI. You can change it either by installing OpenRazer again and changing it with that, or using Razer Synapse on Windows.
