### ISSUE TITLE
Basilisk v3 Settings Change On Dual Boot System

### ISSUE THREAD

**Issue by 0pLuS0** [openrazer/razer-drivers#1807]
### Distribution
Slackware 15.0 x86_64

### Name and version
openrazer 3.3.0
polychromatic-0.7.3

### Support

- [ x] Have you tried rebooting? ```YES```
- [ x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page? ```YES```

My system is Dual Boot, Windows 10 and Slackware 15.0.

I'm using polychromatic-0.7.3, I don't know if it plays a part in any of this, or these issues are strictly from Openrazer.

When I shut the computer down inside Windows, and of course I use Synaptics 3 in Windows, then when I start the computer back up and boot into Linux, I see this problem. The mouse keeps cycling through the colors, like it's on the default settings, and I placed polychromatic on Static for the lighting effect, with the default Razer Green color. The problem is that the setting doesn't take effect until I log into X.

If I shut down the computer in Linux, and then start the computer, and boot into Linux, there isn't this issue. The mouse options stick as soon as I start up Slackware, half way through the boot up, when Openrazer loads, the mouse goes solid green.

I wish, when I shutdown the computer in Windows, and at some later point in time, when I start the computer, and then boot into Linux, that the mouse settings would stick right when Openrazer is loaded, because many times I just work in the console and I don't log into X, and then the mouse is sitting there cycling through the colors while I'm working in the console.

I personally don't like the colors cycling, it's distracting, and I would love to figure out if it's possible for me to correct, or this is just a limitation of the mouse and sofware, and running Dual Boot, with Synapse in Windows and Openrazer in Linux.

THANKS

**Comment by lah7** [comment]
From https://github.com/polychromatic/polychromatic/issues/419:

> It's likely because Razer Synapse handles everything in software, so when that takes over, the hardware is back to a default spectrum upon next power cycle. The hardware effect becomes "software" rather then "static". Some firmware might be smart enough to use the last hardware effect.
>
> The trouble is, even when Windows applies the static effect, it's actually sending a different command, like "draw a frame with all LEDs green" **(software)** rather then "activate the static effect hardware that's green" **(hardware).** If you're just wanting the same settings on both, the solution might be to uninstall Razer Synapse on Windows (and I mean, make sure it's **fully** removed), then use OpenRazer to set the hardware effect.
>
> Since OpenRazer daemon is a user process, it's only running as soon as you log on (on most distros). Unlike Razer Synapse which I think is a Windows  driver. If you do use Razer Synapse, you could [use the OpenRazer driver sysfs directly](https://github.com/openrazer/openrazer/wiki/Using-the-keyboard-driver) by echoing a file (as root or plugdev) during system boot up.
>
> Equally, OpenRazer doesn't technically know what the hardware is actually doing, which is where the persistence comes in. Until Razer Synapse is removed from the equation, that particular device will reset to spectrum on next power up.

**Comment by 0pLuS0** [comment]
Yes ```OpenRazer daemon is a user process```

BUT I use in Slackware ```/etc/rc.d/rc.modules.local;```

### /sbin/razerkbd 

I don't have to log on, as you are mentioning, the OpenRazer daemon is suppose to be loaded at bootup.

So then, I should not be seeing this issue I assumed, where I'm having to log into X, that goes against the concept of loading the module with ```/etc/rc.d/rc.modules.local```. This to me, sorry I didn't really mention this, is the problem I see.

I have in ~/.config/openrazer/razer.conf;
restore_persistence = True

With the razer.conf set at restore_persistence = True and loading the module at boot up with the rc.modules.local, this to me, in how things have always worked with loading modules at bootup, I assumed the mouse goes Static as I've set it, just sitting in the console and not even logged into Slackware. But, when I do log into Slackware, I don't use a login manager, I simply type in a user/pass and then type startx at the console.

So why, now, in what I've explained before, is it that I have to log into X to get it to stick, after I am in Windows? That makes no sense, because when the openazer daemon is loaded, isn't that suppose to be when the settings are applied? I don't see what logging into X has to do with when the openrazer daemon is started, because with the rc.modules.local, the dameon is being loaded before I log into X.

THANKS

**Comment by 0pLuS0** [comment]
@lah7 Hi,

It would be nice to leave this open, because this has been an ongoing issue for me, with two versions of Openrazer, polychromatic and using Windows 10 and Windows 11 while dual booting with Slackware, and I still can't figure this out.

For me, now the problem is, the Keyboard Effects don't work, only the Static using a Huntsman v2 Tenkeyless. 1532:026B

THANKS

**Comment by lah7** [comment]
> I don't see what logging into X has to do with when the openrazer daemon is started, because with the rc.modules.local, the dameon is being loaded before I log into X.

Which user is it running as? I'm guessing `root`.  IIRC, there is weirdness running the daemon as root, because the daemon uses the **session bus** of the user, and root also uses a different config/persistence file (`/root/.config/...`)

It probably works when you log in to X because:

*  `openrazer-daemon` wasn't running as your user.
* Auto starting `polychromatic-tray-applet` is going to summon the daemon (via D-Bus).
* `openrazer-daemon` starts, reads your persistence file and restores effects, as expected.

**Possible solutions:**

* Make it so `rc.modules.local` starts `openrazer-daemon` as your user.
   * _Also double check devices do appear in the log, in case the daemon can't see them under non-X11 for some reason._
* Or use sysfs (as suggested in [#2002](https://github.com/openrazer/openrazer/issues/2002#issuecomment-1384429897) - see below). **No daemon required!**

## sysfs driver
It cuts out the middleman by echo'ing to the driver files directly. It might work better for your Slackware set up.

Put this in a bash script that runs at system boot (after drivers `razerkbd`, `razermouse` have loaded)

    echo -n -e "\xFF\x00\xFF" > /sys/bus/hid/drivers/razerkbd/*:1532:0214.*/matrix_effect_static
    echo -n -e "\xFF\x00\xFF" > /sys/bus/hid/drivers/razermouse/*:1532:0046.*/matrix_effect_static

Adjust as necessary to your hardware PID. This works as `root` or any user in the `plugdev` group (should already be the case)

**Comment by lah7** [comment]
> For me, now the problem is, the Keyboard Effects don't work, only the Static using a Huntsman v2 Tenkeyless. 1532:026B

Has Razer Synapse recently (auto-)updated the firmware of the device?

If it just recently started happening, that's the only reason I can think of. Quite possible that what was implemented (#1754) for this device under OpenRazer is no longer compatible with your firmware version now?

**Comment by 0pLuS0** [comment]
No there have not been any recent updates for Synapse.

I have a Baslisk Essential I bought last month, so I am using that now, instead of the v3 which was defective.

I uninstalled openrazer-daemon and kernel and polychromatic and all the cache and config files too, then rebooted, then reinstalled everything.

Now, only the Ripple & Reactive Effects I can't get to to work when I first booted into Slackware.

But, sometimes when I play around clicking on different Effects, then I click on Static, it doesn't work either, so then I click on the other Effects that work, then go back to Static and it will work.

Seems to be a bug here, where I have to keep playing around with the keyboard effects, in order to get them working.

**Comment by 0pLuS0** [comment]
After playing with this for several hours, I still can't get a lot of the Keyboard Effects to work, and then some that work, if I play around with the other effects then go back to an effect that was previously working, sometimes it too will stop. Then I have to go back clicking through the effects and refreshing polychromatic to get an effect working again that stopped.

I beleive I mentioned it before, I uninstalled openrazer and polychromatic, cleaned it all out, then compiled/reinstalled over and still no good with the keyboard effects.

The keyboard effects all work in Windows, for whatever reason, there's an issue with openrazer support and this keyboard for me.

```Huntsman v2 Tenkeyless 1532:026B```

THANKS
