### ISSUE TITLE
Suggestion: Secondary color choosing ability

### ISSUE THREAD

**Issue by Decapitater** [openrazer/razer-drivers#1808]
Secondary Color is referred to the color that shows up when either CAPS key or Fn Key (specially for mini keyboard ie Razer Huntsman mini) or any other mutimedia bindings ,

it would be cool to have option to change those lights and yes its possible , i have seen them in different color somehow . 

I was told that its something that maybe worth exploring for openrazer. 

Originally posted https://github.com/polychromatic/polychromatic/issues/420

**Comment by z3ntu** [comment]
@lah7 I guess this would be basically software effects?

**Comment by lah7** [comment]
Software probably could handle it, but I think it's a firmware "feature". Whether it's configurable or not or simply undocumented, I don't know.

Some Razer Blade's _apparently_ will colour the top FN row green while FN is pressed, regardless of what the software is drawing.

**Comment by z3ntu** [comment]
Then packet captures of this are needed :)

**Comment by Decapitater** [comment]
@z3ntu i may get ya some will those help ?

**Comment by z3ntu** [comment]
@Decapitater This is how you get pcaps: https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol

What exactly to toggle around in Synapse I don't know. But if it's a firmware feature and it's getting enabled somehow then this will show us.
