### ISSUE TITLE
Sync across all functionality improvement (Breath only allows one colour)

### ISSUE THREAD

**Issue by DMJC** [openrazer/razer-drivers#1813]
### Distribution

Debian Linux 12 Bookworm, Polychromatic 0.7.3

### Support

-Permissions are fine.
- Have restarted the daemon/services. I can apply effects to my devices.

When I select apply to all: Breath, all my devices get set to green and changing the colour/applying it works, however when I go back to apply to all and click breath again, green is again the default selected. Also when I select Breath under apply to all there is never an option to set a secondary colour, or set random colours. I like to use Breath with pink/blue so I get a nice synthwave style effect. Can this be fixed to add the missing functionality?

**Comment by lah7** [comment]
"Apply to All" is a [Polychromatic](https://github.com/polychromatic/polychromatic) thing. It's supposed to be a convenient "quick" feature to set a simple hardware effect for all compatible devices, which don't always support the same parameters, so showing every possible option is complicated.

There's a "presets" feature **planned** in that software, which will achieve what you're looking for. The idea being you can set up devices how you like and then apply in one go.

For now, you can set devices independently, or create a Python script to interface with OpenRazer directly [(see examples in this repository)](https://github.com/openrazer/openrazer/tree/master/examples). When scripting, this can be used to apply a command to all devices:
```python
device_manager.sync_effects = True
```
