### ISSUE TITLE
Blackwidow X Chroma pressing random key and stuck on the key

### ISSUE THREAD

**Issue by aunsid** [openrazer/razer-drivers#1814]
### Support

- [ yes ] Have you tried rebooting?
- [ yes ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I can type some words and then random key pressed, caps lock goes on and then it keeps repeating 
For. eg. ashJ'\LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL

`lsusb | grep 1532`
`Bus 001 Device 002: ID 1532:0216 Razer USA, Ltd BlackWidow X Chroma`

`uname -r`
`5.13.0-41-generic`

`sudo dkms status`
```
openrazer-driver, 2.5.0, 5.13.0-41-generic, x86_64: installed
openrazer-driver, 2.5.0, 5.4.0-110-generic, x86_64: installed
```

**Comment by lah7** [comment]
I have a similar quirk with my older, BlackWidow Chroma too. Vast majority of the time, it's hardly a problem, but very rarely a key I just pressed will repeat itself until pressed again.

See also: #591. Firmware updates (on Windows with Razer Synapse) may help.

If you can easily reproduce it on your keyboard, please try stopping the daemon and unloading the driver, and see if it still happens.

    openrazer-daemon -s
    sudo rmmod razerkbd
