### ISSUE TITLE
dependency cannot be fulfilled || openrazer-driver-dkms

### ISSUE THREAD

**Issue by Cuvy95** [openrazer/razer-drivers#1821]
### Distribution

openrazer 3.3.0
Debian 11

### Support

- [ x] Have you tried rebooting?
- [ x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Hello Community, 
at first i want to say that this is my first post at Github, sorry for any mistakes.
im come from Germany and i use Parrot Os since 3 weeks. 
Now i will install openrazer but everytime when i download the .deb file from the official Homepage and i want to install it i become these Message : 

"Fehler Abhängikeit nicht erfüllbar: openrazer-driver-dkms (=3.3.0-0)"

I dont know what i can do to install it. 
I hope anyone can help me :)

**Comment by z3ntu** [comment]
Please explain how you're trying to install it.

**Comment by Cuvy95** [comment]
I downloaded it at this page [https://software.opensuse.org/download.html?project=hardware%3Arazer&package=openrazer-meta](url)
and then i double click on the .deb file.

**Comment by z3ntu** [comment]
Yeah, that won't work. Please use the way "Add repository and install manually" that adds the repository to your apt repo list.

**Comment by Cuvy95** [comment]
i have tried it now and now i become these error (see in the picture
![error](https://user-images.githubusercontent.com/89508877/170830773-2f80dd78-683f-4da5-b34c-efd26c3b5b81.png)
)

**Comment by z3ntu** [comment]
Try removing the `openrazer-meta` package completely and then reinstall it.

**Comment by Cuvy95** [comment]
i uninstalled it , but now comes this 
![error2](https://user-images.githubusercontent.com/89508877/170830884-4d604d98-b0ab-41ac-9eec-7c7cd9cc2cea.png)
:

**Comment by z3ntu** [comment]
Not sure. Dpkg is always cryptic in what it does and I don't use Debian so please ask for help in some Debian or Parrot support channel.

**Comment by Cuvy95** [comment]
OK thanks for your help :)

**Comment by Etaash-mathamsetty** [comment]
> i uninstalled it , but now comes this ![error2](https://user-images.githubusercontent.com/89508877/170830884-4d604d98-b0ab-41ac-9eec-7c7cd9cc2cea.png) :

its complaining that openrazer-meta is already not installed (so it cant remove anything lol), so just manually remove openrazer-driver-dkms openrazer-daemon and python3-openrazer
`sudo apt remove openrazer-driver-dkms openrazer-daemon python3-openrazer`
then try (it should work if you added the repository)
`sudo apt install openrazer-meta`
if that doesn't work, try 
`sudo apt update && sudo apt upgrade`
and then
`sudo apt install openrazer-meta`
ps: english and german seem really similar, guess I should try learning german!
