### ISSUE TITLE
Razer Viper Ultimate erratic mouse sensitivity

### ISSUE THREAD

**Issue by rantnar** [openrazer/razer-drivers#1822]
I have this problem with my mouse. Both dock and mouse are recognized by openrazer and are working. But for some reason mouse sens ich constantly changing. I tried ubuntu, arch, fedora. x11 and wayland. Still same behaviour. Mouse dongle is connected to the dock.

**Comment by lah7** [comment]
When you say the mouse sensitivity constantly changes, do you mean randomly, or is it different every time you log in?

What desktop environment are you using? Have you checked for any "mouse acceleration" settings?

For example, in KDE:

![image](https://user-images.githubusercontent.com/13032135/171459623-2f1bc221-a9da-4af8-8f21-f02a347e7de8.png)

Any sort of "acceleration" setting might be something to check.

**Comment by rantnar** [comment]
Thanks for answering.
I use flat acceleration profile. What i mean by by erratic mouse sensitivity is that it changes constantly, randomly, on the fly. Acceleration is always flat i checked that its just the sensitivity thats changing.  Its noticable because changes are random and big to the point when there isnt enough space on my desk to move the mouse from one corner to another.

Ive also checked and plugged mouse directly to my computer, not the dongle. Same behaviour.
Also the problem is much less noticeable, but still exists on 125Hz polling rate. So that could be a clue.

**Comment by lah7** [comment]
Have you tried without OpenRazer installed, a different system, or with Razer Synapse on Windows?

I don't really know what on OpenRazer's side could cause this, as it's only adjusting hardware parameters. Could it be a fault with the mouse, or maybe just a dirty sensor?

`libinput` could _potentially_ be a culprit on the software side, but only if this problem started happening recently with a system update.  #1690 found that an update started causing erratic scrolling.

On the hardware side, a higher polling rate means more CPU polling, so there is the possibility there is a bottleneck in your system or USB bus. Have you tried a different port or unplugged other USB devices?

**Comment by rantnar** [comment]
It's fixed. I'm using UNRAID and passing through usb devices to a VM. It was my VM configuration that was problematic.. My usb controller was set to 3.0 qemu XHCI. For some reason it is problematic on linux VM, not on windows VM. Setting usb controller to 2.0 ehci fixes the issue with mose sens and polling rate. Sorry to bother you.

**Comment by lah7** [comment]
Good to hear! Thanks for feeding back.

For what it's worth, if Razer Synapse ever offers a firmware upgrade, say **no**. @z3ntu ended up with a bricked Razer device because of USB passthrough to a VM.
