### ISSUE TITLE
Huntsman tkl 1532:026b not reckonised 

### ISSUE THREAD

**Issue by wolfbiteaus** [openrazer/razer-drivers#1824]
Support for Razer Huntsman V2 Tenkeyless #1681 
https://github.com/openrazer/openrazer/issues/1681
Device Info
    Name: Razer Huntsman V2 Tenkeyless
    Product Number: RZ03-03940600-R3F1
    Model Number: RZ03-0394
ThomChroma added the Device Support label Nov 26, 2021
@z3ntu z3ntu added the need pcap label Dec 3, 2021

**Comment by z3ntu** [comment]
The device is not supported yet. Did you build from source with https://github.com/openrazer/openrazer/pull/1754 ?
