### ISSUE TITLE
I installed open razer daemon, but this error still appears

### ISSUE THREAD

**Issue by korolipliaja** [openrazer/razer-drivers#1828]
× openrazer-daemon.service - Daemon to manage razer devices in userspace
     Loaded: loaded (/usr/lib/systemd/user/openrazer-daemon.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2022-06-04 19:23:11 EEST; 24s ago
       Docs: man:openrazer-daemon(8)
    Process: 33523 ExecStart=/usr/bin/openrazer-daemon -F (code=exited, status=1/FAILURE)
   Main PID: 33523 (code=exited, status=1/FAILURE)
        CPU: 86ms

Jun 04 19:23:11 RyanGosling openrazer-daemon[33523]: 2022-06-04 19:23:11 | razer                          | CRITICAL | Please run the command 'sudo gpasswd -a $USER plugdev' and then reboot!
Jun 04 19:23:11 RyanGosling openrazer-daemon[33523]: Stopping daemon.
Jun 04 19:23:11 RyanGosling openrazer-daemon[33523]: Exception ignored in atexit callback: <bound method Daemonize.exit of <daemonize.Daemonize object at 0x7fc7505aee00>>
Jun 04 19:23:11 RyanGosling openrazer-daemon[33523]: Traceback (most recent call last):
Jun 04 19:23:11 RyanGosling openrazer-daemon[33523]:   File "/usr/lib/python3.10/site-packages/daemonize.py", line 72, in exit
Jun 04 19:23:11 RyanGosling openrazer-daemon[33523]:     sys.exit(0)
Jun 04 19:23:11 RyanGosling openrazer-daemon[33523]: SystemExit: 0
Jun 04 19:23:11 RyanGosling systemd[700]: openrazer-daemon.service: Main process exited, code=exited, status=1/FAILURE
Jun 04 19:23:11 RyanGosling systemd[700]: openrazer-daemon.service: Failed with result 'exit-code'.
Jun 04 19:23:11 RyanGosling systemd[700]: Failed to start Daemon to manage razer devices in userspace.

v

**Comment by z3ntu** [comment]
Please read and follow the error message

> Please run the command 'sudo gpasswd -a $USER plugdev' and then reboot!
