### ISSUE TITLE
I have a supported device but razergenie says I don't.

### ISSUE THREAD

**Issue by DataBase137** [openrazer/razer-drivers#1829]
I have a Razer Basilisk X Hyperspeed which is listed on the supported devices, yet RazerGenie says I don't.

**Comment by lah7** [comment]
It could mean an old version is installed, or OpenRazer wasn't installed properly. [(See the Troubleshooting guide if it's the latter)](https://github.com/openrazer/openrazer/wiki/Troubleshooting).

What version of OpenRazer? The latest right now is 3.3.0.

    openrazer-daemon --version

Which distro? Did you install it using the instructions on https://openrazer.github.io?

**Comment by DataBase137** [comment]
I have 3.3.0 installed, and I'm on Fedora 36 Workstation Edition.

**Comment by DataBase137** [comment]
So I actually installed it via the GNOME store, but I uninstalled it now, and installed it the way you have it on the guide, but now I don't have the application.

**Comment by lah7** [comment]
Maybe you need to install RazerGenie again?

I noticed on the [Flatpak page](https://flathub.org/apps/details/xyz.z3ntu.razergenie), there is this:

> Requires OpenRazer to be installed outside of flatpak via a distribution package.

In theory, we should be on the right track. Unless there's [something else that's needs addressing](https://github.com/openrazer/openrazer/wiki/Troubleshooting) (like plugdev, secure boot, etc)

**Comment by DataBase137** [comment]
Well if I install RazerGenie it says I don't have a supported device
![Screenshot from 2022-06-05 10-04-19](https://user-images.githubusercontent.com/94127434/172061811-507e8377-2bfc-475c-b60f-c3d18c9daac7.png)
.

**Comment by lah7** [comment]
That must mean that OpenRazer isn't set up on your computer properly. Please try 2, 3 and 4 from this troubleshooting guide and let us know if you get stuck:

https://github.com/openrazer/openrazer/wiki/Troubleshooting

**Comment by DataBase137** [comment]
With the 2nd option, I got this error:
Error! Could not find module source directory.
Directory: /usr/src/openrazer-driver-3.3.0 does not exist.

**Comment by DataBase137** [comment]
With the 3rd option, I got this error:
modprobe: FATAL: Module razerkbd not found in directory /lib/modules/5.17.11-300.fc36.x86_64

**Comment by lah7** [comment]
The driver isn't installed. Which distro are you using?

**Comment by DataBase137** [comment]
Fedora 36 with GNOME 42.2

**Comment by z3ntu** [comment]
Did you follow the installation instructions? https://openrazer.github.io/#fedora

**Comment by DataBase137** [comment]
Yes, I did.

**Comment by z3ntu** [comment]
`ls -al /usr/src/` ?

**Comment by forza91** [comment]
:~$ ls -al /usr/src/
总用量 28
drwxr-xr-x  7 root root 4096 6月   8 12:25 .
drwxr-xr-x 14 root root 4096 10月 23  2021 ..
drwxr-xr-x  7 root root 4096 10月 23  2021 linux-headers-5.11.0-38-generic
drwxr-xr-x  7 root root 4096 6月   6 16:27 linux-headers-5.13.0-44-generic
drwxr-xr-x 24 root root 4096 10月 23  2021 linux-hwe-5.11-headers-5.11.0-38
drwxr-xr-x 24 root root 4096 6月   6 16:27 linux-hwe-5.13-headers-5.13.0-44
drwxr-xr-x  3 root root 4096 6月   8 12:46 openrazer-driver-3.3.0

Same device and same issue here with Polychromatic.    
PID: 1532:009c
Ubuntu 20.04/Zorin 16
Tried on both statble and daily PPA.

Not supported yet? #1339 #1307

**Comment by DataBase137** [comment]
I'm fine without razer for now.

**Comment by DataBase137** [comment]
I'm fine without razer for now.

**Comment by nightsky30** [comment]
> :~$ ls -al /usr/src/ 总用量 28 drwxr-xr-x 7 root root 4096 6月 8 12:25 . drwxr-xr-x 14 root root 4096 10月 23 2021 .. drwxr-xr-x 7 root root 4096 10月 23 2021 linux-headers-5.11.0-38-generic drwxr-xr-x 7 root root 4096 6月 6 16:27 linux-headers-5.13.0-44-generic drwxr-xr-x 24 root root 4096 10月 23 2021 linux-hwe-5.11-headers-5.11.0-38 drwxr-xr-x 24 root root 4096 6月 6 16:27 linux-hwe-5.13-headers-5.13.0-44 drwxr-xr-x 3 root root 4096 6月 8 12:46 openrazer-driver-3.3.0
> 
> Same device and same issue here with Polychromatic. PID: 1532:009c Ubuntu 20.04/Zorin 16 Tried on both statble and daily PPA.
> 
> Not supported yet? #1339 #1307

Both of those issues refer to the Basilisk X Hyperspeed and don't match the PID you provided. PID: 1532:009c seems to be the DeathAdder V2 X HyperSpeed. You may want to take a look at #1711 #1773

**Comment by forza91** [comment]
> > :~$ ls -al /usr/src/ 总用量 28 drwxr-xr-x 7 root root 4096 6月 8 12:25 . drwxr-xr-x 14 root root 4096 10月 23 2021 .. drwxr-xr-x 7 root root 4096 10月 23 2021 linux-headers-5.11.0-38-generic drwxr-xr-x 7 root root 4096 6月 6 16:27 linux-headers-5.13.0-44-generic drwxr-xr-x 24 root root 4096 10月 23 2021 linux-hwe-5.11-headers-5.11.0-38 drwxr-xr-x 24 root root 4096 6月 6 16:27 linux-hwe-5.13-headers-5.13.0-44 drwxr-xr-x 3 root root 4096 6月 8 12:46 openrazer-driver-3.3.0
> > Same device and same issue here with Polychromatic. PID: 1532:009c Ubuntu 20.04/Zorin 16 Tried on both statble and daily PPA.
> > Not supported yet? #1339 #1307
> 
> Both of those issues refer to the Basilisk X Hyperspeed and don't match the PID you provided. PID: 1532:009c seems to be the DeathAdder V2 X HyperSpeed. You may want to take a look at #1711 #1773

oh sorry for mixing that up. I have read these two issues but I am not sure if the driver of V2 X HyperSpeed is contained in V3.3.0. Because it said "The following PIDs are not supported in the lastest stable release..". I installed with Ubuntu 20.04 Stable PPA, then I switched to Daily PPA. Still can't make it works, I will leave a commit there, thank you

Bus 003 Device 015: ID 1532:009c Razer USA, Ltd Razer DeathAdder V2 X HyperSpeed
