### ISSUE TITLE
Support for [blackwidow te chroma v2]

### ISSUE THREAD

**Issue by itstonylin** [openrazer/razer-drivers#1831]
### Device Info

* Name: blackwidow te chroma v2
* Product Number: RZ03-0219
* Model Number: RZ03-02190700-R3M1

### Device Information
```
Please post the output of
    lsusb -d 1532: -v
```

```
Please post the output of
    ls -lah /dev/input/by-id/
```

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on **Razer Synapse** in a Windows Environment>

**Comment by z3ntu** [comment]
Please provide `lsusb | grep 1532`. But I'm quite sure the device is already supported since multiple years. Have you checked the troubleshooting page? https://github.com/openrazer/openrazer/wiki/Troubleshooting
