### ISSUE TITLE
Razer gentie don't see my mouse

### ISSUE THREAD

**Issue by korolipliaja** [openrazer/razer-drivers#1832]
![razrt](https://user-images.githubusercontent.com/69907714/172140601-09169381-a77f-4a7c-81b7-95b4cddedaca.jpg)
![support](https://user-images.githubusercontent.com/69907714/172140610-bab37d4d-c91f-43f2-9042-a97277f224a8.jpg)

**Comment by z3ntu** [comment]
Did you check our troubleshooting guide? https://github.com/openrazer/openrazer/wiki/Troubleshooting

**Comment by Etaash-mathamsetty** [comment]
can you paste the lsusb output of the mouse too?

**Comment by korolipliaja** [comment]
> Did you check our troubleshooting guide? https://github.com/openrazer/openrazer/wiki/Troubleshooting

Thanks it helps me
