### ISSUE TITLE
Request: Support for Huntsman v2 1523:026B

### ISSUE THREAD

**Issue by 0pLuS0** [openrazer/razer-drivers#1839]
### Distribution

Slackware 15.0

### Support

- [X ] Have you tried rebooting?
- [X ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I believe that Huntsman v2 1523:026B is not supported, I didn't see it listed, and wanted to ask, will there be support for it soon? I just received the keyboard today, so I really hope there will be support soon.

Here's a screen shot in Polychromatic showing it failed.

![polychromatic](https://user-images.githubusercontent.com/36190223/174424372-fe982675-c216-4e95-a6d8-c643dac96aba.png)

```THANKS```

**Comment by z3ntu** [comment]
Duplicate of #1681

**Comment by 0pLuS0** [comment]
@openrazer

I was told this was released then the post was closed, so I couldn't ask, how/where was it released?

I'm already using 3.3.0

THANKS

**Comment by z3ntu** [comment]
The device is not yet supported as indicated in the linked issue. However there's an open pull request for this device, you can try building that and testing it. Instructions you can find in the wiki "building a package" the page is called

**Comment by 0pLuS0** [comment]
Ok, any chance of knowing when it's expected?

THANKS

**Comment by z3ntu** [comment]
Whenever it's ready.
