### ISSUE TITLE
Having problems getting headers to use with openrazer

### ISSUE THREAD

**Issue by CobraA1** [openrazer/razer-drivers#1843]
### Distribution

Manjaro 21.0

### Support

- [x] Have you tried rebooting?

Yes

- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Yes

The troubleshooting page indicates I am missing linux-headers, but I am unable to obtain them. Would like advice on how to approach this and who to contact.

![Screenshot_20220623_170834](https://user-images.githubusercontent.com/8573502/175423663-2c451295-3971-485d-a88a-b228d5be1d96.png)

**Comment by z3ntu** [comment]
Update your system (pacman -Syu) and then it should work

**Comment by CobraA1** [comment]
> Update your system (pacman -Syu) and then it should work

That fixes it, thanks!

Perhaps make a note on the [troubleshooting page](https://github.com/openrazer/openrazer/wiki/Troubleshooting)?

**Comment by z3ntu** [comment]
Tbh that's not a common problem and definitely not at all related to openrazer. Any time you're getting a 404 error with pacman either your mirror is quite broken or you haven't updated your package lists. And partial updates have also never been supported in Arch Linux and I assume neither in Manjaro.
