### ISSUE TITLE
Trackpad stops working after waking from suspend

### ISSUE THREAD

**Issue by kaykhan** [openrazer/razer-drivers#1847]
### Distribution

ubuntu 22
razer blade 15 mid 2021 (RZ09-0409) 

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

After i wake up the laptop from suspend the trackpad no longer works and the screen is set to full brightness.

**Comment by z3ntu** [comment]
Hi, does this issue also happen without OpenRazer installed?

**Comment by kaykhan** [comment]
> Hi, does this issue also happen without OpenRazer installed?

i didint check, probably exists without OpenRazer installed

**Comment by z3ntu** [comment]
Then it's nothing we can fix unfortunately.
