### ISSUE TITLE
Razer VIPERMINI Unrecognised Device

### ISSUE THREAD

**Issue by KevinChen-CMYK** [openrazer/razer-drivers#1852]
### Support

- [ ] Have you tried rebooting?
- [ ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Kernel module has been built for this kernel
sudo dkms install -m openrazer-driver/3.3.0

Binary sign-file not found, module won't be signed
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Error! Your kernel headers for kernel 5.19.0-1-MANJARO cannot be found at /usr/lib/modules/5.19.0-1-MANJARO/build or /usr/lib/modules/5.19.0-1-MANJARO/source.
Please install the linux-headers-5.19.0-1-MANJARO package or use the --kernelsourcedir option to tell DKMS where it's located.

Kernel module can be probed
Kernel module is loaded
sudo modprobe razerkbd

modprobe: FATAL: Module razerkbd not found in directory /lib/modules/5.19.0-1-MANJARO

**Comment by z3ntu** [comment]
Please don't open duplicate issues. Continuing in #1853
