### ISSUE TITLE
DeathAdder V2 x Hyperspeed - Unrecognised 

### ISSUE THREAD

**Issue by jrwagh333** [openrazer/razer-drivers#1854]
OpenRazer detects a device but has no idea what it is. I see that the BlackWidow Hyperspeed and other Hyperspeed devices are supported, but unfortunately not the DeathAdder. 

Please could somebody provide directions on how I can provide the necessary information to get the device added to the software in an update.

**Comment by z3ntu** [comment]
Please provide output of `lsusb | grep 1532`

**Comment by Etaash-mathamsetty** [comment]
> OpenRazer detects a device but has no idea what it is. I see that the BlackWidow Hyperspeed and other Hyperspeed devices are supported, but unfortunately not the DeathAdder.
> 
> Please could somebody provide directions on how I can provide the necessary information to get the device added to the software in an update.

I am pretty sure this mouse is already supported, it's just that open razer hasn't got a new release with support for the mouse

**Comment by jrwagh333** [comment]
> > OpenRazer detects a device but has no idea what it is. I see that the BlackWidow Hyperspeed and other Hyperspeed devices are supported, but unfortunately not the DeathAdder.
> > Please could somebody provide directions on how I can provide the necessary information to get the device added to the software in an update.
> 
> I am pretty sure this mouse is already supported, it's just that open razer hasn't got a new release with support for the mouse

I can't see it listed on the website

**Comment by Etaash-mathamsetty** [comment]
> > > OpenRazer detects a device but has no idea what it is. I see that the BlackWidow Hyperspeed and other Hyperspeed devices are supported, but unfortunately not the DeathAdder.
> > > Please could somebody provide directions on how I can provide the necessary information to get the device added to the software in an update.
> > 
> > 
> > I am pretty sure this mouse is already supported, it's just that open razer hasn't got a new release with support for the mouse
> 
> I can't see it listed on the website

check readme.md under supported mice
picture: 
![image](https://user-images.githubusercontent.com/45927311/179573613-6d6f5d2c-2752-41f4-8f37-77059c3eb933.png)

**Comment by jrwagh333** [comment]
Hmm, thanks for that. Polychromatic sees it as an Unsupported Device though.

**Comment by z3ntu** [comment]
@jrwagh333 It's not part of the latest release v3.3.0, only supported in git master yet. On Ubuntu you can install the daily packages, or on Arch Linux openrazer-git. For other distros you can build the package from source youself: https://github.com/openrazer/openrazer/wiki/Building-a-package
