### ISSUE TITLE
Support for Ornata V3

### ISSUE THREAD

**Issue by broomhead** [openrazer/razer-drivers#1855]
### Device Info

* Name: Ornata V3/V3X
* Product Number: RZ03-04470200-R3U1
* Model Number: RZ03-0447

### Device Information
```
      Razer Ornata V3 X:

              Product ID: 0x0294
              Vendor ID: 0x1532
              Version: 2.00
              Speed: Up to 12 Mb/s
              Manufacturer: Razer
              Location ID: 0x14210000 / 7
              Current Available (mA): 500
              Current Required (mA): 500
              Extra Operating Current (mA): 0
```

```
Please post the output of
    ls -lah /dev/input/by-id/
```

Not sure we have an equivalent to this on OSX

### Synapse Screenshots
I have OSX so I'm stuck on Synapse 2, which does not detect this device.

**Comment by z3ntu** [comment]
This project does not support macOS, only Linux.

**Comment by broomhead** [comment]
There are OSX builds and this project is referenced by multiple sources on how to customize your Razer products on Mac. Seems to work for other devices; this Ornata V3 is very new I think.

**Comment by z3ntu** [comment]
I'm aware that there are other projects supporting macOS, but definitely not OpenRazer itself, so I'm not really sure why you're here and not at the project page for whatever project you're using/wanting to use on macOS.

**Comment by broomhead** [comment]
Yep, trying to see how we got here. Looks like another project linked to OpenRazer which has a link back to here. Didn't realize the jump.

**Comment by broomhead** [comment]
I would add, however, that the request is for new Razer hardware support. Given the other project just ports the drivers from this project to OSX (https://github.com/1kc/razer-macos), it will likely need this project to support the new Ornata V3 keyboards that are out now.

**Comment by bogdan-marian** [comment]
My old keyboard drowned in a sea of coffee. Now I've upgraded to Ornata V3 and I'm ready to rule over its fancy features!

**Comment by z3ntu** [comment]
This device is now tracked in #1947
