### ISSUE TITLE
Any support for Razer Blackwidow Mini V3 on Mac?

### ISSUE THREAD

**Issue by jm74221** [openrazer/razer-drivers#1862]
### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I’ve been trying to connect my new Blackwidow v3 mini keyboard to the program but it just says “please select a device to configure”. Is this device supported?

**Comment by z3ntu** [comment]
This project never supported macOS and likely never will. Please reach out to the people maintaining whatever macOS project you are using.
