### ISSUE TITLE
installed openrazer and polychromatic, not one of my devices in recognized

### ISSUE THREAD

**Issue by sospwa** [openrazer/razer-drivers#1865]
these are the razer products I have and their ID

Bus 003 Device 004: ID 1532:0f17 Razer USA, Ltd Razer Tomahawk Chassis
Bus 001 Device 007: ID 1532:0228 Razer USA, Ltd BlackWidow Elite
Bus 001 Device 006: ID 1532:051a Razer USA, Ltd Nari Ultimate
Bus 001 Device 005: ID 1532:0511 Razer USA, Ltd RZ19-0229 Gaming Microphone
Bus 001 Device 012: ID 1532:007e Razer USA, Ltd RC30-030502 Mouse Dock
Bus 001 Device 011: ID 1532:0088 Razer USA, Ltd Gaming Mouse [Basilisk Ultimate, Wireless, Receiver]

**Comment by lah7** [comment]
These devices are supported:

* Razer BlackWidow Elite | 1532:0228
* Razer Mouse Dock | 1532:007E
* Razer Basilisk Ultimate (Receiver) | 1532:0088

Please run **Troubleshoot** in Polychromatic to see what is failing. You can check these with the [troubleshooting guide](https://github.com/openrazer/openrazer/wiki/Troubleshooting) to fix the most common installation problems.

---

**Razer Tomahawk Chassis** (1532:0F17) is new. Please [create a separate issue](https://github.com/openrazer/openrazer/issues/new/choose) using the **New Device Support** template so this can be supported in future.

**Razer Nari Ultimate** (1532:051A) is known, but hasn't been implemented:
*  #974

**Razer Seiren X** (1532:0511) isn't supported as it doesn't have any features to configure. OpenRazer's scope is to configure RGB and device-specific functionality.
  * #1058
