### ISSUE TITLE
Razer Ornata v3 not supported

### ISSUE THREAD

**Issue by stimpson1957** [openrazer/razer-drivers#1870]
I have a Razer Ornata V3 that is not listed as a supported device. When can we expect this device to be supported in addition to the V2 version of keyboard. Thanks for your assistance!

**Comment by lah7** [comment]
For a device to be supported, it needs to be documented by [creating a new issue](https://github.com/openrazer/openrazer/issues/new/choose) following the **"New Device Support"** template. Someone interested can pick this up to implement and the keyboard owner to test.

Note that Linux, packet captures and a temporary Windows installation is required.

Razer Ornata V2 (`1532:025D`) is already supported, but it's highly unlikely to be the same device ID as V3.
