### ISSUE TITLE
"daemon is not installed"

### ISSUE THREAD

**Issue by Douper2** [openrazer/razer-drivers#1873]
![Screenshot from 2022-08-05 19-23-12](https://user-images.githubusercontent.com/106928620/183120078-20acae85-7d72-4fb2-8fa2-4a7957093158.png)
also this is happening on manjaro
ive installed razergenie from the flathub

**Comment by lah7** [comment]
For Manjaro, have you installed `openrazer-meta` from the AUR?

**Comment by Douper2** [comment]
> For Manjaro, have you installed `openrazer-meta` from the AUR?

no, i did not

**Comment by z3ntu** [comment]
Please do so then, as mentioned in the error message in the screenshot you sent.

**Comment by Douper2** [comment]
> Please do so then, as mentioned in the error message in the screenshot you sent.

ok, i will try to do that

**Comment by Douper2** [comment]
> Please do so then, as mentioned in the error message in the screenshot you sent.

so i checked if i have it installed and i have it installed

**Comment by z3ntu** [comment]
Did you check our Troubleshooting page already? https://github.com/openrazer/openrazer/wiki/Troubleshooting

**Comment by Douper2** [comment]
> Did you check our Troubleshooting page already? https://github.com/openrazer/openrazer/wiki/Troubleshooting

hey, ive fixed the issue by using another windows pc. also thanks for all the things that you said.
