### ISSUE TITLE
Device not detected.

### ISSUE THREAD

**Issue by mlanca** [openrazer/razer-drivers#1893]
A 1532:0A24 is not detectable.  Tried poly & genie.  meta package installed.  using Manjaro.  Works fine under Win10(amd 4600g w.12g)

**Comment by lah7** [comment]
[What troubleshooting have you tried?](https://github.com/openrazer/openrazer/wiki/Troubleshooting) In Polychromatic, click **Troubleshoot** to find out which component is not installed properly.

**Comment by mlanca** [comment]
hi - I had a pretty massive stroke.  However, if you can spare the time. P
would love ro get this working.  Let me know how you would like to
proceed.  It works with Windows.  However, it doesn't see the keyboard in
Linux.

Sincerely,
Mike Lancaster

**Comment by z3ntu** [comment]
If you could try following what @lah7 wrote that would be helpful. Or check this wiki page https://github.com/openrazer/openrazer/wiki/Troubleshooting
