### ISSUE TITLE
Arch derivative fails to validate module

### ISSUE THREAD

**Issue by LividJava** [openrazer/razer-drivers#1898]
### Distribution
EndeavourOS  5.19.3-arch1-1

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Polychromatic reports that the Kernel modules are not installed.
![image](https://user-images.githubusercontent.com/7604544/187043681-fe2a380b-4ba6-4cf4-bfad-0e8bc2f7491e.png)

However I do have failed to validate module from dmesg
![image](https://user-images.githubusercontent.com/7604544/187043698-0d6003c3-687a-44aa-ad26-1e03dd97bb68.png)

Also polychromatic reports an old version of openrazer installed when yay reports the latest version is installed.

Uncertain if this is related to #1893 but it only started happening after a system update.

**Comment by lah7** [comment]
I found this [Arch bug report](https://bugs.archlinux.org/task/75685) showing a similar error affecting kernel 5.19.3. The solution there was to downgrade `pahole` and then cleanly reinstall the module (`openrazer-driver-dkms` in our case). Does that work?

**Comment by LividJava** [comment]
Downgrading `pahole` to `1:1.23-1` did work can confirm
