### ISSUE TITLE
kali install openrazer error

### ISSUE THREAD

**Issue by pro1tocol** [openrazer/razer-drivers#1906]
The following is the error message:

openrazer-daemon.service - Daemon to manage razer devices in userspace
     Loaded: loaded (/usr/lib/systemd/user/openrazer-daemon.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sat 2022-09-10 11:43:27 EDT; 25s ago
       Docs: man:openrazer-daemon(8)
    Process: 13495 ExecStart=/usr/bin/openrazer-daemon -F (code=exited, status=1/FAILURE)
   Main PID: 13495 (code=exited, status=1/FAILURE)
        CPU: 108ms

Sep 10 11:43:27 dot1q systemd[865]: Starting Daemon to manage razer devices in userspace...
Sep 10 11:43:27 dot1q openrazer-daemon[13495]: The daemon should not be run as root. If you have a good reason to do so, use the --as-root flag.
Sep 10 11:43:27 dot1q systemd[865]: openrazer-daemon.service: Main process exited, code=exited, status=1/FAILURE
Sep 10 11:43:27 dot1q systemd[865]: openrazer-daemon.service: Failed with result 'exit-code'.
Sep 10 11:43:27 dot1q systemd[865]: Failed to start Daemon to manage razer devices in userspace.

**Comment by z3ntu** [comment]
Having the user session as root is generally a bad idea, a separate user account should be used. If you're for whatever reason not willing to do that, edit the openrazer-daemon.service file and add `--as-root` flag as mentioned in the error message.
