### ISSUE TITLE
Ability to use OpenRazer for hardware functionality and disable RGB control completely

### ISSUE THREAD

**Issue by Rycia** [openrazer/razer-drivers#1908]
Hey!

I was wondering if there already is, or can be a way to have OpenRazer control just hardware functionality and not the RGB, because I want to use OpenRGB for non-razer devices outside of the support of OpenRazer over OpenRazer's RGB control.

I'm running the latest version of Arch.

**Comment by lah7** [comment]
I think (but haven't tested) that if you only install the OpenRazer driver, then you're good to go with using it with OpenRGB. If not, then the OpenRazer daemon might need installing too.

I believe the two can happily co-exist, simply don't use any of OpenRazer's frontends (and use sysfs or Python library directly), or use a frontend without touching any of it's RGB / effect options.

RGB control can't be "disabled", but if you turn off persistence and don't touch any "effects", OpenRazer won't mess with it.
