### ISSUE TITLE
Base Station V2 not seen/wrong PID

### ISSUE THREAD

**Issue by ghost** [openrazer/razer-drivers#1909]
Using Pop_OS & openrazer 3.4.0, tried stable and development.

Following the troubleshooting page, all logs commands don't show the device at all. Some strange behavior with this one. It's plugged in, and I can charge headsets with it, but nothing more. I've gotten it to work three times: twice from a mix of random plugging in/out my devices, rebooting, refreshing polychromatic and restarting the daemon; the third time was installing the driver in Arch and it suddenly working. These aren't reproducible. When it was working, upon suspending my PC, the LED seemed to turn on all colors at once and ceased functioning. When rebooting with it not plugged in and plugging it in after, my monitor starts randomly refreshing. The troubleshooting shown on polychromatic says "the following PIDs are not supported: 1532:0090. This is the PID for the Naga Pro, which is working. Not sure where to go from here.

**Comment by lah7** [comment]
If the device isn't showing in the kernel logs, it's likely some kind of a hardware issue. Maybe the USB bus isn't supplying enough power to the Base Station hub? Do you have the Base Station plugged in directly to the back of the computer?

The Linux kernel's USB power management can "disable" a USB bus until next boot if something was misbehaving. Like if you plug in the base station, ⚡  "too much load, shut it off!" → base station doesn't work until reboot. You might want to check `dmesg` generally for any USB related errors.

I have heard online of the original Base Station has been problematic with some BIOSes. I have the original one, and it hasn't been a bother for me (that said, I don't plug much into it). I can confirm that its RGB might stay on during sleep, or it lights up the RGB if a device is {un}plugged from the hub while still sleeping.

If it works in Arch but not Pop_OS, it could be the kernel version?
