### ISSUE TITLE
There aren't many supported devices.

### ISSUE THREAD

**Issue by wispophobia** [openrazer/razer-drivers#1911]
I have linux mint and I installed razor genie but none of my three razor devices are supported.
I have a Viper Mini, a Cynosa Chroma, and a Tartarus Pro. I understand why the first two aren't there but It's really disapointing that the Tartarus V2 is supported but not the Pro, there's no need for the annaloge controls to be there.

**Comment by z3ntu** [comment]
These two devices should already be supported, check `lsusb | grep 1532` output.

Razer Viper Mini | 1532:008A
-- | --

Razer Cynosa Chroma | 1532:022A
-- | --


Tartarus Pro is tracked by https://github.com/openrazer/openrazer/issues/1039
