### ISSUE TITLE
openrazer crashed

### ISSUE THREAD

**Issue by PlamenStilyianov** [openrazer/razer-drivers#1915]
try to start the daemon process

**Comment by z3ntu** [comment]
Can you give any further detail than this? Without an error message I cannot help you.

**Comment by PlamenStilyianov** [comment]
Looked at the GUI error it suggested to run the command for user, it sorted it outSent from PORSCHE DESIGN HUAWEI Mate 40-------- Original message --------From: Luca Weiss ***@***.***>Date: Mon, 26 Sep 2022, 21:09To: openrazer/openrazer ***@***.***>Cc: Plamen Stilyianov ***@***.***>, Author ***@***.***>Subject: Re: [openrazer/openrazer] openrazer crashed (Issue #1915)
Can you give any further detail than this? Without an error message I cannot help you.

**Comment by z3ntu** [comment]
Can we close this then?

**Comment by PlamenStilyianov** [comment]
Sure, you can
