### ISSUE TITLE
Can not launch Razer Genie and Razer Configuration

### ISSUE THREAD

**Issue by YouriyPaluch** [openrazer/razer-drivers#1924]
× openrazer-daemon.service - Daemon to manage razer devices in userspace
     Loaded: loaded (/usr/lib/systemd/user/openrazer-daemon.service; disabled; preset: disabled)
     Active: failed (Result: exit-code) since Tue 2022-10-11 08:23:12 EEST; 24s ago
       Docs: man:openrazer-daemon(8)
    Process: 14943 ExecStart=/usr/bin/openrazer-daemon -F (code=exited, status=1/FAILURE)
   Main PID: 14943 (code=exited, status=1/FAILURE)
        CPU: 90ms

жов 11 08:23:12 localhost.localdomain openrazer-daemon[14943]: 2022-10-11 08:23:12 | razer                          | CRITICAL | Please run the command 'sudo gpasswd -a $USER plugdev' and then reboot!
жов 11 08:23:12 localhost.localdomain openrazer-daemon[14943]: Stopping daemon.
жов 11 08:23:12 localhost.localdomain openrazer-daemon[14943]: Exception ignored in atexit callback: <bound method Daemonize.exit of <daemonize.Daemonize object at 0x7f086ebd74f0>>
жов 11 08:23:12 localhost.localdomain openrazer-daemon[14943]: Traceback (most recent call last):
жов 11 08:23:12 localhost.localdomain openrazer-daemon[14943]:   File "/usr/lib/python3.10/site-packages/daemonize.py", line 72, in exit
жов 11 08:23:12 localhost.localdomain openrazer-daemon[14943]:     sys.exit(0)
жов 11 08:23:12 localhost.localdomain openrazer-daemon[14943]: SystemExit: 0
жов 11 08:23:12 localhost.localdomain systemd[1264]: openrazer-daemon.service: Main process exited, code=exited, status=1/FAILURE
жов 11 08:23:12 localhost.localdomain systemd[1264]: openrazer-daemon.service: Failed with result 'exit-code'.
жов 11 08:23:12 localhost.localdomain systemd[1264]: Failed to start Daemon to manage razer devices in userspace.

**Comment by z3ntu** [comment]
Please read the log line marked "critical" and follow it.
