### ISSUE TITLE
My devices are unrecognized by openrazer

### ISSUE THREAD

**Issue by MartinYang1** [openrazer/razer-drivers#1933]
### Support

- [x] Have you tried rebooting? Yes
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page? Yes

Hi, I have a razer viper mouse and a razer huntsman tenkeyless TE keyboard and they are unrecognized by openrazer even though on the website, it says they are supported. The device numbers are 1532:026B and 1532:0078.

**Comment by z3ntu** [comment]
0078 should be supported, the other device is tracked in #1681

Can you provide output of `sudo modprobe razerkbd` and `systemctl --user status openrazer-daemon.service` ?

**Comment by MartinYang1** [comment]
yes, now 0078, my razer viper, is recognized. however the keyboard is unrecognized. Could it be because my openrazer version is 3.2.0? My openrazer-meta is already the newest version, but the openrazer-src newest version is 3.4.0
![Screenshot from 2022-10-21 19-38-06](https://user-images.githubusercontent.com/93455117/197305715-e3425492-0657-4b41-8954-ed5b7ccaa102.png)

**Comment by MartinYang1** [comment]
i looked at openrazer's website and readme.md and they don't seem to support razer huntsman v2 tenkeyless. they support huntsman te or huntsman v2 analog, but not this

**Comment by z3ntu** [comment]
As mentioned, the 026B device is not yet supported. You can subscribe to issue #1681 to get notified when it will be.

As the other device is detected fine (so no setup issue or anything), I'll close this issue.
