### ISSUE TITLE
Can anyone help with this error ?

### ISSUE THREAD

**Issue by Robbie99999** [openrazer/razer-drivers#1936]
:: Installing OpenRazer python library
=====================================================
python3 setup.py install --prefix=/usr --root=/home/deck/.cache/yay/openrazer-git/pkg/python-openrazer-git
Traceback (most recent call last):
  File "/home/deck/.cache/yay/openrazer-git/src/openrazer/pylib/setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'
make[1]: *** [Makefile:9: install] Error 1
make: *** [Makefile:91: python_library_install] Error 2
==> ERROR: A failure occurred in package_python-openrazer-git().
    Aborting...
error making: openrazer-git (openrazer-driver-dkms-git openrazer-daemon-git)

**Comment by z3ntu** [comment]
You're missing the `python-setuptools` package which is a makedepends of `openrazer` and `openrazer-git` AUR package, so makepkg should install that when needed. Or your Python setup is just messed up, then I cannot help much.
