### ISSUE TITLE
Polychromatic does not detect my devices

### ISSUE THREAD

**Issue by marcoszy** [openrazer/razer-drivers#1937]
### Distribution

Kubuntu 22.04

### Support

- [ x ] Have you tried rebooting?
- [ X ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Hey there!

I was trying to figure out what is happening here, and I've opened an issue here: https://github.com/openrazer/openrazer/issues/1927#issuecomment-1279715910

But, today the problem became worse. :(

Trying to fix the issue I've uninstalled both Polychromatic and OpenRazer. After that I installed both.

But now Polychromatic is not detecting my Razer devices (unrecognized device). Both the keyboard and mouse are listed with the lsusb command, moreover.

The command `sudo dkms install openrazer-driver/3.4.0` returns the below error:

"headers for kernel 5.17.0-1020-oem cannot be found."

But I really don't know if this is the problem and/or if I am missing something.

Any help would be greatly appreciated! :)

**Comment by z3ntu** [comment]
I guess you're missing the package `linux-headers-5.17.0-1020-oem` , not sure if there's some meta package you can install that makes this installable (and for future versions also).

**Comment by marcoszy** [comment]
Hum, I will check that. Thanks.

**Comment by kyle-belle** [comment]
My device also is no longer recognized (razer blade 15 2019) running Zorin OS 16.2 [Linux 5.18.15-051815-generic x86_64]

**Comment by kyle-belle** [comment]
> My device also is no longer recognized (razer blade 15 2019) running Zorin OS 16.2 [Linux 5.18.15-051815-generic x86_64]

After some updates (following the updates which probably broke things) + a restart it now seems to be working again
