### ISSUE TITLE
support for razer blade 15 

### ISSUE THREAD

**Issue by nkurata** [openrazer/razer-drivers#1938]
### Support

- [ ] Have you tried rebooting?
- [ ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

hello, i just have a question that i cant seem to find the answer too anywear, does open razer have the performance mode and creator mode switcher ?

**Comment by z3ntu** [comment]
Can you give more details on what this should be?
