### ISSUE TITLE
Steam Deck 

### ISSUE THREAD

**Issue by The-Hoff** [openrazer/razer-drivers#1944]
### Support

- [ ] Have you tried rebooting?
- [ ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I am new to Linux, and I don't know how to install openrazer on Steam Deck. Any step-by-step instructions for a complete beginner would be much appreciated. Thank you.

**Comment by z3ntu** [comment]
Does this help? https://github.com/openrazer/openrazer/issues/1815#issuecomment-1129144041
