### ISSUE TITLE
plugdev group doesn't exist

### ISSUE THREAD

**Issue by TheTrashCrafter** [openrazer/razer-drivers#1948]
### Distribution

Fedora Workstation 36

### Support

- [Yes] Have you tried rebooting?
- [Yes] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Hi,
I'm currently trying to install OpenRazer on Fedora, but even the first step doesn't work: If i try to run this command:
`sudo gpasswd -a $USER plugdev`
It tells me, that there is no plugdev group in /etc/group.

Regards,
Kevin

**Comment by z3ntu** [comment]
Weird, the install script from the package you installed should've created it for you: https://github.com/openrazer/OBS-packaging/blob/master/openrazer.spec#L129-L133

Can you try running the `sudo groupadd -r plugdev` manually?

**Comment by TheTrashCrafter** [comment]
That resulted in crashing, but i reinstalled Fedora and now it works, thanks for your help.

Regards,
Kevin
