### ISSUE TITLE
Fedora 37 released - please update the repo

### ISSUE THREAD

**Issue by Provisional9448** [openrazer/razer-drivers#1951]
### Distribution
Fedora 37

### Support

- [ X ] Have you tried rebooting?
- [ X ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

[Fedora 37](https://fedoramagazine.org/announcing-fedora-37/) was just released. Please update the repo so I can continue using OpenRazer. Thanks!

**Comment by z3ntu** [comment]
All packages should be built an published now for Fedora 37. Please try :)
