### ISSUE TITLE
Huntsman v2 not recognized

### ISSUE THREAD

**Issue by Albusoline** [openrazer/razer-drivers#1956]
### Distribution

Linux Mint 21

### Support

- [x ] Have you tried rebooting? Yes. 
- [x ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Keyboard is still unrecognized. Any ideas?
![grafik](https://user-images.githubusercontent.com/96739565/202863245-65dc90f4-21b1-4448-853c-2fcaf003d439.png)

**Comment by z3ntu** [comment]
Huntsman V2 is only supported since v3.3.0, so it won't work with v3.2.0 that you have installed. Check our website for installation instructions.

**Comment by Albusoline** [comment]
Hi.
Thanks for the tip, I just updated to 3.4.0... still not working.
![grafik](https://user-images.githubusercontent.com/96739565/202863574-90cfca22-b7fb-422d-a6e8-711eae3d3997.png)

**Comment by z3ntu** [comment]
Have you rebooted after updating? Also please provide `lsusb | grep 1532` output

**Comment by Albusoline** [comment]
Rebooted LinuxMint.
Opened Polychromatic again. Device is now showing up as "Razer Huntsman V2", however I get a "Backend Error". When "showing details" I get this text:

_Traceback (most recent call last):
  File ’/usr/lib/python3/dist-packages/polychromatic/middleman.py’, line 165, in get_device
    device = module.get_device(uid)
  File ’/usr/lib/python3/dist-packages/polychromatic/backends/openrazer.py’, line 607, in get_device
    ’id’: ids[rate],
KeyError: 250_

Output of `lsusb | grep 1532`:
_Bus 001 Device 007: ID 1532:026c Razer USA, Ltd Razer Huntsman V2_

**Comment by z3ntu** [comment]
For that, see https://github.com/polychromatic/polychromatic/issues/430 . At least the OpenRazer side seems to be working correctly now.

**Comment by Albusoline** [comment]
Thank you z3ntu.
You've been a great help!
It's working now!
