### ISSUE TITLE
Unable to find Basilisk Ultimate Wired

### ISSUE THREAD

**Issue by jassib** [openrazer/razer-drivers#1967]
### Distribution

Ubuntu 5.15.0-53-generic

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Hi, I am using the Basilisk Ultimate in Wireless mode successfully on my Ubuntu machine. However, I am unable to use it in Wired mode. In the following output, I don't see the `0086` for Wired.
```
$ lsusb | grep Razer
Bus 003 Device 016: ID 1532:0088 Razer USA, Ltd 
Bus 003 Device 012: ID 1532:0209 Razer USA, Ltd BlackWidow Tournament Edition Chroma
$ lsusb | grep '1532:'
Bus 003 Device 016: ID 1532:0088 Razer USA, Ltd 
Bus 003 Device 012: ID 1532:0209 Razer USA, Ltd BlackWidow Tournament Edition Chroma
```
I also don't see any output on `dmesg | grep razer` when I unplug and plug my wired cable, but I do when I unplug and plug my wireless receiver.

**Comment by z3ntu** [comment]
If it doesn't show up in lsusb (or kernel log) then OpenRazer won't be able to do anything with it. 

Or were you able to resolve this issue in the meantime?
