### ISSUE TITLE
openrazer-daemon.service error

### ISSUE THREAD

**Issue by Dissonanc3** [openrazer/razer-drivers#1968]
× openrazer-daemon.service - Daemon to manage razer devices in userspace
     Loaded: loaded (/etc/systemd/user/openrazer-daemon.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2022-11-30 11:53:56 CET; 23s ago
       Docs: man:openrazer-daemon(8)
    Process: 15438 ExecStart=/nix/store/w52syhqx13vx3krxcwnhdx4lh4riba06-openrazer_daemon-3.1.0/bin/openrazer-daemon --config /nix/store/hkyz2hga0n5n3ppnal9v97q0ih2hvzaz-razer.conf --foreground (code=exited, status=1/FAILURE)
   Main PID: 15438 (code=exited, status=1/FAILURE)
        CPU: 91ms

11月 30 11:53:56 nixos systemd[1302]: openrazer-daemon.service: Scheduled restart job, restart counter is at 5.
11月 30 11:53:56 nixos systemd[1302]: Stopped Daemon to manage razer devices in userspace.
11月 30 11:53:56 nixos systemd[1302]: openrazer-daemon.service: Start request repeated too quickly.
11月 30 11:53:56 nixos systemd[1302]: openrazer-daemon.service: Failed with result 'exit-code'.
11月 30 11:53:56 nixos systemd[1302]: Failed to start Daemon to manage razer devices in userspace.

**Comment by z3ntu** [comment]
Check `journalctl -eu openrazer-daemon.service` if there's any error

**Comment by Dissonanc3** [comment]
I get no entries

**Comment by z3ntu** [comment]
I don't know much about NixOS but try running `/nix/store/w52syhqx13vx3krxcwnhdx4lh4riba06-openrazer_daemon-3.1.0/bin/openrazer-daemon --config /nix/store/hkyz2hga0n5n3ppnal9v97q0ih2hvzaz-razer.conf --foreground` and see if that throws an error.

**Comment by Dissonanc3** [comment]
2022-11-30 12:04:41 | razer                          | INFO     | Initialising Daemon (v3.1.0). Pid: 16960
2022-11-30 12:04:41 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2022-11-30 12:04:41 | razer                          | INFO     | Found device.0: 0003:1532:0078.0001
2022-11-30 12:04:41 | razer.device0                  | INFO     | Initialising device.0 RazerViper
2022-11-30 12:04:41 | razer                          | INFO     | Serving DBus

**Comment by Dissonanc3** [comment]
oh it works now

**Comment by Dissonanc3** [comment]
thank you very much for help

**Comment by z3ntu** [comment]
If the systemd service doesn't work, then I believe it's a bug in the NixOS packaging so please ask there for help.
