### ISSUE TITLE
MicroOS version?

### ISSUE THREAD

**Issue by Konglomneshued** [openrazer/razer-drivers#1971]
I'm using OpenSUSE MicroOS and trying to install, but there are only repos for Leap and Tumbleweed.

**Comment by z3ntu** [comment]
Unfortunately I cannot find any documentation how to get MicroOS builds into build.opensuse.org. Does MicroOS support the traditional rpm packages?

**Comment by ThomChroma** [comment]
MicroOS is based on Tumbleweed but uses [transactional updates](https://en.opensuse.org/Portal:MicroOS/Desktop) (it's an immutable OS). So you don't need a new package, you have to learn how to install the Tumbleweed one on MicroOS, which I don't know.

But like the page says, maybe MicroOS is not for you if you start doing things like that.

**Comment by Konglomneshued** [comment]
Just wanted to update saying that I simply used the Tumbleweed repo, because MicroOS is based on it as @ThomChroma mentioned, and it worked fine for me.

Would you like me to close the issue?

**Comment by z3ntu** [comment]
Sounds good. If there's more demand on this in the future, we can maybe include some more details on the website so it's easier for people to find.
