### ISSUE TITLE
Is this message on boot splash screen an actual error?           No inputs registered, leaving

### ISSUE THREAD

**Issue by Karnor** [openrazer/razer-drivers#1973]
### Distribution

Kubuntu 22.04

### Support

- [x] Have you tried rebooting? Yes I have rebooted a couple of times
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I'm not even sure this is an error.

I get this message on the boot pre KDE splash screen, but the keyboard is working so I guess I'm just confused what this means

razerkbd 0003:1532:024E.0004: No inputs registered, leaving

**Comment by z3ntu** [comment]
Sounds harmless, I think the kernel is just a bit too loudly complaining about the somewhat weird USB setup Razer devices have.
