### ISSUE TITLE
Razer Cynosia Chroma and Lancehead not noticed by RazerGenie

### ISSUE THREAD

**Issue by schreibling** [openrazer/razer-drivers#1975]
hello,

it says that there are no devices found by the deamon. 

- keyboard is Razer Cynosia Chroma
-Mice is Razer Lancehead TournamentEdition

can anyone help pls?
![razergenie](https://user-images.githubusercontent.com/119764085/205981583-d8fbdef5-acd1-4191-8b18-8ee9c16bc4ec.jpg)

**Comment by z3ntu** [comment]
Please check our Troubleshooting page: https://github.com/openrazer/openrazer/wiki/Troubleshooting

**Comment by schreibling** [comment]
ok, ty.

both devices are findeable via lsusb | grep Razer, see image below. 
both are on the list of stable supported devices.

dkms status shows me 2 lines. does that mean its installed twice? if so, how can i fix that pls?
![dkms](https://user-images.githubusercontent.com/119764085/205984811-4da5d842-2c6c-482b-8ca0-7be52909173d.jpg)
![dkmsstatus](https://user-images.githubusercontent.com/119764085/205984814-8d5e8a70-3922-486e-8be7-67dd5c88fb18.jpg)
![lsusb](https://user-images.githubusercontent.com/119764085/205984819-12dacec5-f3e6-457a-9342-689810eeb4f3.jpg)

**Comment by lah7** [comment]
It just means that the driver has been installed for two kernels on your system.

Which kernel are you running right now? It should be `5.15.0-56-generic` :

    uname -a

Just to note, your OpenRazer version is a bit behind. `3.5.1` is the latest. You might want to re-add the repository so it stays up-to-date.
