### ISSUE TITLE
request for device 1532:027A

### ISSUE THREAD

**Issue by WantClue** [openrazer/razer-drivers#1979]
### Support request for adding new device

- [ x] Have you tried rebooting?
- [ x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Will we get support for the 1532:027A keyboard?

I use a razer blade 15 2022 base model and this keyboard seems to be not supported and is not recognised by openrazer.
Would love to see suppor for this aswell

**Comment by z3ntu** [comment]
Duplicate of #1581
