### ISSUE TITLE
DeathStalker V2 volume wheel acts like a mouse wheel

### ISSUE THREAD

**Issue by simplyroman** [openrazer/razer-drivers#1980]
### Distribution

Manjaro 21 KDE Plasma

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

The volume wheel acts like a mouse wheel with openrazer-driver_3.5.1.

A possible solution could be here https://github.com/openrazer/openrazer/commit/5845e9d6fc14225ee3a9f0cfe33bec734ca3caa6

I don't have the programming skills to test it by myself. I hope someone has the possibility.

**Comment by simplyroman** [comment]
@AZeroEight Thanks for bringing the support for the keyboard. Are you facing the same problem with the keyboard?

**Comment by AZeroEight** [comment]
Sometimes, it works correctly and sometimes like a mouse wheel. I have not been able to pinpoint the cause yet.

**Comment by simplyroman** [comment]
Do you mind giving the possible fix a chance?

**Comment by AZeroEight** [comment]
> Do you mind giving the possible fix a chance?

I will. But it won't be before monday.

**Comment by AZeroEight** [comment]
Hi @simplyroman,

I have not yet found a way to reproduce the issue. In my current setup the volume wheel acts correctly (openrazer 3.5.1, Kernel 5.15.80) and I did not manage to make it misbehave. If you find a way, please let me know but I cannot implement a fix for an issue I don't have.

But in parallel I create a VM with Manjaro 21 KDE right now and will compile the module for you - if you don't mind replacing it in your modules folder and test if it does a difference? I could also provide you the steps to compile it yourself if you would like to give it a spin.

**Comment by simplyroman** [comment]
@AZeroEight I would appreciate it. Changing the modules sounds not too difficult.

**Comment by simplyroman** [comment]
@AZeroEight I found a way to remap the keys. A fix is no more needed for me. I used [input-remapper](https://github.com/sezanzeb/input-remapper). I keep the issue open so someone who googled a solution can see this.

**Comment by AZeroEight** [comment]
Hi @simplyroman,

using input-remapper is just a workaround in my opinion. I would have the module ready - I presume you are using Kernel 5.15.81-1-MANJARO?

[razerkbd.ko.gz](https://github.com/openrazer/openrazer/files/10237292/razerkbd.ko.gz)

You need to unload the existing module:
```shell
rmmod razerkbd
```

And load the new one:
```shell
insmod ./razerkbd.ko
```

let me know if this solves the issue for you and I will create a pull request, so hopefully with the next revision this is part of history.

**Comment by simplyroman** [comment]
@AZeroEight When I want to load the new module (sudo insmod ./razerkbd.ko) this happens:
`insmod: ERROR: could not insert module ./razerkbd.ko: Invalid module format`

I'm using Kernel 6.0.11-1-MANJARO

**Comment by AZeroEight** [comment]
@simplyroman please find the module for kernel 6.0.11-1-MANJARO attached.

[razerkbd.ko.gz](https://github.com/openrazer/openrazer/files/10243781/razerkbd.ko.gz)

**Comment by simplyroman** [comment]
Hi @AZeroEight, I've tested it and can confirm that it fixes the issue. Thank you very much.

**Comment by AZeroEight** [comment]
I've created the pull request so hopefully the fix will be in the next release.
