### ISSUE TITLE
Fedora 37 / Open Suse Repo Down ???

### ISSUE THREAD

**Issue by craigccfl** [openrazer/razer-drivers#1985]
Doing a system update, using the https://download.opensuse.org/repositories/hardware:razer/Fedora_37/hardware:razer.repo Seems the repo is no longer available. Ended up excluding openrazer-kernel-modules-dkms in my conf file to update system. Don't know if this is a temp issue, over site or no longer supported. Date and time trying to access Dec 20th 00:10 hrs

Thanks to all the Devs working on this project.

**Comment by z3ntu** [comment]
Weird, it seems to work fine here.
```
$ curl -L https://download.opensuse.org/repositories/hardware:razer/Fedora_37/hardware:razer.repo
[hardware_razer]
name=hardware:razer (Fedora_37)
type=rpm-md
baseurl=https://download.opensuse.org/repositories/hardware:/razer/Fedora_37/
gpgcheck=1
gpgkey=https://download.opensuse.org/repositories/hardware:/razer/Fedora_37/repodata/repomd.xml.key
enabled=1
```

Perhaps it was a temporary problem in the opensuse infra?

**Comment by craigccfl** [comment]
Tried it again after reviewing z3ntu comment. It's working now. Probably should have waited a day before posting the question. Again, thanks Devs, love this project, supporting my Razor peripherals.
