### ISSUE TITLE
Support for Razer BlackWidow V3 Mini (wireless 2.4)

### ISSUE THREAD

**Issue by fiercebrake** [openrazer/razer-drivers#1987]
### Device Info

* Name: Razer BlackWidow V3 Mini
* Product Number: rz03-03890900
* Model Number: rz03-0389

### Device Information
```
Please post the output of
    lsusb -d 1532: -v
```
[lsusb.txt](https://github.com/openrazer/openrazer/files/10268923/lsusb.txt)
```
Please post the output of
    ls -lah /dev/input/by-id/
```
[ls.txt](https://github.com/openrazer/openrazer/files/10268926/ls.txt)

<details>

```
Please post the output of
    usbhid-dump -m 1532 -ed
```
[usbhid-dump.txt](https://github.com/openrazer/openrazer/files/10268927/usbhid-dump.txt)

</details>

**Comment by z3ntu** [comment]
The device `1532:0271` is already supported. If you have OpenRazer installed and it doesn't work for you please check the Troubleshooting page: https://github.com/openrazer/openrazer/wiki/Troubleshooting
