### ISSUE TITLE
Support for Razer Wolverine V2 Pro 

### ISSUE THREAD

**Issue by pipedream420** [openrazer/razer-drivers#1994]
### **Device**

- [Razer Wolverine V2 Pro](https://www.razer.com/console-controllers/razer-wolverine-v2-pro)

### **Distribution**

- Arch Linux

### **Support**

- Tried rebooting

- Looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page

### **Issue**

The device is recognized and works out of the box, however, the touchpad is not recognized nor the touchpad buttons. I'd also like to be able to configure the touch pad buttons if possible. Something similar to [DS4Windows](https://github.com/Ryochan7/DS4Windows) would be preferable. Controller does not have Gyro or Rumble functionality FYI.

**Comment by z3ntu** [comment]
Support for functionality like this is very likely out-of-scope for OpenRazer.

However you can check e.g. evtest if any input events are emitted from the kernel when you do anything with the touchpad. If there is something you can probably remap them with https://github.com/sezanzeb/input-remapper
