### ISSUE TITLE
RazerGenie "OpenRazer Daemon" is not installed.

### ISSUE THREAD

**Issue by ArvalCode** [openrazer/razer-drivers#1996]
### Distribution

OpenGenie-git, 1.0.0
### Support

- [ ] Have you tried rebooting?
Yes I have tried rebooted
- [ ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?
Yes I have tried looking.

Even though I have daemon installed, it tells me that it isn't. Polychromatic is working too.
Heres an image.
![image](https://user-images.githubusercontent.com/72712954/210177886-30a95832-d8c5-41a1-ab01-2271874df111.png)

**Comment by z3ntu** [comment]
Please post the output of `systemctl --user status openrazer-daemon.service`
