### ISSUE TITLE
Razer naga x

### ISSUE THREAD

**Issue by Yiggy-Fester** [openrazer/razer-drivers#1999]
On razer naga x, there's nothing under lighting just scroll options and when I click on custom editor it says "Please open an issue in the RazerGenie repository. Device type: mouse"

Device is supported by openrazer, it is 1532:0096

**Comment by z3ntu** [comment]
1. It says RazerGenie repository which is https://github.com/z3ntu/RazerGenie and not this one here.
2. This has been solved with the latest RazerGenie version v1.0.0 so please update.
