### ISSUE TITLE
Where are the GPG keys?

### ISSUE THREAD

**Issue by Konglomneshued** [openrazer/razer-drivers#2000]
### Distribution
OpenSUSE Tumbleweed

### Support

- [ x] Have you tried rebooting?
- [ x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I added the repo but unable to verify keys as I can't find them on the site or Github.

**Comment by z3ntu** [comment]
The key for Tumbleweed can be found here I think: https://download.opensuse.org/repositories/hardware:/razer/openSUSE_Tumbleweed/repodata/repomd.xml.key

What do you need it for?

**Comment by Konglomneshued** [comment]
> The key for Tumbleweed can be found here I think: https://download.opensuse.org/repositories/hardware:/razer/openSUSE_Tumbleweed/repodata/repomd.xml.key
> 
> What do you need it for?

To verify my download.

**Comment by z3ntu** [comment]
Is your question answered then?

**Comment by Konglomneshued** [comment]
Yes, thank you.
