### ISSUE TITLE
Unable to load module in-spite of secure boot being disabled.

### ISSUE THREAD

**Issue by Vixea** [openrazer/razer-drivers#2007]
### Distribution
EndeavourOS

Latest Aur

### Support

- [ *] Have you tried rebooting?
- [* ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I'm unable to load module in-spite of not having secure boot enabled.
(Fails with modprobe: ERROR: could not insert 'razerkbd': Operation not permitted)

https://i.imgur.com/oEuWh69.png

**Comment by z3ntu** [comment]
Apart from not running `modprobe` as root, I'm not aware of anything that could produce "Operation not permitted" that's not from secure boot.

**Comment by Vixea** [comment]
I've copy and pasted the command so I don't think that's the issue.

**Comment by lah7** [comment]
Is there anything in the kernel log?

    sudo dmesg | grep razer

Is your system a laptop?  Apparently, some BIOSes with an Intel CPU might need "Intel Platform Trust Technology" disabling too, [according to this answer.](https://stackoverflow.com/a/63449219)

**Comment by Vixea** [comment]
No, and i don't have an Intel system but an AMD one

**Comment by z3ntu** [comment]
@Vixea Have you been able to figure out anything in the last three weeks why it doesn't work? As written before apart from secure boot or not running modprobe as root I don't know of any way it could fail like that.

**Comment by Vixea** [comment]
Nope

**Comment by Vixea** [comment]
Now I'm getting this 
==> ERROR: Missing 6.1.11-arch1-1 kernel modules tree for module openrazer-driver/3.5.1.

**Comment by z3ntu** [comment]
Then you need to install the kernel headers for the kernel you're running. Check that you have `linux-headers` version `6.1.11.arch1-1` installed.

**Comment by Vixea** [comment]
I'm running zen, so I think I can just remove linux-headers

**Comment by Vixea** [comment]
remind me of the command for modprobe

**Comment by Vixea** [comment]
would kernel lockdown make it impossible?

**Comment by Vixea** [comment]
zswap.enabled=0 lockdown=integrity threadirqs amdgpu.mcbp=1 amdgpu.ppfeaturemask=0xffffffff

**Comment by z3ntu** [comment]
Yes, kernel lockdown is explicitly designed to prevent loading unauthorized kernel modules. That is causing your issues.
