### ISSUE TITLE
Add support for Raiju Mobile

### ISSUE THREAD

**Issue by aanze** [openrazer/razer-drivers#2013]
Raiju Mobile controler, even though detected by Linux (tested on SteamOS) does not function when connected in Bluetooth.

**Comment by z3ntu** [comment]
If the device doesn't work as a gamepad(?) out of the box, then I doubt it's something that OpenRazer support would fix since it mostly handles RGB and other extra bits like that.
Do you have a regulator Linux box to test this on or just the Steam Deck?
