### ISSUE TITLE
1532:0f1f Razer USA, Ltd Razer Chroma Addressable RGB Controller goes dark

### ISSUE THREAD

**Issue by milessi** [openrazer/razer-drivers#2015]
### Distribution
OS: Ubuntu Lunar Lobster (development branch) x86_64 
Kernel: 6.1.8-060108-generic 

### Support

- [ y] Have you tried rebooting?
- [ y] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Openrazer finally is recognizing the RGB controller properly but... as soon as computer boots on a login screen and it is loading the drivers, it is throwing all the leds which are connected the controller to darkness. I cannot figure out why I cannot get the lights back anymore. As soon as I reboot the computer leds are coming back to life but again... loading driver -> darkness and no control.
Did try also with ubuntu 22.10 and older 5.19 kernel with no success.

This is from syslog:
usb 1-8: new full-speed USB device number 6 using xhci_hcd
usb 1-8: New USB device found, idVendor=1532, idProduct=0f1f, bcdDevice= 2.00
usb 1-8: New USB device strings: Mfr=1, Product=2, SerialNumber=0
usb 1-8: Product: Razer Chroma Addressable RGB Controller
usb 1-8: Manufacturer: Razer
hid-generic 0003:1532:0F1F.0008: hidraw7: USB HID v1.11 Device [Razer Razer Chroma Addressable RGB Controller] on usb-0000:00:14.0-8/input0
hid-generic 0003:1532:0F1F.0009: hidraw8: USB HID v1.11 Device [Razer Razer Chroma Addressable RGB Controller] on usb-0000:00:14.0-8/input1
hid-generic 0003:1532:0F1F.000A: hidraw9: USB HID v1.11 Device [Razer Razer Chroma Addressable RGB Controller] on usb-0000:00:14.0-8/input2

### Product
1532:0f1f Razer USA, Ltd Razer Chroma Addressable RGB Controller

Not really sure what to try next..
Any help would be appreciated! 

Br,
milessi

**Comment by z3ntu** [comment]
Just to be clear, after bootup you cannot use e.g. polychromatic to adjust the LED lighting? How did you configure the lights in the first place?
