### ISSUE TITLE
Razer Lancehead Tournament Edition not recognized

### ISSUE THREAD

**Issue by VirtualLusamine** [openrazer/razer-drivers#2017]
### Distribution Manjaro Linux
Openrazer on polychromatic

### Support

- [x] Have you tried rebooting?
I tried rebooting multiple times and it didnt work ever.
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?
i tried truble shooting and did all the steps twice or three times and have went through some other support requests.

Im using polychromatic and i have my razer keyboard connected and it works normally, my headset doesnt work but thats for lack of support and it says clearly on the trubleshooting. Although my Lancehead Tournament Edition seems to not apear in the openrazer app trubleshooting as not working but it still says its a unrecognised device. So i really dont know what to do.

![trubleshooting](https://user-images.githubusercontent.com/82206533/217332693-f4ccfc8b-f803-431f-b9b4-950d3b6928e1.png)
![trubleshooting2](https://user-images.githubusercontent.com/82206533/217332827-6ca0c925-3d94-42a7-81b4-5184de347e8f.png)

**Comment by VirtualLusamine** [comment]
the update seemed to fix it somehow
really wiered but im just glad it works now

**Comment by VirtualLusamine** [comment]
it seems to have come back with rebooting my computer

**Comment by lah7** [comment]
`1532:0528` isn't supported by OpenRazer yet, but there is an open issue for it. Please watch #1280 for updates. Apparently this device doesn't have RGB, so it might be limited if it is supported, as OpenRazer doesn't deal with audio-specific features.

Regarding Lancehead TE,  do you mean the problem has come back? Does restarting OpenRazer from that button help?
