### ISSUE TITLE
Ghosted keys on BlackWidow Elite when holding down button on Naga Trinity

### ISSUE THREAD

**Issue by indie2718** [openrazer/razer-drivers#2026]
### Distribution
Ubuntu 20.04
OpenRazer 3.5.1

### Support
I've tried going through the troubleshooting steps at the wiki page to no avail, as have I tried rebooting a few times to get changes to take.

I'm not sure what info to provide to show that this is happening, or why it's happening, but when I hold down a mouse button on my Naga Trinity (1532:0067), about 40% of my inputs get ghosted by my BlackWidow Elite (1532:0228). It looks like support has been added for both devices, so I'm not sure what's going on. I'm happy to provide whatever's needed to diagnose.
Thanks!!

**Comment by z3ntu** [comment]
Can you try uninstalling OpenRazer and see if the same issue persists?

**Comment by indie2718** [comment]
no dice. the problem persists regardless.

**Comment by z3ntu** [comment]
Yeah then it very much sounds like a hardware or firmware issue. Nothing we can fix, sorry.
