### ISSUE TITLE
Wiki: Recommended VM for USB reverse engineering not available anymore.

### ISSUE THREAD

**Issue by ghost** [openrazer/razer-drivers#2028]
I wanted to record pcaps for a device support issue, but the Windows 10 VM image that was recommended in [the guide in the wiki](https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol) is not available anymore.
It was removed several weeks ago, and there was a page mentioning that it won't be available anymore, instead.

Updating the wiki page with a link to another VM image would make recording pcaps (somewhat) easy to do (again).

**Comment by z3ntu** [comment]
Do you have any suggestion what other VM image to use? I found https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/ which should be good enough I guess? Even though it's Windows 11 and not 10 it should be fine I gues

**Comment by ghost** [comment]
I tried it on a "Debian GNU/Linux 11 Bullseye"-Host with VirtualBox 7 from Debian Fasttrack.

After downloading the 20GB large VM-image, and importing it into VirtualBox, it basically worked; though it crashed once during initial setup, and there were some graphical glitches.
The "Razer Synapse 3"-installer, und the installed app both had graphical glitches (mostly on text) which disappeared temporarily after that part of the app changed (by resizing the window, for example), but other than that it worked.

Definitely not ideal, but better than nothing, i guess.

Thanks for finding it. :)

**Comment by z3ntu** [comment]
Fixed: https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol/_compare/40701f1675038f64308904925be2a80338239ce1...1b58ee53589e3541f18fcd9f4a8e57efc6fc9b25
