### ISSUE TITLE
Could you please add function of mouse macro?

### ISSUE THREAD

**Issue by sajia23** [openrazer/razer-drivers#2034]
### Support

- [ ] Have you tried rebooting?
- [ ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

**Comment by meeuw** [comment]
Have you tried configuring mouse macros on a Windows machine using Synapse for your mouse? 

I know at least some devices are able to execute macros from hardware.

If you'd like to be able to configure/change macros from Linux I'd recommend to add that to this issue description.

**Comment by JurgenCruz** [comment]
I don't know about OP, but I would like being able to configure/change macros from Linux for my Razer Viper mouse. I don't think my mouse has hardware support for macros, plus I don't have a Windows machine to do it.

Thanks.
