### ISSUE TITLE
Blackwidow v3 Custom Color Assignment for Logo

### ISSUE THREAD

**Issue by mitchrich** [openrazer/razer-drivers#2040]
I have tried multiple GUIs with Blackwidow v3 and for all of them, assigning a custom color to the logo doesn't work unless it is applied to the ALT key. This means that the alt key has no way of being assigned. I do not know if this is a problem relating to the GUIs but I have tried Snake, razerCommander, and RazerGenie with the same issue across all of them.

**Comment by lah7** [comment]
According to https://github.com/openrazer/openrazer/issues/1319#issuecomment-1242222448, it's an issue that each GUI needs to address. The BlackWidow V3 shares the same dimensions as the older models, but the physical mappings are a bit different.

Looks like there is an issue open for RazerGenie: https://github.com/z3ntu/RazerGenie/issues/149

There is also Polychromatic which you could try.
