### ISSUE TITLE
Huntsman v2 TKL - Effects Don't Change In Polychromatic

### ISSUE THREAD

**Issue by 0pLuS0** [openrazer/razer-drivers#2070]
### Distribution

Ubuntu 23.04
openrazer 3.6.0
polychromatic 0.8.1

Huntsman v2 TKL 1532:026b

### Support

- [ x] Have you tried rebooting?
- [ x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

None of the effects work, except Static for the Huntsman v2 TKL, rebooting doesn't do anything. Static is the only one that has ever worked.

The only thing I can find in the logs, when I look for any errors is this;

```razerkbd: module verification failed: signature and/or required key missing - tainting kernel```

What is this sig or key missing, is this something I can fix on my end?

Here's the log file attached.

[razer.log](https://github.com/openrazer/openrazer/files/11468173/razer.log)

**Comment by z3ntu** [comment]
@saibotk @rbelando @lwndow I'm guessing on your Huntsman setting the effects work correctly? If so it's possible that the devices are running a different firmware version.

@0pLuS0 Could you share the firmware version of your device please?

**Comment by 0pLuS0** [comment]
I just logged onto Ubuntu today, after a few days away, strange thing, there was an openrazer update, now everything works... LOL 

I can't remember, where is the firmware version at, in case I run into this again down the road?

THANKS

**Comment by lah7** [comment]
> where is the firmware version at, in case I run into this again down the road?

Polychromatic shows this under the **Device Info** button. RazerGenie shows it at the bottom of the device page.

**Comment by 0pLuS0** [comment]
Firmware version 1.0 for the keyboard....

**Comment by 0pLuS0** [comment]
Might as well just follow up on everything in this Post.

https://github.com/openrazer/openrazer/issues/2066

THANKS
