### ISSUE TITLE
Support for Junglecat

### ISSUE THREAD

**Issue by someburner** [openrazer/razer-drivers#2071]
I don't own one of these so I can't provide debugging info, but I'm wondering where one might start with this? I'm looking for a joycon-like controller that specifically uses BLE, and this seems like it would be perfect other than not being open source or having any documentation.

Are there other BLE Razer devices that have been "opened" to some extent?

**Comment by z3ntu** [comment]
I don't imagine Razer uses a custom protocol for controllers, so I would guess that you just connect it and it works on Linux.

**Comment by someburner** [comment]
Cool I will try it out and see.

**Comment by someburner** [comment]
Okay yeah the do pair to linux just fine. Unfortunately the BLE GATT characteristics are a bit opaque to me but if bluez is able to connect and operate then it should be possible on a microcontroller.
