### ISSUE TITLE
Razer BlackWidow V3 Pro ( Wireless 1532:025C )

### ISSUE THREAD

**Issue by ZAKhan** [openrazer/razer-drivers#2081]
I have read all the old threads and could not find a solution.

Can someone please guide me in the right direction as to if : 

1. if a solution exists and how to implement it
2.  if there is no solution then whats the status if this is been looked into

Thanks

Z

**Comment by z3ntu** [comment]
You can follow #1279 which tracks this device. There is an open PR that adds support for this device but some things are not quite finished yet: #2056
If you want to build you can find instructions at https://github.com/openrazer/openrazer/wiki/Building-a-package
