### ISSUE TITLE
Documentation for persistence files

### ISSUE THREAD

**Issue by RiccardoBarbieri** [openrazer/razer-drivers#2083]
Where can I find a comprehensive documentation of keys and values that can be set in the persistence files?

**Comment by lah7** [comment]
I don't believe there's any dedicated documentation on this. The code has all the answers though:

https://github.com/search?q=repo%3Aopenrazer%2Fopenrazer+language%3APython+set_persistence&type=code&l=Python

Where `set_persistence` is used in the daemon, keys are determined like this:

```python
#    set_persistence(zone, key, value)
self.set_persistence("backlight", "effect", 'breathDual')    --> backlight_effect = breathDual
self.set_persistence(None, "dpi_x", dpi_x_scaled)            --> dpi_x = 1800
```

Grouped by serial number, e.g. `[PM1234567891234]`
