### ISSUE TITLE
Support for Razer Viper Mini SE

### ISSUE THREAD

**Issue by DeagledSmeagol** [openrazer/razer-drivers#2089]
### Device Info

* Name: Razer Viper Mini SE
* Product Number: RZ01-04410100
* Model Number: RZ01-0441

Something to note, this device did not come with the standard razer mini dongle, just a HyperPolling wireless dongle that seems to be a one off for this specific device.

I'm not much of a programmer, but if there anything I can do to help add this mouse to your project, please let me know.

### Device Pictures
![IMG_20230628_144346](https://github.com/openrazer/openrazer/assets/1642184/68168ec7-642f-4361-928d-b66b3a827676)
![IMG_20230628_144432](https://github.com/openrazer/openrazer/assets/1642184/28fdc8fd-f4cc-4159-964c-e5b8e33a1d6f)

### Device Information
```
Bus 005 Device 010: ID 1532:009f Razer USA, Ltd Razer Viper Mini Signature Edition
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x009f 
  bcdDevice            1.01
  iManufacturer           1 Razer
  iProduct                2 Razer Viper Mini Signature Edition
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              2 Razer Viper Mini Signature Edition
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.00
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      0 
      iInterface              2 Razer Viper Mini Signature Edition
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.00
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     260
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               4
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              2 Razer Viper Mini Signature Edition
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.00
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      63
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               4
Device Status:     0x0000
  (Bus Powered)
```

```
drwxr-xr-x 2 root root 420 Jun 28 14:34 .
drwxr-xr-x 4 root root 640 Jun 28 14:34 ..
lrwxrwxrwx 1 root root   9 Jun 28 11:22 usb-28bd_ACD02-event-kbd -> ../event3
lrwxrwxrwx 1 root root   9 Jun 28 11:22 usb-28bd_ACD02-event-mouse -> ../event2
lrwxrwxrwx 1 root root   9 Jun 28 11:22 usb-28bd_ACD02-if01-event-mouse -> ../event4
lrwxrwxrwx 1 root root   9 Jun 28 11:22 usb-28bd_ACD02-if01-mouse -> ../mouse2
lrwxrwxrwx 1 root root   9 Jun 28 11:22 usb-28bd_ACD02-mouse -> ../mouse0
lrwxrwxrwx 1 root root   9 Jun 28 14:34 usb-Logitech_USB_Receiver-if02-event-mouse -> ../event9
lrwxrwxrwx 1 root root   9 Jun 28 14:34 usb-Logitech_USB_Receiver-if02-mouse -> ../mouse4
lrwxrwxrwx 1 root root  10 Jun 28 13:54 usb-Razer_Razer_Viper_Mini_Signature_Edition-event-if01 -> ../event19
lrwxrwxrwx 1 root root  10 Jun 28 13:54 usb-Razer_Razer_Viper_Mini_Signature_Edition-event-mouse -> ../event13
lrwxrwxrwx 1 root root  10 Jun 28 13:54 usb-Razer_Razer_Viper_Mini_Signature_Edition-if01-event-kbd -> ../event14
lrwxrwxrwx 1 root root  10 Jun 28 13:54 usb-Razer_Razer_Viper_Mini_Signature_Edition-if01-event-mouse -> ../event15
lrwxrwxrwx 1 root root   9 Jun 28 13:54 usb-Razer_Razer_Viper_Mini_Signature_Edition-if01-mouse -> ../mouse7
lrwxrwxrwx 1 root root  10 Jun 28 13:54 usb-Razer_Razer_Viper_Mini_Signature_Edition-if02-event-kbd -> ../event20
lrwxrwxrwx 1 root root   9 Jun 28 13:54 usb-Razer_Razer_Viper_Mini_Signature_Edition-mouse -> ../mouse6
lrwxrwxrwx 1 root root   9 Jun 28 14:15 usb-YDKB_YD67BLE__USB_DN53_-event-if02 -> ../event8
lrwxrwxrwx 1 root root   9 Jun 28 14:15 usb-YDKB_YD67BLE__USB_DN53_-event-kbd -> ../event5
lrwxrwxrwx 1 root root   9 Jun 28 14:15 usb-YDKB_YD67BLE__USB_DN53_-if01-event-mouse -> ../event7
lrwxrwxrwx 1 root root   9 Jun 28 14:15 usb-YDKB_YD67BLE__USB_DN53_-if01-mouse -> ../mouse3
lrwxrwxrwx 1 root root  10 Jun 28 14:15 usb-YDKB_YD67BLE__USB_DN53_-if03-event-kbd -> ../event11
```

<details>

```
005:010:002:DESCRIPTOR         1687980893.146112
 05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01
 75 01 95 08 81 02 95 01 75 08 81 01 95 05 75 01
 05 08 19 01 29 05 91 02 95 01 75 03 91 01 95 06
 75 08 15 00 25 65 05 07 19 00 29 65 81 00 C0

005:010:001:DESCRIPTOR         1687980893.146485
 05 01 09 06 A1 01 85 01 05 07 19 E0 29 E7 15 00
 25 01 75 01 95 08 81 02 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 0E 81 00 05 08 19 01 29 03 15 00
 25 01 75 01 95 03 91 02 95 05 91 01 C0 05 01 09
 02 A1 01 85 0A 09 01 A1 00 05 09 19 01 29 06 15
 00 25 01 75 01 95 06 81 02 75 01 95 02 81 03 06
 00 FF 09 40 75 08 95 02 15 81 25 7F 81 02 05 01
 09 38 15 81 25 7F 75 08 95 01 81 06 09 30 09 31
 16 00 80 26 FF 7F 75 10 95 02 81 06 C0 C0 05 0C
 09 01 A1 01 85 02 19 00 2A 3C 02 15 00 26 3C 02
 95 01 75 10 81 00 75 08 95 0D 81 01 C0 05 01 09
 80 A1 01 85 03 19 81 29 83 15 00 25 01 75 01 95
 03 81 02 95 05 81 01 75 08 95 0E 81 01 C0 05 01
 09 00 A1 01 85 04 09 03 15 00 26 FF 00 35 00 46
 FF 00 75 08 95 0F 81 00 C0 05 01 09 00 A1 01 85
 05 09 03 15 00 26 FF 00 35 00 46 FF 00 75 08 95
 0F 81 00 C0

005:010:000:DESCRIPTOR         1687980893.146985
 05 01 09 02 A1 01 09 01 A1 00 05 09 19 01 29 05
 15 00 25 01 75 01 95 05 81 02 75 01 95 03 81 03
 06 00 FF 09 40 75 08 95 02 15 81 25 7F 81 02 05
 01 09 38 15 81 25 7F 75 08 95 01 81 06 09 30 09
 31 16 00 80 26 FF 7F 75 10 95 02 81 06 C0 06 00
 FF 09 02 15 00 25 01 75 08 95 5A B1 01 C0
```

</details>

### Packet Captures

GitHub wouldn't allow me to attach the .pcapng files directly so I zipped them. They are separated by function, and stripped of everything that isn't mouse <-> synapse communication. I also have some notes about what I think each thing in the protocol is doing if needed. Although I imagine these packets are fairly standard as they match your packet template under the reverse engineering guide.

[viperSE-pcap.zip](https://github.com/openrazer/openrazer/files/11899582/viperSE-pcap.zip)

Not sure if it makes a difference, but I triggered all the packets by clicking the settings from left to right, or top to bottom in the case of the Indicator LED on the HyperPolling dongle.

For the keybind configuration I set all keys to their default value under standard and hypershift In the order of top -> bottom on the left side, followed by top -> bottom on the right. Hope these help.

### Synapse Screenshots
<details>

<Screenshots of all available options as seen on **Razer Synapse** in a Windows Environment>

![screenshot_20230628-135354](https://github.com/openrazer/openrazer/assets/1642184/ff75fd27-131e-4199-9754-66f4096720b2)
![screenshot_20230628-135404](https://github.com/openrazer/openrazer/assets/1642184/c2438e32-4af9-4944-9af2-14bc3342567d)
![screenshot_20230628-135420](https://github.com/openrazer/openrazer/assets/1642184/83e32f9d-ba2f-40be-968b-6d5c3bcaa419)
![screenshot_20230628-135431](https://github.com/openrazer/openrazer/assets/1642184/f88624f0-f80e-45f2-af95-bc50f08869e4)
![screenshot_20230628-135438](https://github.com/openrazer/openrazer/assets/1642184/60c98f26-398e-4a1b-a46e-2b598ec7f364)
![screenshot_20230628-135443](https://github.com/openrazer/openrazer/assets/1642184/d8387bc8-2840-4b66-b00e-d405675e9135)

</details>

**Comment by DeagledSmeagol** [comment]
So, after looking through some of the commits for previous device additions, it appears adding a device to this driver is a bit less daunting that I originally presumed. I've created a fork with support for the Viper Mini SE in both wireless and wired configurations.

It compiles and works on my Arch desktop and an Ubuntu VM I was using for testing. Almost all of the features seem to be working great, except for configuring the asymmetric cutoff and smart tracking. Configuring the hyperpolling indicator works when set by 
```
echo $STATE > /sys/bus/hid/drivers/razermouse/$DEVICE/hyperpolling_wireless_dongle_indicator_led_mode 
```
but this configurable option doesn't seem to be picked up by any of the GUI's available. I imagine it's because it hasn't been implemented in the frontends, but I thought I would mention it anyway.

Lastly, not sure if this is driver related or not, but there is a bit of a weird thing with the reported default DPI stages in Polychromatic. They don't match the defaults in synapse at all, and are quite high. Not entirely sure why that is.

Anyway. Changes can be found on my github page, or by following the link here.
https://github.com/openrazer/openrazer/compare/master...fireflame90051:openrazer:master

If anyone has any insights on the issues listed above, or if I've missed something glaring, please let me know. Thanks!

I've also attached a couple screenshots showing the mouse working in Polychromatic.
<details>

![screenshot_20230702-170041](https://github.com/openrazer/openrazer/assets/1642184/aee054c3-ff38-420e-b2e8-109368ceec08)
![screenshot_20230702-170512](https://github.com/openrazer/openrazer/assets/1642184/2f11d299-347c-4ca9-888c-4ad1f17ed1d2)

</details>

**Comment by z3ntu** [comment]
If you haven't already opened a pull request with your changes, please do so!

**Comment by DeagledSmeagol** [comment]
Sorry, got caught up with another project and forgot to submit.

Pull request submitted. Thanks!

I'll go ahead and close this issue now.

**Comment by z3ntu** [comment]
Let's keep this open until support is merged, so people can find it.
