### ISSUE TITLE
Not Sure where to Ask, any suggestions on getting the Naga Hyperspeed V2 working with Bluetooth and not just 2.4

### ISSUE THREAD

**Issue by Madcliff** [openrazer/razer-drivers#2099]
Pretty sure this is not strictly a OpenRazer issue, but there seems to be an issue with the bluetooth mode for the Naga V2 Hyperspeed not sustaining a connection. I am almost confident that is related to some measure of power savings setting, and is likely a udev thing, but I am not sure where to begin in working out what needs to be changed so was hoping I might get some pointers here. 

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

**Comment by z3ntu** [comment]
Maybe you can find some github users in the issue for adding support for this device and get advise from them? I can't offer anything here since I don't own any Bluetooth-capable Razer device.

**Comment by 87dnz** [comment]
I own one but i don't know how to add support for it, let me know if you find a guide i can follow.

**Comment by stephanlamoureux** [comment]
I was able to get my deathadder connected to Bluetooth on a ThinkPad and Fedora 38. The laptop got fried, I replaced it with the same exact one, and now the mouse won't show up in Bluetooth devices 😢
