### ISSUE TITLE
Device battery reported as 0% (Naga Pro, DSV2PTKL, Pro Click)

### ISSUE THREAD

**Issue by Hamster42069** [openrazer/razer-drivers#2109]
### Distribution
Manjaro Linux, installed via yay. Openrazer doesn't seem to be correctly reporting my device battery, and it is giving constant notifications that my peripherals are at 0%.

**Comment by z3ntu** [comment]
Is the battery percent always reported at 0% or sometimes also at the correct percentage? Any error from razermouse in dmesg?

**Comment by VlaK0r** [comment]
> ### Distribution
> Manjaro Linux, installed via yay. Openrazer doesn't seem to be correctly reporting my device battery, and it is giving constant notifications that my peripherals are at 0%.

The same problem. Only I have a debian 12.

**Comment by Hamster42069** [comment]
hello, i am new to linux but this is my dmesg report https://pastebin.com/3Ch7VnPF

**Comment by z3ntu** [comment]
Okay, timeout unfortunately. I have some plans for the future how to improve the situation but unfortunately it's still a bit out.
