### ISSUE TITLE
1532:020f Razer USA, Ltd Blade QHD - This Supported Device Was Not Detected By OpenRazer Daemon

### ISSUE THREAD

**Issue by Ndashka-Dev** [openrazer/razer-drivers#2114]
### Distribution
RisiOS 37

### Support

- [X] Have you tried rebooting?
- [X] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I was trying to configure OpenRazer on my laptop, for the Razer Blade QHD keyboard. I have installed the `kernel-devel` package on RisiOS (a fork of Fedora), added the repository and installed `openrazer-meta` which installed `openrazer-daemon` and `openrazer-kernel-modules-dkms`. I have added myself to the `plugdev` group and restarted. I am now in the following groups: `wheel plugdev`. `lsusb | grep '1532:'` displays `Bus 001 Device 004: ID 1532:020f Razer USA, Ltd Blade QHD`. However, the contents of `ls /sys/bus/hid/drivers/` are only `hid-generic  hid-rmi  magicmouse  ntrig`. `razer-cli -l` from PyPI shows me `Found 0 Razer device(s)`. I am lost.

**Comment by lah7** [comment]
Sounds like the driver didn't install correctly or couldn't be loaded. What's the output of:

    sudo dkms status
    sudo modprobe razerkbd

Might be worth checking the kernel log too:

    dmesg | grep razer

**Comment by Ndashka-Dev** [comment]
> Sounds like the driver didn't install correctly or couldn't be loaded. What's the output of:
> 
> ```
> sudo dkms status
> sudo modprobe razerkbd
> ```
> 
> Might be worth checking the kernel log too:
> 
> ```
> dmesg | grep razer
> ```

For the above I got `openrazer-driver/3.6.1, 6.4.10-100.fc37.x86_64, x86_64: installed` and `modprobe: ERROR: could not insert 'razerkbd': Key was rejected by service`. `dmesg` gave me nothing...

**Comment by lah7** [comment]
> modprobe: ERROR: could not insert 'razerkbd': Key was rejected by service

Sounds like [Secure Boot](https://github.com/openrazer/openrazer/wiki/Troubleshooting#3-kernel-modules-do-they-load-properly) is the culprit. Easiest option would be to turn it off in your BIOS/UEFI settings, and then it should start working. The more complicated alternate is to sign the modules yourself.

**Comment by Ndashka-Dev** [comment]
Surprisingly, it actually started working, when Secure Boot was re-enabled (it was disabled beforehand). I am now closing this issue.
