### ISSUE TITLE
Deatadder V3 pro connection failed

### ISSUE THREAD

**Issue by Malfoy88** [openrazer/razer-drivers#2126]
### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

 Hey, guys! Installed  razer MacOs, but opening the app, don'tt see my device Deatadder V3 pro, list is empty. Mouse for now is working only connecting throug cable.Is there any option to do it via bluetooth?
Thank You in advance!

**Comment by z3ntu** [comment]
Pretty sure you're at the wrong issue tracker, we don't support macOS. Please find the issue tracker for the project you're using on macOS.
