### ISSUE TITLE
Would there be any interest in making a FreeBSD port?

### ISSUE THREAD

**Issue by duckyondiscord** [openrazer/razer-drivers#2152]
I'm pretty sure the userspace parts would function the same, save for a few path/prefix changes. 
Kernel modules would definitely need work, but with FreeBSD's LinuxKPI interface, providing a bunch of Linux kernel headers already, it's not that far out of reach with some skill and effort.

Just food for thought, for now. I'm in the midst of learning FreeBSD kernel driver development, so I'd definitely try helping where I can.

**Comment by z3ntu** [comment]
While I'm personally not interested in working on this, please feel free to take the code and make it work! There's already some projects to make the OpenRazer code work on macOS (in user space I believe).

On a sidenote years ago a rewrite of OpenRazer I started (never finished) also worked on FreeBSD, that project was/is using hidapi in the backend which works well there https://github.com/z3ntu/razer_test

**Comment by duckyondiscord** [comment]
> While I'm personally not interested in working on this, please feel free to take the code and make it work! There's already some projects to make the OpenRazer code work on macOS (in user space I believe).
> 
> On a sidenote years ago a rewrite of OpenRazer I started (never finished) also worked on FreeBSD, that project was/is using hidapi in the backend which works well there https://github.com/z3ntu/razer_test


Awesome! Thanks for the guidance :)
I am working on porting another Linux driver currently, but I'll definitely take a look after that. I don't think I can do something this big alone, though, so in the meantime if anyone's interested, do let me know!

**Comment by duckyondiscord** [comment]
Thought about it a little more, porting kernel modules may not be needed at all, if some people could implement it entirely in userspace on Mac.

**Comment by z3ntu** [comment]
Yes, most of the driver doesn't need to be a kernel driver, it's mostly just because of historic reasons. But however there are a few things that to my knowledge actually need to be handled there, such as some extra input handling etc. If you don't need any access to extra buttons on the device or so, then it shouldn't be necessary to have any extra handling for that.

**Comment by duckyondiscord** [comment]
The usbhid driver on FreeBSD already supports most extras I can think of, apart from DPI buttons but I think those are handled on-device. usbhid support multimedia keys, joysticks, all kinds of stuff, now idk how much Razer stuff complies with the standards it expects so that might be problem

**Comment by z3ntu** [comment]
See e.g. https://github.com/openrazer/openrazer/blob/master/driver/razermouse_driver.c#L4427 or `razer_raw_event`/`razer_event` in `razerkbd_driver.c` for what input mangling needs to happen - at least if the device is switched to driver mode
