### ISSUE TITLE
Newest update v.3.7.0 not covering all (new) devices?

### ISSUE THREAD

**Issue by ICDarki** [openrazer/razer-drivers#2155]
A week ago I installed the development build (master branch, kind of v3.6.1 dev) and those listed devices below worked flawlessly, as those new released Razer devices were not covered in the list on v3.6.1 stable.
I had to reinstall my OS (custom Arch Linux) and installed once again the dev master branch (it was updated to v3.7.0 few days ago).
In update v3.7.0 (master build) openrazer is not recognizing those devices. So I tried v3.7.0 stable (as those devices are officialy listed now) and the problem still persist.

My devices:

Razer Basilisk V3 Pro (Wired)             1532:00AA
Razer Basilisk V3 Pro (Wireless)	1532:00AB
Razer BlackWidow V4 Pro                  1532:028D

I'm not sure where the problem is, update side or my side.

**Comment by lah7** [comment]
Considering that the OS was reinstalled, have you added your user to the `plugdev` group again? Seems likely to be that if none of the devices show.

There is also the troubleshooting guide in case it's a driver issue (like if the driver is installed for the wrong kernel)
https://github.com/openrazer/openrazer/wiki/Troubleshooting

**Comment by ICDarki** [comment]
@lah7 Thank you!

Such a simple command. I thought I did .. but nope, I missed. It's working now. ✅
