### ISSUE TITLE
Stopped working after updating Fedora 38, openrazer 3.7.0 and Linux kernel 6.5.9

### ISSUE THREAD

**Issue by ad-on-is** [openrazer/razer-drivers#2158]
I recently updated my system, and openrazer stopped working. razercli -ls doesn't show any devices. Up until then, everything was working just fine.

Any clues?

**Comment by z3ntu** [comment]
Did you check the Troubleshooting page linked in the issue template at all?

**Comment by ad-on-is** [comment]
@z3ntu Admittedly, it never occurred to me to look into the troubleshooting guide. I assumed since it was working fine until now, that something broke in the package. 

Thx, I went through the steps, and everything is working again.
