### ISSUE TITLE
Razer Naga Epic Chroma does not support effects anymore

### ISSUE THREAD

**Issue by daxpedda** [openrazer/razer-drivers#2168]
### Distribution

Manjaro Linux
Kernel 6.6.1-1

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

When I try to change the effect or color of my scroll wheel or backlight on my Razer Naga Epic Chroma, I get an error that this is seemingly unsupported.
Checking the kernel logs I can see the following message:
`razermouse: matrix_effect_static not supported for this model`

This worked correctly before the current v3.7.0 and git (8b42841) version.

**Comment by z3ntu** [comment]
Thanks for opening, I made some changes lately that probably broke your device, I'll look into fixing it asap!

**Comment by z3ntu** [comment]
Sorry about that, seems during refactoring I broke this device :)

Could you please try if this diff helps you? If you need any advise how to build/test, please let me know!

```diff
diff --git a/driver/razermouse_driver.c b/driver/razermouse_driver.c
index 54082822..12d824d7 100644
--- a/driver/razermouse_driver.c
+++ b/driver/razermouse_driver.c
@@ -3095,6 +3095,8 @@ static ssize_t razer_attr_write_matrix_effect_spectrum_common(struct device *dev
     case USB_DEVICE_ID_RAZER_DEATHADDER_CHROMA:
     case USB_DEVICE_ID_RAZER_MAMBA_2012_WIRELESS:
     case USB_DEVICE_ID_RAZER_MAMBA_2012_WIRED:
+    case USB_DEVICE_ID_RAZER_NAGA_EPIC_CHROMA:
+    case USB_DEVICE_ID_RAZER_NAGA_EPIC_CHROMA_DOCK:
         request = razer_chroma_standard_set_led_state(VARSTORE, led_id, true);
         request.transaction_id.id = 0x3F;
         razer_send_payload(device, &request, &response);
@@ -3285,6 +3287,8 @@ static ssize_t razer_attr_write_matrix_effect_breath_common(struct device *dev,
     case USB_DEVICE_ID_RAZER_DEATHADDER_3500:
     case USB_DEVICE_ID_RAZER_DEATHADDER_CHROMA:
     case USB_DEVICE_ID_RAZER_DEATHADDER_2013:
+    case USB_DEVICE_ID_RAZER_NAGA_EPIC_CHROMA:
+    case USB_DEVICE_ID_RAZER_NAGA_EPIC_CHROMA_DOCK:
         if (count != 3) {
             printk(KERN_WARNING "razermouse: Static mode only accepts RGB (3byte)\n");
             return -EINVAL;
@@ -3456,6 +3460,8 @@ static ssize_t razer_attr_write_matrix_effect_static_common(struct device *dev,
     case USB_DEVICE_ID_RAZER_DEATHADDER_2013:
     case USB_DEVICE_ID_RAZER_MAMBA_2012_WIRELESS:
     case USB_DEVICE_ID_RAZER_MAMBA_2012_WIRED:
+    case USB_DEVICE_ID_RAZER_NAGA_EPIC_CHROMA:
+    case USB_DEVICE_ID_RAZER_NAGA_EPIC_CHROMA_DOCK:
         request = razer_chroma_standard_set_led_state(VARSTORE, led_id, true);
         request.transaction_id.id = 0x3F;
         razer_send_payload(device, &request, &response);
@@ -3643,6 +3649,8 @@ static ssize_t razer_attr_write_matrix_effect_none_common(struct device *dev, st
     case USB_DEVICE_ID_RAZER_OUROBOROS:
     case USB_DEVICE_ID_RAZER_OROCHI_2013:
     case USB_DEVICE_ID_RAZER_DEATHADDER_2000:
+    case USB_DEVICE_ID_RAZER_NAGA_EPIC_CHROMA:
+    case USB_DEVICE_ID_RAZER_NAGA_EPIC_CHROMA_DOCK:
         request = razer_chroma_standard_set_led_state(VARSTORE, led_id, false);
         request.transaction_id.id = 0x3F;
         break;

```

**Comment by daxpedda** [comment]
As far as I can tell nothing changed.
You can see the change I did here: https://github.com/daxpedda/openrazer/tree/naga-epic-chroma-effects.

I used that to install the DKMS modules and the daemon just to make sure. I think only the DKMS modules were required, am I missing anything?

**Comment by z3ntu** [comment]
Did you use this for installing? https://github.com/openrazer/openrazer/wiki/Building-a-package#build-packages-from-a-different-github-repository

And then after installing the package, reboot so the new kernel modules get loaded.

**Comment by daxpedda** [comment]
> Did you use this for installing? https://github.com/openrazer/openrazer/wiki/Building-a-package#build-packages-from-a-different-github-repository

I didn't know about this documentation, but that is exactly what I did. I just didn't do the whole meta thing, just the DKMS and daemon package, which should be fine?
> And then after installing the package, reboot so the new kernel modules get loaded.

Yes, I did reboot.

**Comment by z3ntu** [comment]
Yes just installing the updated `openrazer-driver-dkms-git` should be enough. Can you send `pacman -Q openrazer-driver-dkms-git` output?

**Comment by daxpedda** [comment]
```
> pacman -Q openrazer-driver-dkms-git
openrazer-driver-dkms-git 3.7.0.r1.g8b428410-1
```
What is this supposed to show? I also tried with `--verbose` and `--info`, but it doesn't seem to show any relevant information, like which git repository was used.
I did confirm though that my fork and branch was used through the build logs.

**Comment by z3ntu** [comment]
Yeah you didn't build from the branch you patched but from master branch (commit 8b428410), it should show fe1e6a5d in there. Please double check your PKGBUILD that you point it to the correct branch.

**Comment by daxpedda** [comment]
So before I was using an edited build file inside of Pamac, which at least seemed to work.
Building it myself seemed to cause some problems in the `pkgver()` function but I managed to solve that by just using `echo 1`.

Will report back when I restart.

**Comment by daxpedda** [comment]
Everything seems to work now!

EDIT: Let me know if it takes off any work if I create the PR.

**Comment by z3ntu** [comment]
Already pushed, thanks! I'm currently not planning a bugfix release just for that device, I hope it's okay for you to run openrazer-git for now until the next release. Unless plenty more people with the same device are hitting this issue, but I'd guess the numbers of people with this device is rather low.

Thanks for reporting and testing it!

**Comment by daxpedda** [comment]
No worries, thank you for the quick fix!
