### ISSUE TITLE
openrazer - 'this supported devices wasn't detected by the OpenRazer deamon (v3.7.0)

### ISSUE THREAD

**Issue by emirhanyagci** [openrazer/razer-drivers#2170]
Hi i installed  polychromatic with openrazer,
i see my devices in the polychromatic but couldn't manage them 
![image](https://github.com/openrazer/openrazer/assets/66957950/67ebe28a-8c9f-4fc4-aede-178cf31ce79d)

My Distributions : debian 12

Greatly appreciate your help.

**Comment by z3ntu** [comment]
Have you checked https://github.com/openrazer/openrazer/wiki/Troubleshooting ?

**Comment by emirhanyagci** [comment]
Sorry for my late reply.
I wasn't checked , i found solution of my problem at this repo thank u so much 
The problem for me was that secure boot was enabled.
