### ISSUE TITLE
New to Linux/ubuntu

### ISSUE THREAD

**Issue by Vexuss12** [openrazer/razer-drivers#2173]
### Support

- [ ] Have you tried rebooting?
- [ ] Yes
- [ ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?
- [ ] Yes

I have had issues getting the drivers to work. I can't get them in the right folders or figure out what even I need to do. I've followed some of the troubleshooting guides and can't quite figure it out. The first image is where I started and then went from there and got the following in the terminal. 
sudo modprobe razerkbd
modprobe: FATAL: Module razerkbd not found in directory /lib/modules/6.5.7-060507-generic
 Then I followed more troubleshooting stuff. Help would be appreciated!
![Screenshot from 2023-11-25 12-40-17](https://github.com/openrazer/openrazer/assets/148642250/18835283-435a-4d8c-a667-add1ca78e1b6)
to the second image. I can find the razerkdb  .h and .c files but... I can't seem to figure out what to do next.
![Screenshot from 2023-11-25 12-36-41](https://github.com/openrazer/openrazer/assets/148642250/793211ce-c38c-4464-8a69-8a4a4722260a)
EDIT: The second photo is meant to be the first.

**Comment by z3ntu** [comment]
What's the output of `sudo dkms install openrazer-driver/3.7.0`? I'm guessing your kernel headers are missing
