### ISSUE TITLE
Support for Razer BlackShark V2 Pro

### ISSUE THREAD

**Issue by alansenairj** [openrazer/razer-drivers#2184]
### Device Info

* Name: Razer BlackShark V2 Pro
* Product Number: RZ04-04530100-R3U1
* Model Number: RZ04-0453

### Device Information
```
Bus 001 Device 008: ID 1532:0555 Razer USA, Ltd [unknown]
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 [unknown]
  bDeviceSubClass         0 [unknown]
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0555 [unknown]
  bcdDevice            0.01
  iManufacturer           0 
  iProduct                2 Razer BlackShark V2 Pro 2.4
  iSerial                 3 O001000007
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x00e0
    bNumInterfaces          4
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           0
      bInterfaceClass         1 Audio
      bInterfaceSubClass      1 Control Device
      bInterfaceProtocol      0 
      iInterface              0 
      AudioControl Interface Descriptor:
        bLength                10
        bDescriptorType        36
        bDescriptorSubtype      1 (HEADER)
        bcdADC               1.00
        wTotalLength       0x0046
        bInCollection           2
        baInterfaceNr(0)        1
        baInterfaceNr(1)        2
      AudioControl Interface Descriptor:
        bLength                12
        bDescriptorType        36
        bDescriptorSubtype      2 (INPUT_TERMINAL)
        bTerminalID             1
        wTerminalType      0x0201 Microphone
        bAssocTerminal          0
        bNrChannels             1
        wChannelConfig     0x0000
        iChannelNames           0 
        iTerminal               0 
      AudioControl Interface Descriptor:
        bLength                 8
        bDescriptorType        36
        bDescriptorSubtype      6 (FEATURE_UNIT)
        bUnitID                 2
        bSourceID               1
        bControlSize            1
        bmaControls(0)       0x03
          Mute Control
          Volume Control
        iFeature                0 
      AudioControl Interface Descriptor:
        bLength                 9
        bDescriptorType        36
        bDescriptorSubtype      3 (OUTPUT_TERMINAL)
        bTerminalID             3
        wTerminalType      0x0101 USB Streaming
        bAssocTerminal          0
        bSourceID               2
        iTerminal               0 
      AudioControl Interface Descriptor:
        bLength                12
        bDescriptorType        36
        bDescriptorSubtype      2 (INPUT_TERMINAL)
        bTerminalID             4
        wTerminalType      0x0101 USB Streaming
        bAssocTerminal          0
        bNrChannels             2
        wChannelConfig     0x0003
          Left Front (L)
          Right Front (R)
        iChannelNames           0 
        iTerminal               0 
      AudioControl Interface Descriptor:
        bLength                10
        bDescriptorType        36
        bDescriptorSubtype      6 (FEATURE_UNIT)
        bUnitID                 5
        bSourceID               4
        bControlSize            1
        bmaControls(0)       0x03
          Mute Control
          Volume Control
        bmaControls(1)       0x00
        bmaControls(2)       0x00
        iFeature                0 
      AudioControl Interface Descriptor:
        bLength                 9
        bDescriptorType        36
        bDescriptorSubtype      3 (OUTPUT_TERMINAL)
        bTerminalID             6
        wTerminalType      0x0301 Speaker
        bAssocTerminal          0
        bSourceID               5
        iTerminal               0 
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           0
      bInterfaceClass         1 Audio
      bInterfaceSubClass      2 Streaming
      bInterfaceProtocol      0 
      iInterface              0 
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       1
      bNumEndpoints           1
      bInterfaceClass         1 Audio
      bInterfaceSubClass      2 Streaming
      bInterfaceProtocol      0 
      iInterface              0 
      AudioStreaming Interface Descriptor:
        bLength                 7
        bDescriptorType        36
        bDescriptorSubtype      1 (AS_GENERAL)
        bTerminalLink           3
        bDelay                  1 frames
        wFormatTag         0x0001 PCM
      AudioStreaming Interface Descriptor:
        bLength                11
        bDescriptorType        36
        bDescriptorSubtype      2 (FORMAT_TYPE)
        bFormatType             1 (FORMAT_TYPE_I)
        bNrChannels             1
        bSubframeSize           2
        bBitResolution         16
        bSamFreqType            1 Discrete
        tSamFreq[ 0]        48000
      Endpoint Descriptor:
        bLength                 9
        bDescriptorType         5
        bEndpointAddress     0x87  EP 7 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0068  1x 104 bytes
        bInterval               1
        bRefresh                0
        bSynchAddress           0
        AudioStreaming Endpoint Descriptor:
          bLength                 7
          bDescriptorType        37
          bDescriptorSubtype      1 (EP_GENERAL)
          bmAttributes         0x00
          bLockDelayUnits         0 Undefined
          wLockDelay         0x0000
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           0
      bInterfaceClass         1 Audio
      bInterfaceSubClass      2 Streaming
      bInterfaceProtocol      0 
      iInterface              0 
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       1
      bNumEndpoints           1
      bInterfaceClass         1 Audio
      bInterfaceSubClass      2 Streaming
      bInterfaceProtocol      0 
      iInterface              0 
      AudioStreaming Interface Descriptor:
        bLength                 7
        bDescriptorType        36
        bDescriptorSubtype      1 (AS_GENERAL)
        bTerminalLink           4
        bDelay                  1 frames
        wFormatTag         0x0001 PCM
      AudioStreaming Interface Descriptor:
        bLength                11
        bDescriptorType        36
        bDescriptorSubtype      2 (FORMAT_TYPE)
        bFormatType             1 (FORMAT_TYPE_I)
        bNrChannels             2
        bSubframeSize           2
        bBitResolution         16
        bSamFreqType            1 Discrete
        tSamFreq[ 0]        48000
      Endpoint Descriptor:
        bLength                 9
        bDescriptorType         5
        bEndpointAddress     0x06  EP 6 OUT
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x00d0  1x 208 bytes
        bInterval               1
        bRefresh                0
        bSynchAddress           0
        AudioStreaming Endpoint Descriptor:
          bLength                 7
          bDescriptorType        37
          bDescriptorSubtype      1 (EP_GENERAL)
          bmAttributes         0x01
            Sampling Frequency
          bLockDelayUnits         0 Undefined
          wLockDelay         0x0000
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        3
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 [unknown]
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     103
          Report Descriptors: 
            ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
```
```
Permissions Size User Date Modified Name
drwxr-xr-x     - root 19 Dec 14:54  /dev/input/by-id
lrwxrwxrwx     9 root 19 Dec 14:54  ├── ckb-Corsair_Gaming_K95_RGB_PLATINUM_Keyboard_vKB_-event -> ../event3
lrwxrwxrwx     9 root 19 Dec 14:54  ├── ckb-Corsair_Gaming_K95_RGB_PLATINUM_Keyboard_vM_-event -> ../event4
lrwxrwxrwx     9 root 19 Dec 14:54  ├── usb-1532_Razer_BlackShark_V2_Pro_2.4_O001000007-event-if03 -> ../event7
lrwxrwxrwx    10 root 19 Dec 14:54  ├── usb-Logitech_USB_Receiver-event-if01 -> ../event10
lrwxrwxrwx     9 root 19 Dec 14:54  ├── usb-Logitech_USB_Receiver-event-kbd -> ../event8
lrwxrwxrwx     9 root 19 Dec 14:54  ├── usb-Logitech_USB_Receiver-if01-event-mouse -> ../event9
lrwxrwxrwx     9 root 19 Dec 14:54  └── usb-Logitech_USB_Receiver-if01-mouse -> ../mouse1
```
```
001:008:003:DESCRIPTOR         1703009198.031110
 05 0C 09 01 A1 01 85 01 15 00 25 01 09 CD 09 B5
 09 B6 09 B7 75 01 95 04 81 02 15 00 25 01 09 B0
 09 B1 09 B3 09 B4 75 01 95 04 81 22 15 00 25 01
 09 E9 09 EA 09 E2 75 01 95 03 81 22 75 05 95 01
 81 01 C0 06 00 FF 09 01 A1 01 85 02 15 00 26 FF
 00 09 02 75 08 95 3F 81 02 15 00 26 FF 00 09 03
 75 08 95 3F 91 02 C0
```

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots

![image](https://github.com/openrazer/openrazer/assets/20565821/0e15db46-e811-42ff-9312-7745c9ca6902)

![image](https://github.com/openrazer/openrazer/assets/20565821/0f76c015-338b-49fc-a14b-61df1431cbbe)

![image](https://github.com/openrazer/openrazer/assets/20565821/0f9b3925-787f-49ad-88fa-9c49df2042f3)

![image](https://github.com/openrazer/openrazer/assets/20565821/8d7e264a-c7a0-47bf-a21a-59af176ecb22)

**Comment by z3ntu** [comment]
Thanks for opening the issue! You can also take a look at https://github.com/openrazer/openrazer/blob/master/DEVELOPMENT.md how you could add support for this device yourself.

**Comment by alansenairj** [comment]
> Thanks for opening the issue! You can also take a look at https://github.com/openrazer/openrazer/blob/master/DEVELOPMENT.md how you could add support for this device yourself.

It is really difficult to develop a driver for me. It is not my skill. I can write shellscripts and I know very little about python but I really don't know how to start. I read this link and it is about dev. environment setup. 

The problem is mic via USB dongle is not working. It can't be detected. 

By the way I can share my experience here using this product. It's output works well in blue tooth and USB dongle. I just configure KDE output. In bluetooth I choose a HD codec because default configuration was nasty. 

Dongle USB configuration: 
![image](https://github.com/openrazer/openrazer/assets/20565821/ebbdac1a-d138-495c-8b54-42129830ec3e)

BT configuration

![image](https://github.com/openrazer/openrazer/assets/20565821/5a0826b8-42a5-4cc0-b917-2a799a442833)

**Comment by alansenairj** [comment]
I am suspecting this issue is a problem in my  KDE Fedora instalation. When a do all steps to capture USB traffic I tested mic using Fedora 39 with Gnome and I can use mic. 

![image](https://github.com/openrazer/openrazer/assets/20565821/817da64f-2bb3-4d73-8e92-485f4ca6cff3)

So I even need to capture nothing. I will do some update here and go back with results. 
![image](https://github.com/openrazer/openrazer/assets/20565821/65694e62-bea4-476d-ac07-010bd110ff15)

**Comment by alansenairj** [comment]
I got it. The configurations are pretty confuse using KDE. It is tricky to make it work. 

First i list the device 
arecord -l

![image](https://github.com/openrazer/openrazer/assets/20565821/bdf8b4e2-5e53-486f-96e8-a9d9be8987b8)

Then I config setting like this:

![image](https://github.com/openrazer/openrazer/assets/20565821/cf308c33-fcb7-4284-bfa0-3153adcb9a8e)

I config meeting like this too:

![image](https://github.com/openrazer/openrazer/assets/20565821/fc2993cf-ce70-4349-9b63-21b8e9cd29d7)

Audacity stopped to work and I choose "DEFAULT" as record device. 

![image](https://github.com/openrazer/openrazer/assets/20565821/91674e25-f469-47cc-80c7-fee094e2597a)


So I think it needs to be carefully configured. The problem was changing a profile at KDE audio dropdown menu it eliminate options based on your selection and then Razer's Mic selection disappears from the list and it not works because profile doesn't show it anymore to other softwares. 

I think you could use this troubleshot  if you have same problem. 

It is working by default in Fedora 38/39. I must select device as "stereo analog output + mono input".
This option gives you an option in record devices to select your mic there.

**Comment by alansenairj** [comment]
So the problem was solved and it was a profile configuration issue at KDE advanced audio part.

**Comment by marcosilva85** [comment]
@alansenairj 
I assume you have the blackshark v2 pro 2023 version, which linux distro do you use?

- does the mic performs in [high-quality like in this video](https://youtu.be/7_xjpBYwm5g?t=307)
- how well does this model worked for you in linux, is it good in music and films or do you think the Windows software (synapse 3) would be required for this model to perform well by default?

**Comment by alansenairj** [comment]
I Marcos. Are you Brazilian? 

I tested it in Fedora 38/39 upgraded. I installed this driver. 
I am using now a fresh Fedora 39 install. On fresh install I did nothing. It is detected by system and I am using it with dongle. 

The mic is the best. It is almost the same as a good as dynamic mic I used with my soundcard later.

So if you want to deep dive in configs it is mandatory to install easy effects flatpak app. Despite it is a little awkward it is intuitive and you just get Linux DAW plugins working with your razer. Those plugins are pro and they are better than Razer's software. 

I am using   this setup and this one autoloads with system:

![image](https://github.com/openrazer/openrazer/assets/20565821/851d0ffd-5d6d-4fdb-8295-624269c0187f)

Askme anythig. I am daily user. You must adapt a little to use with teams. Sometimes I get some problems. It is not rock solid but Teams is not a rock solid software too.

**Comment by marcosilva85** [comment]
Portuguese :)
Nice! I've seen customers so many problems with this 2023 pro version in Windows that hearing that it works fine in Linux is uplifting!

The dynamic mic is why I want to get it!
But then in Linux you do not get by default the impressive mic-quality that Windows gets, so its required to equalize it a bit?
How does the mic sound without eq on it?
(I will also need to use it in MacOS at work and company does not allow eq. software, hence the question).

Did you had to update firmwares for some reason? Which firmware version are you currently running of dongle/headset?

**Comment by alansenairj** [comment]
I Marcos, sorry for delay. 
Cara, eu tive um desastre aqui e tive que formatar o Fedora por um backup corrompido de OS que não funcionou. Mas temos boas e más notícias. A boa é que o dongle USB funcionou nativamente. A ruim é que o dongle muito provavelmente está acordando o PC da suspensão. 

Eu ia gravar um vídeo comparando o audio, mas não estou com tempo. O que o pessoal do trabalho me falou é que o som é o mesmo. 

Mais pra frente eu faço o comparativo e atualizo em Inglês. O fone é bom o mic é foda, mas tem esses problemas de acordar o PC no Fedora 39

**Comment by guilhermetk** [comment]
@alansenairj 

can you share which app is that one you posted on which you can control Denoise, Voice detection, etc...? also, another BR here :)

**Comment by alansenairj** [comment]
> @alansenairj
> 
> can you share which app is that one you posted on which you can control Denoise, Voice detection, etc...? also, another BR here :)

saudações Guilherme, use o easyeffects. Tem no próprio repo do Fedora, "sudo dnf install -y easyeffects"

Deixa eu passar um feedback. O funcionamento do fone não é tão estável assim. Já tive problemas loucos aqui durante o uso. Gostaria que fosse mais confiável. Mas funciona bem no geral. 

Aqui é Fedora, e tem pipewire no soim, isso é importante. Funcionou sem precisar do driver. às vezes eu preciso desconectar o dongle para ele reencontrar. 

O software para carregar os plugins é muito bom. é flexível e carrega rápido. Mas nas novas versões do proprio teams eu tenho observado que o filtro de barulho tem funcionado a contento. 

no geral, não é essa maravilha, gostaria que fosse mais confiável, tipo, ligou funcionou, mas tem que conviver né. 

vlww e boa sorte 



![image](https://github.com/openrazer/openrazer/assets/20565821/8aa5f09c-fba4-4fe7-9fb3-1edb1c5ec71a)

![image](https://github.com/openrazer/openrazer/assets/20565821/af44c2dc-6db5-4de5-9fa3-043cef2c8db4)

**Comment by makarov-roman** [comment]
V2 Pro (2023) ,Fedora 40/Gnome  - I can see the mic, but it doesn't work. installed openrazer with no effect. Any ideas? how to fix it?

**Comment by Xpiravit** [comment]
@makarov-roman did you get it working?

**Comment by alansenairj** [comment]
me too. Fedora 39 mic worked but Fedora 40 not. I got some issues on sound but it is related to my /home reusing. 

My mic is not working. Even using it connect in Bluetooth .

**Comment by makarov-roman** [comment]
@Xpiravit yeah, but I don't understand how. At some point it just started to work as expected. I removed openrazer and didn't install any additional components.
Make sure to turn on physical switch, select Analog output in sound settings (without that volume loudness is limited for me).

**Comment by alansenairj** [comment]
Hi! I am using now with Bluetooth. Mic is working. I am not using with dongle anymore. 
About Fedora 40, there was a lot of problems in audio reusing /home because of kde upgrade from 5 to 6 differs a lot from each other. But beside that my system is stable now using bluetooth. I hope it helps you in some way.

**Comment by xela-zone** [comment]
i'd like to be able to get the battery levle of my headset - any idea how to do that?

**Comment by alansenairj** [comment]
> i'd like to be able to get the battery levle of my headset - any idea how to do that?

KDE gives the level by default

<img width="533" height="182" alt="Image" src="https://github.com/user-attachments/assets/d25e21f4-fe66-424c-b020-1f6e5a59b770" />

**Comment by xela-zone** [comment]
> > i'd like to be able to get the battery levle of my headset - any idea how to do that?
> 
> KDE gives the level by default
> 
> 

If you're connected over Bluetooth, sure. But I'm using the dongle, and depend on the stereo sound & recording at the same time

**Comment by enesbsafak** [comment]
## BlackShark V2 Pro (2023) `1532:0555` — the requested pcap would not help for EQ

This issue is tagged `need pcap`. I went and looked at the Windows side, and I
think the pcap is not the blocker — the audio processing everyone is asking for
does not travel over USB at all. Evidence below.

### 1. On Windows, all DSP runs host-side as an APO

The 2.4 GHz dongle's render endpoint has a THX APO chain attached:

```
oem39.inf : THX_Spatial_Audio_for_Digital_Peripherals : 3.2.3.0 : USB\VID_1532&PID_0555&MI_00
```

`HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\MMDevices\Audio\Render\{…}\FxProperties`
carries three separate APO CLSIDs (SFX / MFX / EFX) plus the friendly name
`THX Spatial Audio (BlackShark V2 Pro)`.

### 2. The user-facing settings are stored on the host, not on the device

The same `FxProperties` key holds the complete live configuration as plain JSON
(property `{d5e8f0ab-4de6-4d91-ab21-68868dda6a4a},6`):

```json
{
  "hardwareId": "usb\\1532\\0555",
  "presetName": "Custom",
  "eqCurve": [31 values],
  "spatialEnabled": false,
  "spatialProcessingMode": "Headphones5",
  "drcEnabled": true, "drcLevel": 0,
  "bassBoostEnabled": false, "bassBoost": 50,
  "dialogEnhancementEnabled": false, "dialogEnhancement": 50,
  "tilt": 0,
  "room": { "roomName": "Studio", "roomDimensions": [5.5, 4.1, 2.9], … },
  "emitterPositions": { … }
}
```

A protobuf-encoded copy of the same struct sits next to it in `,7`.

### 3. The device-specific tuning is a host-side file

`C:\ProgramData\THX\usb\1532\0555\thx_spatial.conf.json` (181 KB),
`deviceName: 1532-razer-0555-odessa-t1r-generic-V2`, THX signal-flow schema v2,
version 4.20.1. It contains the actual filter design data:

- `HeadphonePath.FastEqualizer` — a 31-band 1/3-octave EQ (`THIRD_OCTAVE_EQ`,
  20 Hz–20 kHz with explicit band edges), a `FASTEQ_MATRIX` mapping third-octave
  targets to filter coefficients, and 19 named target curves including
  `HP Deconvolution Stereo Source` (the driver correction curve).
- `HeadphonePath.HeadphoneVolumeLevelingDRC` — a 6-point DRC scale
  (level 0 → ratio 2, threshold −6 dB, width 3, makeup +4 dB, attack 0.1 ms,
  decay 100 ms).
- `crosstalkV11` (−4.5 dB, 226.2 µs, biquad), `WidthExpansion`, `DCRemoval`,
  `LastResortDRC`, `McdeDRC` — all as raw biquad coefficient sets at fs = 48000.

So EQ, spatial, bass boost, DRC and dialogue enhancement are computed in the
Windows audio graph **before** samples reach the USB link.

### 4. Consequence for openrazer

Capturing Synapse moving an EQ slider will not reveal a device command, because
there is no device command to capture. Implementing the vendor protocol for this
model would not change how the headset sounds on Linux.

For anyone who landed here because Linux sounds thinner than Windows: the fix is
to reproduce the host-side chain locally (EasyEffects or equivalent). The
parameters above are sufficient to do it — the dominant term is the
`HP Deconvolution Stereo Source` curve, which lifts bass/low-mids by roughly 3 dB
relative to everything above 1.6 kHz.

### 5. What is still unknown

I am **not** claiming the device speaks no vendor protocol at all. Battery level,
mic mute, sidetone and the volume wheel are plausibly still device-side, and a
pcap would legitimately help for those. The claim is narrower: the *audio
processing* is host-side, so the `need pcap` blocker does not apply to EQ.

### 6. Why the current openrazer probing fails on this model

The HID report descriptor on interface 3 (`/dev/hidrawN`, endpoints `0x02 OUT` /
`0x83 IN`, interrupt, 64 bytes, bInterval 1) decodes to:

```
06 00 FF   Usage Page (Vendor Defined 0xFF00)
A1 01      Collection (Application)
85 02        Report ID (2)
75 08 95 3F  Report Size 8 × Count 63
81 02        INPUT   (63 bytes)
91 02        OUTPUT  (63 bytes)
C0
```

There is **no Feature report** — not a single `B1` item. openrazer's transport is
built on 90-byte feature reports over control transfers, which this descriptor
does not expose. I tried 35 standard read-only queries (firmware version, serial,
device mode, battery level, charging status × 7 transaction IDs); all 35 returned
`Errno 110` (timeout). That is not evidence of a different protocol dialect — it
is evidence that the door openrazer knocks on does not exist on this device. Any
future support would have to go through Report ID `0x02`, 63 bytes, on the
interrupt endpoints.

Happy to run further read-only probes on the Linux side if that is useful.
