### ISSUE TITLE
Razer Device not Detected on Ubuntu 23.10

### ISSUE THREAD

**Issue by hadinatasalim100** [openrazer/razer-drivers#2185]
![image](https://github.com/openrazer/openrazer/assets/54607817/accdb372-c9a7-460b-b3bc-44e0a8648437)

i got the problem like this, im using Razer Hunstman Mini and Razer Deathadder Essential

**Comment by z3ntu** [comment]
Did you check the Troubleshooting page already? https://github.com/openrazer/openrazer/wiki/Troubleshooting
