### ISSUE TITLE
Change layout keyboar in Razer Cynosa V2 Linux mint 21.1

### ISSUE THREAD

**Issue by viniciusslisboa** [openrazer/razer-drivers#2186]
### Distribution

Linux mint 21.1

### Support

- [ x] Have you tried rebooting?
- [ x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I need to change the keyboard layout to "pt_PT" (Portuguese), but I couldn't do it through polychromatic, and I also couldn't do it through the CLI. How can I change the layout?

**Comment by z3ntu** [comment]
I believe this was answered in the community chat with this link: https://www.linuxquestions.org/questions/slackware-14/xfce-how-to-change-the-keyboard-layout-322374/
