### ISSUE TITLE
DPI showing 26000 instead of 30000

### ISSUE THREAD

**Issue by beyondbrokkoli** [openrazer/razer-drivers#2194]
Using a Basilisk V3 Pro.
Like the title suggests the maximum DPI available with the openrazer daemon is 26000.
Im not saying using 30k is a reasonable thing to do but either razer is lying or the device is not fully supported.
the mouse works fine with and without installing openrazer.
when i first started razercommander it showed both sliders at 0 dpi and polling at 500 hz even though the mouse was configured to 30k dpi and 1000hz. this is not an issue with razercommander because ive seen the maximum 26000 also in the output of another cli openrazer tool (don't remember the name)

**Comment by z3ntu** [comment]
You're right, https://www.razer.com/eu-en/gaming-mice/razer-basilisk-v3-pro/RZ01-04620100-R3G1#specs shows "MAX SENSITIVITY (DPI) 30000" but the code has set a maximum of 26000: https://github.com/openrazer/openrazer/blob/master/daemon/openrazer_daemon/hardware/mouse.py#L1595

Can you try editing this file on your PC (`find /usr -name mouse.py` should find it, then restart the daemon with `systemctl --user restart openrazer-daemon.service`) and see if that resolves the issue?

(CC @6razz1)

**Comment by beyondbrokkoli** [comment]
Yes that solved the issue, thank you for the quick reply.
