### ISSUE TITLE
`dh-dkms` should be added to the Ubuntu building wiki as a dep

### ISSUE THREAD

**Issue by alichtman** [openrazer/razer-drivers#2198]
[`dh-dkms` is required for Ubuntu 23.04 and later](https://github.com/openrazer/openrazer/blob/master/debian/control#L9-L10), so it should be added to the `apt install` command in the wiki [here](https://github.com/openrazer/openrazer/wiki/Building-a-package#ubuntu--linux-mint) 

### Distribution

Ubuntu 23.10

**Comment by lah7** [comment]
Thanks, wiki updated. Thought this sounded familiar: https://github.com/openrazer/openrazer/commit/374f093d5bffd0942d2e6d457afc347c22be9046 (under a different error)
