### ISSUE TITLE
random popups on debian testing (xfce) for razer pro click with wrong information

### ISSUE THREAD

**Issue by damnms** [openrazer/razer-drivers#2203]
### Distribution
debian trixie

### Support

- [ x] Have you tried rebooting?
- [x ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

whenever i work at my workstation, i randomly get popups telling me something about my mouse. either its that it has 0% power, 5 minutes later it has 27%, and so on. feels very random and it starts to annoy me. it would be ok for me to disable those popups alltogether if possible. But i dont know where to disable that.

**Comment by lah7** [comment]
The battery notifications reporting the wrong info is a known (annoying) issue (#2122). In future, battery notifications could be superseded by a better integration into the desktop environment (#87, #2160)

In the meantime, you can disable these notifications by editing this file in your home directory:

    ~/.config/openrazer/razer.conf

Set this line to `False`:

    battery_notifier = False

Changes will take effect at next login or by restarting the daemon via the terminal:

    openrazer-daemon -r
