### ISSUE TITLE
Mouse not detected

### ISSUE THREAD

**Issue by noteyeris** [openrazer/razer-drivers#2208]
### Support

- [ x ] Have you tried rebooting?
- [ x ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I am trying to get this to work on my steam deck so I can use my side buttons but it keeps saying that no devices were detected. I have tried several fixes here but to no avail.

**Comment by z3ntu** [comment]
Can you share how you installed OpenRazer on the Steam Deck? We also don't officially support Steam Deck so I can't really help you much there.
