### ISSUE TITLE
Unit openrazer-daemon.service could not be found. Fedora 39

### ISSUE THREAD

**Issue by ynuske** [openrazer/razer-drivers#2221]
I installed using  -sudo dnf config-manager --add-repo https://download.opensuse.org/repositories/hardware:razer/Fedora_39/hardware:razer.repo
- sudo dnf install razergenie
but when I logged in it said "Unit openrazer-daemon.service could not be found."

and I also installed openrazer from the website using
sudo dnf install kernel-devel

![Captura de tela de 2024-03-13 20-21-54](https://github.com/openrazer/openrazer/assets/134338764/ae3cf5ef-c7ad-46be-ad2c-c6a79289144b)
sudo dnf config-manager --add-repo https://download.opensuse.org/repositories/hardware:/razer/Fedora_$(rpm -E %fedora)/hardware:razer.repo

sudo dnf install openrazer-meta

**Comment by lah7** [comment]
Installing `openrazer-meta` should install `openrazer-daemon` too. Is the daemon working?

    openrazer-daemon -F

If not, try installing that package explicitly:

    sudo dnf install openrazer-daemon

**Comment by ynuske** [comment]
Hi, I tried everything in Fedora, but I couldn't. So I decided to change distros and installed Arch Linux, but the same error happened.
![Captura de tela de 2024-03-16 11-40-11](https://github.com/openrazer/openrazer/assets/134338764/426324d0-40d3-44f1-9cb6-03511b5b02ba)
![Captura de tela de 2024-03-16 11-42-23](https://github.com/openrazer/openrazer/assets/134338764/4773e218-c62d-4ad0-b767-9233b464a513)

**Comment by z3ntu** [comment]
What's the output of `systemctl --user status openrazer-daemon.service`  ? And `ls -al /usr/lib/systemd/user/openrazer-daemon.service` ?

**Comment by ynuske** [comment]
look 
![Captura de tela de 2024-03-18 18-36-17](https://github.com/openrazer/openrazer/assets/134338764/b419f7f5-4620-4d72-ac27-ff70f8ccf391)
![Captura de tela de 2024-03-18 18-37-07](https://github.com/openrazer/openrazer/assets/134338764/67665068-41f9-402e-ad69-63cd40fa3d81)

**Comment by z3ntu** [comment]
That part looks fine. On your new install you also installed RazerGenie via the package manager, so from the AUR? Can you run `razergenie` in the terminal and post the output here?

**Comment by ynuske** [comment]
I installed rezergenie via flatpak, but I uninstalled it and installed it via aur and it still gives this error
![Captura de tela de 2024-03-19 18-10-29](https://github.com/openrazer/openrazer/assets/134338764/57993eca-f42a-470d-ad6b-38f4b7160dc2)
![Captura de tela de 2024-03-19 18-15-30](https://github.com/openrazer/openrazer/assets/134338764/0d354861-30fe-4af5-bc9c-43d188ff567a)
![Captura de tela de 2024-03-19 18-21-18](https://github.com/openrazer/openrazer/assets/134338764/e89e4825-2815-4f93-96b6-6e1ac0d7a8ea)

**Comment by z3ntu** [comment]
Are you using some weird application sandboxing thing? This is definitely not normal...

**Comment by ynuske** [comment]
no, right after installing arch linux I downloaded openrazer and then rezergenie

**Comment by lah7** [comment]
I tried installing `razergenie` (AUR) and `openrazer-daemon` and could reproduce the issue on Arch Linux.

To get it working:

    sudo gpasswd -a $USER plugdev
    systemctl --user enable openrazer-daemon

Then reboot and try opening RazerGenie again. Does that work for you?

**Comment by ynuske** [comment]
bro, my luck is 
![Captura de tela de 2024-03-20 19-04-49](https://github.com/openrazer/openrazer/assets/134338764/78b5eebf-3756-4ff6-889c-324d4331eb5e)

**Comment by ynuske** [comment]
I researched and saw that I needed linux-headers, so after installing and restarting I think it worked
![Captura de tela de 2024-03-20 19-13-42](https://github.com/openrazer/openrazer/assets/134338764/b86adad4-4ccc-42b6-a807-732eed3a7da2)
