### ISSUE TITLE
Fedora 40 repository missing

### ISSUE THREAD

**Issue by quidamphx** [openrazer/razer-drivers#2235]
Adding repo from: https://download.opensuse.org/repositories/hardware:/razer/Fedora_40/hardware:razer.repo
Status code: 404 for https://download.opensuse.org/repositories/hardware:/razer/Fedora_40/hardware:razer.repo (IP: 195.135.223.226)
Error: Configuration of repo failed

I assume the links need to be updated?

**Comment by z3ntu** [comment]
Since Fedora 40 isn't out yet, the builders haven't been enabled for it. But I've done this manually now and all the packages should now be available.

**Comment by quidamphx** [comment]
Thanks, seems to work now!
