### ISSUE TITLE
Razer Deatstalker V2 no connecting

### ISSUE THREAD

**Issue by Antipyrinie** [openrazer/razer-drivers#2246]
### Distribution

 Hello, Ihave a mac book pro and a Razer deathstalkert V2 thats on the list but doesnt show up in the all devices list. i also restarted the mac book pro. It just dont show it anywhere.

Thx in advance for your help.

**Comment by z3ntu** [comment]
What OpenRazer version and operating system version do you have installed?

**Comment by Antipyrinie** [comment]
i have the newest just downloaded this morning. 0.4.10 and the newest Mac Version Sonoma 14.4.1

**Comment by z3ntu** [comment]
That version number is not an OpenRazer and since you say you run macOS, I'm sure you're not running OpenRazer because we don't support macOS.

Whatever you're running, please find their issue tracker and ask there.
