### ISSUE TITLE
Can I set the dpi of the scroll wheel?

### ISSUE THREAD

**Issue by flowerseacar** [openrazer/razer-drivers#2250]

**Comment by z3ntu** [comment]
Not on device-level. Maybe libinput or your desktop environment has some settings how much a scroll degree actually scrolls.

On KDE Plasma this seems to be under Mouse settings "Scrolling speed"

**Comment by flowerseacar** [comment]
> Not on device-level. Maybe libinput or your desktop environment has some settings how much a scroll degree actually scrolls.
> 
> On KDE Plasma this seems to be under Mouse settings "Scrolling speed"

The gnome desktop doesn't seem to have this setting, which is a bit regrettable

**Comment by z3ntu** [comment]
Here's some newish thread about this on GNOME side: https://discourse.gnome.org/t/add-touchpad-scroll-sensitivity-adjustment-feature/18097

**Comment by flowerseacar** [comment]
> Here's some newish thread about this on GNOME side: https://discourse.gnome.org/t/add-touchpad-scroll-sensitivity-adjustment-feature/18097

thank you. I saw they were discussing who should implement this function. I think according to the Windows standard, this function should be provided by the driver API, and gnome should call it to provide UI.
