### ISSUE TITLE
Razer Basilisk V3 X Hyperspeed not recognized by razer genie

### ISSUE THREAD

**Issue by Ornibys** [openrazer/razer-drivers#2254]
I'm using Pop OS 22.04

My razer basilisk V3 X hyperspeed is not recognized by razer genie

**Comment by z3ntu** [comment]
What's the output of `sudo modprobe razerkbd`?

**Comment by Mickhat** [comment]
I have the same issue so i'll provide my output

```
mickhat@pop-os:~$ sudo modprobe razerkbd
mickhat@pop-os:~$ 

```

**Comment by z3ntu** [comment]
`openrazer-daemon --version` ?

**Comment by Mickhat** [comment]
`openrazer-daemon --version
openrazer-daemon 3.8.0
`

**Comment by Mickhat** [comment]
It suddenly worked. Is there a way that I can remap keys?

**Comment by z3ntu** [comment]
You can use input-remapper to remap keys: https://github.com/sezanzeb/input-remapper

If it works now, I'll close the issue then :)
