### ISSUE TITLE
No device was detected

### ISSUE THREAD

**Issue by Culaii** [openrazer/razer-drivers#2255]
### Distribution
Pop!_OS 22.04 LTS x86_64

### Razer Version
RazerGenie v1.1.0
OpenRazerDaemon v3.8.0

### Support

- [ Yes] Have you tried rebooting?
- [ Yes] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Hello there, 2 days ago my razer app worked perfect .. i've been cleaning my laptop ( that means i took out my battery ), after that razer app isn't recognize any device.I have 2 device's that appear like they are connected : 
Bus 003 Device 006: ID 1532:006e Razer USA, Ltd DeathAdder Essential
Bus 003 Device 004: ID 1532:024e Razer USA, Ltd Razer BlackWidow V3
![razer_err](https://github.com/openrazer/openrazer/assets/121720916/ccde0213-e30a-40b6-a58e-01cde40b286f)

**Comment by z3ntu** [comment]
What does `sudo dkms status` say?

**Comment by f0rks7331n** [comment]
> What does `sudo dkms status` say?

openrazer-driver/3.8.0, 6.8.0-76060800daily20240311-generic, x86_64: installed

**Comment by Culaii** [comment]
> What does `sudo dkms status` say?
openrazer-driver/3.8.0, 6.8.0-76060800daily20240311-generic, x86_64: installed

**Comment by z3ntu** [comment]
And `sudo modprobe razerkbd`?

**Comment by Culaii** [comment]
> And `sudo modprobe razerkbd`?
modprobe: ERROR: could not insert 'razerkbd': Invalid argument

**Comment by z3ntu** [comment]
Check dmesg then. But probably a combination of 
`sudo dkms remove openrazer-driver/3.8.0 --all` and 
`sudo dkms install openrazer-driver/3.8.0` should fix it.

**Comment by Culaii** [comment]
> Check dmesg then. But probably a combination of `sudo dkms remove openrazer-driver/3.8.0 --all` and `sudo dkms install openrazer-driver/3.8.0` should fix it.

Ty bro .. it worked! Have a good night :100:
