### ISSUE TITLE
DKMS + Secure Boot documentation

### ISSUE THREAD

**Issue by z3ntu** [openrazer/razer-drivers#2273]
Apparently it's quite doable to use DKMS modules with Secure Boot, on Ubuntu at least.

Try to put this into our documentation:

> Official doc here: https://wiki.ubuntu.com/UEFI/SecureBoot
> 
> usually all you need to do if it does not work is this:
> `sudo update-secureboot-policy --enroll-key`
> 
> if the user has never created keys, first this:
> `sudo update-secureboot-policy --new-key`
> then this:
> `sudo update-secureboot-policy --enroll-key`
> upon reboot, user will be asked to enroll key, then enter the password they selected

Thanks @ilvipero!

**Comment by zjDrummond** [comment]
Glad I found this! I can confirm this worked for my system on Kubuntu 24.04. Adding this to the troubleshooting page would be great for others like myself.

**Comment by z3ntu** [comment]
@zjDrummond Thanks for confirming!

**Comment by lah7** [comment]
I created a new wiki page documenting the secure boot key enrolment process. Mainly targets Ubuntu, which is actually easier then I thought.

https://github.com/openrazer/openrazer/wiki/Secure-Boot
