### ISSUE TITLE
mouse not showing 

### ISSUE THREAD

**Issue by Totallynotmwa** [openrazer/razer-drivers#2276]
### Distribution
Bazzite (installed on fedora 40 kinoite)

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

So my mouse is not showing in open razer it's a razer cobra and is supported when I tried polychromatic it said razer daemon not detected I hit Troubleshoot it it said smth about dvdk or whatever it's called

And the keyboard which is razer ornata v3 shows up properly

**Comment by z3ntu** [comment]
Could you run `sudo dkms install openrazer-driver/3.8.0` ?

**Comment by Totallynotmwa** [comment]
> Could you run `sudo dkms install openrazer-driver/3.8.0` ?

[Dkms command not found](sudo: dkms: command not found)
All the fixes for this online are related to arch linux

**Comment by z3ntu** [comment]
It seems you haven't installed openrazer then?

**Comment by Totallynotmwa** [comment]
> It seems you haven't installed openrazer then?

Maybe it was installed incorrectly 
I have kernel-devel package but it still says dkms not found
openrazer-driver-dkms is also missing
I reinstalled it via bazzite portal same thing and some results say it has to do with dkms drivers not avaible in atomic builds of fedora
I also found [this](https://github.com/openrazer/openrazer/issues/1747) while trying to find a fix
