### ISSUE TITLE
Razer BlackWidow V4 75% Fn+KEY combinations not working

### ISSUE THREAD

**Issue by Flexksx** [openrazer/razer-drivers#2299]
### Affected Device / PID

Razer BlackWidow V4 75%, 1532:02A5

### Operating System / Version

Arch Linux x86_64

### Kernel Version

6.10.8-arch1-1

### OpenRazer Version

3.8.0

### Support Checklist

- [X] My user was added to the plugdev group.
- [X] I have rebooted and the problem persists.
- [X] I looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page and it did not solve the problem.

### Symptoms

- [X] Uninstalling OpenRazer fixes the problem
- [ ] Re-plugging the device fixes the problem
- [X] It worked before a system/kernel update.
- [X] Only a problem if the daemon is running.
- [ ] Only a problem from power up or a reboot.
- [X] I'm dual booting with Windows.
- [ ] Intermittent or erratic problem.
- [X] My device is missing a feature.

### Please describe the issue

After latest patch that added support for BlackWidow V4 75%, the Fn+KEY combinations stopped working.
Specifically:
Fn+P -> PrtScr
Fn+del -> Hybernate
Fn+PgUp -> Home
Fn+PgDn -> End
Fn+Ins -> Pause

The function key row is working as normal.
Fn+ F11 is decreasing brightness, Fn+F12 is increasing it
Fn+F10 turns game mode on
Fn+F9 I can't understand how do I create a macro.

**Comment by Flexksx** [comment]
@Oery opened the issue

**Comment by Oery** [comment]
Okay so it seems the mapping for those keys must be manually added in ```driver/razerkbd_driver.c```. I'm going to do that.

My only issue is that Fn+Del reboot my PC so I can't really check what key it's supposed to be. If you can check what key is produced using something like ```evtest``` it would be super useful.
