### ISSUE TITLE
Razer Viper V3 Pro Gaming Mouse not detected

### ISSUE THREAD

**Issue by Tyler-Posella** [openrazer/razer-drivers#2307]
### Device Name

Razer Viper V3 Pro

### Product Number

RZ01-05120100

### Model Number

RZ01-0512

### VID:PID

1532:00c0

### USB Details

```shell
Bus 001 Device 009: ID 1532:00c0 Razer USA, Ltd Razer Viper V3 Pro
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x00c0 
  bcdDevice            1.00
  iManufacturer           0 
  iProduct                2 Razer Viper V3 Pro
  iSerial                 3 000000000000
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
```

### Device Input Paths

```shell
drwxr-xr-x 2 root root 400 Sep 19 12:45 .
drwxr-xr-x 4 root root 700 Sep 19 12:45 ..
lrwxrwxrwx 1 root root  10 Sep 19 12:45 usb-1532_Razer_Viper_V3_Pro_000000000000-event-if01 -> ../event17
lrwxrwxrwx 1 root root  10 Sep 19 12:45 usb-1532_Razer_Viper_V3_Pro_000000000000-event-mouse -> ../event15
lrwxrwxrwx 1 root root  10 Sep 19 12:45 usb-1532_Razer_Viper_V3_Pro_000000000000-if01-event-kbd -> ../event16
lrwxrwxrwx 1 root root  10 Sep 19 12:45 usb-1532_Razer_Viper_V3_Pro_000000000000-if02-event-kbd -> ../event18
lrwxrwxrwx 1 root root   9 Sep 19 12:45 usb-1532_Razer_Viper_V3_Pro_000000000000-mouse -> ../mouse3
lrwxrwxrwx 1 root root  10 Sep 19 12:39 usb-Blue_Microphones_Yeti_Stereo_Microphone_REV8-event-if03 -> ../event14
lrwxrwxrwx 1 root root  10 Sep 19 12:39 usb-KEYBOARD_USB_KEYBOARD-event-if02 -> ../event10
lrwxrwxrwx 1 root root   9 Sep 19 12:39 usb-KEYBOARD_USB_KEYBOARD-event-kbd -> ../event9
lrwxrwxrwx 1 root root  10 Sep 19 12:39 usb-KEYBOARD_USB_KEYBOARD-if02-event-kbd -> ../event12
lrwxrwxrwx 1 root root  10 Sep 19 12:39 usb-KEYBOARD_USB_KEYBOARD-if02-event-mouse -> ../event13
lrwxrwxrwx 1 root root   9 Sep 19 12:39 usb-KEYBOARD_USB_KEYBOARD-if02-mouse -> ../mouse2
lrwxrwxrwx 1 root root   9 Sep 19 12:39 usb-Logitech_USB_Receiver-event-mouse -> ../event7
lrwxrwxrwx 1 root root   9 Sep 19 12:39 usb-Logitech_USB_Receiver-if01-event-kbd -> ../event8
lrwxrwxrwx 1 root root   9 Sep 19 12:39 usb-Logitech_USB_Receiver-mouse -> ../mouse1
lrwxrwxrwx 1 root root   9 Sep 19 12:39 usb-UBEST_zoom75_wireless_061DB7FA3C18-event-if02 -> ../event4
lrwxrwxrwx 1 root root   9 Sep 19 12:39 usb-UBEST_zoom75_wireless_061DB7FA3C18-event-kbd -> ../event3
lrwxrwxrwx 1 root root   9 Sep 19 12:39 usb-UBEST_zoom75_wireless_061DB7FA3C18-if02-event-mouse -> ../event6
lrwxrwxrwx 1 root root   9 Sep 19 12:39 usb-UBEST_zoom75_wireless_061DB7FA3C18-if02-mouse -> ../mouse0
```

### USB HID Dump

```shell
libusb: error [get_usbfs_fd] libusb couldn't open USB device /dev/bus/usb/001/009, errno=13
libusb: error [get_usbfs_fd] libusb requires write access to USB device nodes
Failed to find and open the devices: Access denied (insufficient permissions)
```

**Comment by Tyler-Posella** [comment]
Device ID 1532:00c0 doesn't appear in the supported devices even though there is a completed issue with this device in the past.

**Comment by lah7** [comment]
Support was added in #2266 for `1532:00C0` (wired) and `1532:00C1` (wireless), but it's not in any stable release yet.

Depending on your distro, you can install the equivalent `-git` packages (for Arch), use the daily PPA (for Ubuntu) or [build the package](https://github.com/openrazer/openrazer/wiki/Building-a-package) for others using the `master` branch in the meantime.

**Comment by Tyler-Posella** [comment]
> Support was added in #2266 for `1532:00C0` (wired) and `1532:00C1` (wireless), but it's not in any stable release yet.
> 
> Depending on your distro, you can install the equivalent `-git` packages (for Arch), use the daily PPA (for Ubuntu) or [build the package](https://github.com/openrazer/openrazer/wiki/Building-a-package) for others using the `master` branch in the meantime.

I've been trying all morning but I keep getting device not detected

**Comment by lah7** [comment]
What distro and frontend are you using (Polychromatic, RazerGenie)?

If the device isn't listed, sounds like not all of the `master` equivalent packages are installed (e.g. `openrazer-daemon-git`, `python-openrazer-git`, `openrazer-driver-dkms-git`). There is the usual [troubleshooting guide](https://github.com/openrazer/openrazer/wiki/Troubleshooting) in case it's something as simple as a missing `plugdev` user group.

**Comment by Tyler-Posella** [comment]
> What distro and frontend are you using (Polychromatic, RazerGenie)?
> 
> If the device isn't listed, sounds like not all of the `master` equivalent packages are installed (e.g. `openrazer-daemon-git`, `python-openrazer-git`, `openrazer-driver-dkms-git`). There is the usual [troubleshooting guide](https://github.com/openrazer/openrazer/wiki/Troubleshooting) in case it's something as simple as a missing `plugdev` user group.

I've already gone through the troubleshooting and everything ran properly. For somereason though none of the "supported apps" are showing the device as supported still but it detects the product code properly

**Comment by Tyler-Posella** [comment]
I am currently running on PopOS version 22.04 and I have tried Polychromatic and RazerGenie and both say either device not supported or device not found. I am using the Flatpak version

**Comment by lah7** [comment]
Since it's based on Ubuntu, add the ["daily" PPA](https://launchpad.net/~openrazer/+archive/ubuntu/daily) and update the system:

```
sudo add-apt-repository ppa:openrazer/daily
sudo apt update
sudo apt dist-upgrade
```

Then reboot. The device should be recognised in both apps afterwards.

Once your device is in a stable release (next one: v3.9.0), then you can remove the daily PPA, or remove it immediately now if you want.

**Comment by jtsec92** [comment]
> Since it's based on Ubuntu, add the ["daily" PPA](https://launchpad.net/~openrazer/+archive/ubuntu/daily) and update the system:
> 
> ```
> sudo add-apt-repository ppa:openrazer/daily
> sudo apt update
> sudo apt dist-upgrade
> ```
> 
> Then reboot. The device should be recognised in both apps afterwards.
> 
> Once your device is in a stable release (next one: v3.9.0), then you can remove the daily PPA, or remove it immediately now if you want.

I'm running into a similar problem with the Viper Pro V3 on Ubuntu 22.04, however my mouse connects and the buttons and scroll wheel and horizontal tracking work fine, however, it doesn't move in any other direction besides the x-axis. The troubleshooting steps show the mouse working correctly.

![image](https://github.com/user-attachments/assets/a9bd75c6-fc78-4b28-9675-6a291496d076)

![image](https://github.com/user-attachments/assets/5bf1e022-6e53-42da-882e-1f9e0588418f)

```
user@r4z:~$ openrazer-daemon --version
openrazer-daemon 3.9.0
user@r4z:~$ sudo dkms status | grep openrazer
[sudo] password for user: 
openrazer-driver/3.9.0, 6.8.0-47-generic, x86_64: installed
user@r4z:~$ sudo dkms install openrazer-driver/3.9.0
Module openrazer-driver/3.9.0 already installed on kernel 6.8.0-47-generic (x86_64).
user@r4z:~$ sudo modprobe razerkbd
user@r4z:~$ 
```

**Comment by lah7** [comment]
@jtsec92 That's strange. Presumably you've rebooted? What's in the daemon's log file: `~/.local/share/openrazer/logs/razer.log`?

(Try `sudo modprobe razermouse` instead)

**Comment by jtsec92** [comment]
```
user@r4z:~/.local/share/openrazer/logs$ cat razer.log 
2024-10-28 19:29:01 | razer                          | INFO     | Initialising Daemon (v3.9.0). Pid: 2170
2024-10-28 19:29:01 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2024-10-28 19:29:01 | razer                          | INFO     | Serving DBus
2024-10-28 19:52:21 | razer                          | INFO     | Initialising Daemon (v3.9.0). Pid: 2160
2024-10-28 19:52:21 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2024-10-28 19:52:21 | razer                          | INFO     | Serving DBus
2024-10-28 19:53:46 | razer                          | INFO     | Initialising Daemon (v3.9.0). Pid: 2257
2024-10-28 19:53:46 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2024-10-28 19:53:46 | razer                          | INFO     | Serving DBus
2024-10-28 20:03:20 | razer                          | INFO     | Initialising Daemon (v3.9.0). Pid: 2227
2024-10-28 20:03:20 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2024-10-28 20:03:20 | razer                          | INFO     | Serving DBus
2024-10-28 20:05:47 | razer                          | INFO     | Initialising Daemon (v3.9.0). Pid: 2276
2024-10-28 20:05:47 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2024-10-28 20:05:47 | razer                          | INFO     | Serving DBus
2024-10-28 20:08:33 | razer                          | INFO     | Stopping daemon on signal 15
2024-10-28 20:08:35 | razer                          | INFO     | Initialising Daemon (v3.9.0). Pid: 6368
2024-10-28 20:08:35 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2024-10-28 20:08:35 | razer                          | INFO     | Serving DBus
2024-10-28 20:12:15 | razer                          | INFO     | Stopping daemon on signal 15
2024-10-28 20:17:16 | razer                          | INFO     | Initialising Daemon (v3.9.0). Pid: 9405
2024-10-28 20:17:16 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2024-10-28 20:17:16 | razer                          | INFO     | Serving DBus
2024-10-28 20:27:17 | razer                          | INFO     | Initialising Daemon (v3.9.0). Pid: 2239
2024-10-28 20:27:17 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2024-10-28 20:27:17 | razer                          | INFO     | Serving DBus
2024-10-28 20:48:52 | razer                          | INFO     | Initialising Daemon (v3.9.0). Pid: 2280
2024-10-28 20:48:52 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2024-10-28 20:48:52 | razer                          | INFO     | Serving DBus
2024-10-29 00:10:16 | razer                          | INFO     | Initialising Daemon (v3.9.0). Pid: 2119
2024-10-29 00:10:16 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2024-10-29 00:10:16 | razer                          | INFO     | Serving DBus
2024-10-29 00:15:32 | razer                          | INFO     | Initialising Daemon (v3.9.0). Pid: 2267
2024-10-29 00:15:32 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2024-10-29 00:15:32 | razer                          | INFO     | Serving DBus
2024-10-29 00:16:50 | razer                          | INFO     | Initialising Daemon (v3.9.0). Pid: 2387
2024-10-29 00:16:50 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2024-10-29 00:16:50 | razer                          | INFO     | Serving DBus
2024-10-29 09:54:00 | razer                          | INFO     | Initialising Daemon (v3.9.0). Pid: 2210
2024-10-29 09:54:00 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2024-10-29 09:54:00 | razer                          | INFO     | Serving DBus
```
`sudo modprobe razermouse` returns:

```
user@r4z:~/.local/share/openrazer/logs$ sudo modprobe razermouse
[sudo] password for user: 
user@r4z:~/.local/share/openrazer/logs$
```
I've updated the firmware in the mouse in Windows and it also works fine in Windows, oddly enough.

**Comment by lah7** [comment]
Daemon doesn't see the device, driver appears to be OK. `1532:00C1` is definitely supported in 3.9.0. What are the permissions for the mouse in the sysfs?

    ls -al /sys/bus/hid/drivers/razer*/*1532*/

Did you add your user to `plugdev` group? (The daemon typically refuses to start if it wasn't)

    sudo gpasswd -a $USER plugdev

Also for good measure, what does the kernel say?

```
dmesg | grep razer
```
```
sudo journalctl -b | grep -i razer_mount
```

**Comment by jtsec92** [comment]
```
user@r4z:~$ ls -al /sys/bus/hid/drivers/razer*/*1532*/
'/sys/bus/hid/drivers/razermouse/0003:1532:00C1.000E/':
total 0
drwxr-xr-x 5 root plugdev    0 Oct 29 15:00 .
drwxr-xr-x 5 root root       0 Oct 29 15:00 ..
-r--r--r-- 1 root plugdev 4096 Oct 29 15:00 country
lrwxrwxrwx 1 root plugdev    0 Oct 29 15:00 driver -> ../../../../../../../../../../../bus/hid/drivers/razermouse
drwxr-xr-x 3 root plugdev    0 Oct 29 15:00 hidraw
drwxr-xr-x 3 root plugdev    0 Oct 29 15:00 input
-r--r--r-- 1 root plugdev 4096 Oct 29 15:00 modalias
drwxr-xr-x 2 root plugdev    0 Oct 29 15:00 power
-r--r--r-- 1 root plugdev 4096 Oct 29 15:00 report_descriptor
lrwxrwxrwx 1 root plugdev    0 Oct 29 15:00 subsystem -> ../../../../../../../../../../../bus/hid
-rw-r--r-- 1 root plugdev 4096 Oct 29 15:00 uevent

'/sys/bus/hid/drivers/razermouse/0003:1532:00C1.000F/':
total 0
drwxr-xr-x 5 root plugdev    0 Oct 29 15:00 .
drwxr-xr-x 5 root root       0 Oct 29 15:00 ..
-r--r--r-- 1 root plugdev 4096 Oct 29 15:00 country
lrwxrwxrwx 1 root plugdev    0 Oct 29 15:00 driver -> ../../../../../../../../../../../bus/hid/drivers/razermouse
drwxr-xr-x 3 root plugdev    0 Oct 29 15:00 hidraw
drwxr-xr-x 3 root plugdev    0 Oct 29 15:00 input
-r--r--r-- 1 root plugdev 4096 Oct 29 15:00 modalias
drwxr-xr-x 2 root plugdev    0 Oct 29 15:00 power
-r--r--r-- 1 root plugdev 4096 Oct 29 15:00 report_descriptor
lrwxrwxrwx 1 root plugdev    0 Oct 29 15:00 subsystem -> ../../../../../../../../../../../bus/hid
-rw-r--r-- 1 root plugdev 4096 Oct 29 15:00 uevent
user@r4z:~$ 
```
Yes I did add plug dev to the user group. Re-ran `sudo gpasswd -a $USER plugdev` again for good measure as well.

Output of `dmesg | grep razer`

```
user@r4z:~$ dmesg | grep razer
dmesg: read kernel buffer failed: Operation not permitted
user@r4z:~$ sudo dmesg | grep razer
[ 2567.008376] razermouse 0003:1532:00C1.000D: input,hidraw6: USB HID v1.00 Mouse [Razer Razer Viper V3 Pro] on usb-0000:08:00.3-5.2/input0
[ 2567.198313] razermouse 0003:1532:00C1.000E: input,hidraw11: USB HID v1.00 Keyboard [Razer Razer Viper V3 Pro] on usb-0000:08:00.3-5.2/input1
[ 2567.319162] razermouse 0003:1532:00C1.000F: input,hidraw12: USB HID v1.00 Keyboard [Razer Razer Viper V3 Pro] on usb-0000:08:00.3-5.2/input2
user@r4z:~$
```

Output of `sudo journalctl -b | grep -i razer_mount`

```
user@r4z:~$ sudo journalctl -b | grep -i razer_mount
Oct 29 15:00:23 r4z razer_mount[4980]: Driver razermouse
Oct 29 15:00:23 r4z razer_mount[4981]: Device_ID 3-5.2
Oct 29 15:00:23 r4z razer_mount[4982]: Modprobing razermouse
Oct 29 15:00:23 r4z razer_mount[4988]: Modprobed razermouse
Oct 29 15:00:23 r4z razer_mount[4994]: Driver razermouse
Oct 29 15:00:23 r4z razer_mount[4997]: Driver razermouse
Oct 29 15:00:23 r4z razer_mount[4998]: Device_ID 3-5.2:1.1
Oct 29 15:00:23 r4z razer_mount[5002]: Device_ID 3-5.2:1.2
Oct 29 15:00:23 r4z razer_mount[5006]: Driver razermouse
Oct 29 15:00:23 r4z razer_mount[5008]: Driver razermouse
Oct 29 15:00:23 r4z razer_mount[5009]: Device_ID 0003:1532:00C1.000E
Oct 29 15:00:23 r4z razer_mount[5010]: Device_ID 0003:1532:00C1.000F
Oct 29 15:00:23 r4z razer_mount[5011]: Changing group /sys/bus/hid/drivers/razermouse/0003:1532:00C1.000E/
Oct 29 15:00:23 r4z razer_mount[5012]: Changing group /sys/bus/hid/drivers/razermouse/0003:1532:00C1.000F/
Oct 29 15:00:23 r4z razer_mount[5015]: Changed group /sys/bus/hid/drivers/razermouse/0003:1532:00C1.000E/
Oct 29 15:00:23 r4z razer_mount[5016]: Changed group /sys/bus/hid/drivers/razermouse/0003:1532:00C1.000F/
Oct 29 15:00:23 r4z razer_mount[5036]: Driver razermouse
Oct 29 15:00:23 r4z razer_mount[5037]: Device_ID 3-5.2:1.0
Oct 29 15:00:23 r4z razer_mount[5043]: Driver razermouse
Oct 29 15:00:23 r4z razer_mount[5044]: Device_ID 0003:1532:00C1.000D
user@r4z:~$
```

**Comment by lah7** [comment]
I'm not sure what's happening here. There's typically three directories: yours is missing `0003:1532:00C1.000D`, and one of the three should have files starting with `matrix_`, `device_`, etc, which are missing. Driver appears to look like it's installed and loaded though.

* What distro/version are you using?
* Does it work if you unplug it, wait, then plug it in?  _(In case device is in a weird state)_
* Do you have other USB ports to try? _(In case a hub is the problem, still be strange if so since Windows works)_

**Comment by jtsec92** [comment]
> I'm not sure what's happening here. There's typically three directories: yours is missing `0003:1532:00C1.000D`, and one of the three should have files starting with `matrix_`, `device_`, etc, which are missing. Driver appears to look like it's installed and loaded though.
> 
> * What distro/version are you using?
> * Does it work if you unplug it, wait, then plug it in?  _(In case device is in a weird state)_
> * Do you have other USB ports to try? _(In case a hub is the problem, still be strange if so since Windows works)_

I'm on Ubuntu 22.04 LTS:

```
user@r4z:~$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
user@r4z:~$ 
```

I've tried unplugging it and plugging it back in. I've tried other ports as well and without using the hub. How would I go about getting those three directories?

**Comment by lah7** [comment]
`00C1` is the wireless one - let's try device PID `00C0`.

* Does it work when the mouse is wired directly?
* Does having the wireless dongle plugged in at the same time make any difference?  
* _If necessary, press CTRL+F5 to force refresh Polychromatic, or restart the daemon._

Puzzling one, because it looks right, except the driver obviously isn't creating device files, but there's no error. 1bbbe473382a8f9bda1e7a33a85be575a343c0e7 looks sane and other users reported it working (#2266). Unless there is an odd chance that it isn't actually v3.9.0 (e.g. mismatching files). You could check that:

    cat /usr/lib/python3/dist-packages/openrazer_daemon/hardware/mouse.py | grep 'class RazerViperV3Pro'
    cat /usr/src/openrazer-driver-3.9.0/driver/razermouse_driver.c | grep RAZER_VIPER_V3_PRO

It should output lines showing this device.

Did you always use the stable PPA, or did you try daily PPA, building packages, or manual installation, etc? 

Lastly, _because of a recent nuisance with **secure boot**_ - is this turned on/off in your BIOS/UEFI?

**Comment by jtsec92** [comment]
> `00C1` is the wireless one - let's try device PID `00C0`.
> 
> * Does it work when the mouse is wired directly?

It's the same problem where clicks work and the scroll wheel works but it only moves along the x-axis.

> * Does having the wireless dongle plugged in at the same time make any difference?

I tried it with the dongle plugged in and the mouse plugged in via a separate cord and it still has the same problem.

> * _If necessary, press CTRL+F5 to force refresh Polychromatic, or restart the daemon._
> 
> Puzzling one, because it looks right, except the driver obviously isn't creating device files, but there's no error. [1bbbe47](https://github.com/openrazer/openrazer/commit/1bbbe473382a8f9bda1e7a33a85be575a343c0e7) looks sane and other users reported it working (#2266). Unless there is an odd chance that it isn't actually v3.9.0 (e.g. mismatching files). You could check that:
> 
> ```
> cat /usr/lib/python3/dist-packages/openrazer_daemon/hardware/mouse.py | grep 'class RazerViperV3Pro'
> cat /usr/src/openrazer-driver-3.9.0/driver/razermouse_driver.c | grep RAZER_VIPER_V3_PRO
> ```
> 
> It should output lines showing this device.

This is the output with the mouse plugged in and with the dongle unplugged:

```
user@r4z:~$ cat /usr/lib/python3/dist-packages/openrazer_daemon/hardware/mouse.py | grep 'class RazerViperV3Pro'
class RazerViperV3ProWired(__RazerDevice):
class RazerViperV3ProWireless(RazerViperV3ProWired):
user@r4z:~$ cat /usr/src/openrazer-driver-3.9.0/driver/razermouse_driver.c | grep RAZER_VIPER_V3_PRO
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRED:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRED:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRED:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRED:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRED:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRED:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRED:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRED:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRED:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRED:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRED:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRED:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRED:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRED:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRED:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRED:
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS:
        case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS:
        case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRED:
        case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS:
        case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRED:
    { HID_USB_DEVICE(USB_VENDOR_ID_RAZER,USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRED) },
    { HID_USB_DEVICE(USB_VENDOR_ID_RAZER,USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS) },
```

> 
> Did you always use the stable PPA, or did you try daily PPA, building packages, or manual installation, etc?

I believe I tried both. There might be a possibility that the SSL decryption/inspection setting on my firewall may have caused an issue when I set up the PPA? I'm not a 100% sure on that, I think I tried the stable PPA first and then I switched to the daily PPA. I had to turn on ProtonVPN after running into a SSL verify error while trying to install `openrazer-meta` with the SSL inspection setting on. Not sure if that caused a problem.

I tried these steps:

> Starting with 20.04, OpenRazer is available from the [official repositories](https://packages.ubuntu.com/search?keywords=openrazer). However, you may need to install our package if your device was added in a newer version.
> 
> elementaryOS users need to install a prerequisite first:
> ```
> sudo apt install software-properties-gtk
> ```
> To install the latest release, add this PPA:
> ```
> sudo add-apt-repository ppa:openrazer/stable
> ```
> Or for latest development builds:
> ```
> sudo add-apt-repository ppa:openrazer/daily
> ```
> After adding the PPA, install the packages:
> ```
> sudo apt update
> sudo apt install openrazer-meta
> ```

> 
> Lastly, _because of a recent nuisance with **secure boot**_ - is this turned on/off in your BIOS/UEFI?

I do have secure boot on in my BIOS/UEFI settings.

**Comment by lah7** [comment]
Good to know. Thanks for going through the troubleshooting. It was head scratching since everything seems in place. Polychromatic saying it's "not supported" will be addressed in its next update. The PPA SSL shouldn't matter since you have the repository now, and presumably it's the release version of 3.9.0:

    $ apt-cache show openrazer-daemon | grep Version
    Version: 3.9.0~ubuntu22.04.1
    Version: 3.2.0+dfsg-3

_(If you see more, disable the daily PPA in **Software & Updates** → Other Software tab, but it's not the problem)_

Regarding secure boot, did you do anything special to [sign the modules](https://github.com/openrazer/openrazer/wiki/Secure-Boot)? It looks like they're loaded (no message from `modprobe`) but it wouldn't surprise me if _nothing happens_ still because it's still unsigned/untrusted. **That's problem A.**

---

> It's the same problem where clicks work and the scroll wheel works but it only moves along the x-axis.

**For problem B:** To rule things out further, does the mouse work fine if you enter the UEFI settings in your BIOS? (assuming it has cursor support)

Does your laptop run Ubuntu as well, and does it have OpenRazer installed? If the laptop doesn't have OpenRazer and it works under Ubuntu, I would suggest trying uninstalling OpenRazer on the desktop, just to see if it's our driver triggering buggy mouse firmware (as you say you've recently updated the firmware)

I would guess there's a stray system configuration file that's dictating the mouse behaviour. First, is your session using Wayland or X11?

    env | grep SESSION_TYPE

If it's X11, check `/etc/X11/xorg.conf.d/` - by default, it's an empty folder in 22.04. In case of a stray local configuration file, there could be something in your home folder (`~/.config` or `~/.local/share`), try creating a new user, and see if it happens in a fresh profile.

**Comment by jtsec92** [comment]
Doh, I'm an idiot. I wasn't hacked. It was because of the mouse acceleration that I was using. Apparently, this doesn't play nice with Razer mice, the kernel module at least: https://github.com/AndyFilter/YeetMouse 

I ended up upgrading to 24.04:

```
jftai@jftai-r4z:~$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

and as soon as I tried installing the YeetMouse driver with the steps below, I ran into the issue:

```
# Install the driver and activate the dkms module
sudo make setup_dkms && sudo make udev_install
sudo dkms install -m leetmouse-driver -v 0.9.0 # Enter the version you determined from the Makefile earlier in here
```

Anyways, I guess that's what I get for blaming hackers immediately. Pretty good foot-gun if you ask me. Now I get to reinstall all of my old apps :(

**Comment by jtsec92** [comment]
```
user@r4z:~/YeetMouse-master$ apt-cache show openrazer-daemon | grep Version
Version: 3.9.0~ubuntu24.04.1
Version: 3.7.0+dfsg-1
user@r4z:~/YeetMouse-master$ env | grep SESSION_TYPE
XDG_SESSION_TYPE=x11
user@r4z:~/YeetMouse-master$
```

**Comment by jtsec92** [comment]
When I run `sudo apt-get install openrazer-meta` it doesn't take me to the screen for signing kernel modules.

**Comment by lah7** [comment]
Problem solved then! See our [secure boot wiki page ](https://github.com/openrazer/openrazer/wiki/Secure-Boot) for details on that screen. Could it be that it was already set up before?
