### ISSUE TITLE
chromeOS user here i have a problem i can't launch it it says no device was detected

### ISSUE THREAD

**Issue by julian136452** [openrazer/razer-drivers#2352]
### Affected Device / PID

Razer DeathAdder Essential (2021) 1532:0098

### Operating System / Version

chromeOS Version 130.0.6723.126 (64 bit)

### Kernel Version

6.6.50-05090-g02ec56928355

### OpenRazer Version

dont have open razer do i need it?

### Support Checklist

- [ ] My user was added to the plugdev group.
- [ ] I have rebooted and the problem persists.
- [ ] I looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page and it did not solve the problem.

### Symptoms

- [ ] Uninstalling OpenRazer fixes the problem
- [ ] Re-plugging the device fixes the problem
- [ ] It worked before a system/kernel update.
- [ ] Only a problem if the daemon is running.
- [ ] Only a problem from power up or a reboot.
- [ ] I'm dual booting with Windows.
- [ ] Intermittent or erratic problem.
- [ ] My device is missing a feature.

### Please describe the issue

i do not have open razer if i need it someone please do a tutorial on how to install it on chromeOS
i dont know how to reboot a chromebook and idk what is does

**Comment by z3ntu** [comment]
Chromebooks running ChromeOS are not supported. If you install a regular Linux distribution, even on the same device, you can follow the install instructions on the website https://openrazer.github.io/#download
