### ISSUE TITLE
 RuntimeError: "Should never be installed" when installing OpenRazer Python library | installing openrazer.client in a venv

### ISSUE THREAD

**Issue by Dralexgon** [openrazer/razer-drivers#2359]
Hi! 👋

I'm trying to install the OpenRazer Python library as described in the [examples](https://github.com/openrazer/openrazer/tree/master/examples) using the command:

`pip install openrazer`

However, I encounter the following error:  
`RuntimeError: Should never be installed`

It seems that it isn't possible to install it because it's installed by default with openrazer. But that means we can't use it in a venv.

I couldn't find any documentation for the library other than these examples. Could you provide guidance or point me to the correct way to install and use the library?

Thank you in advance!

**Comment by Dralexgon** [comment]
After ~4 hours of search I FOUND THE ISSUE
The library is installed with openrazer (that's why I wasn't able to found how to install it) BUT it isn't added to the venv
Use `python3 -m venv --system-site-packages path/to/venv`

**Comment by Dralexgon** [comment]
[resolved]

After ~4 hours of search I FOUND THE ISSUE
The library is installed with openrazer (that's why I wasn't able to found how to install it) BUT it isn't added to the venv
Use `python3 -m venv --system-site-packages path/to/venv`

**Comment by Dralexgon** [comment]
[Resolved]

To use openrazer lib in venv, you need to link your system package to your venv package.
I made this script if anyone has the same issue.

`
#Change these variables to match your system
VENV_PATH=venv
PYTHON_VERSION=3.12

# This is the path where the packages are installed
PACKAGES_PATH=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
VENV_PACKAGES_PATH="$VENV_PATH"/lib/python"$PYTHON_VERSION"/site-packages

python3 -m venv "$VENV_PATH"
source "$VENV_PATH"/bin/activate

ln -s "$PACKAGES_PATH"/* "$VENV_PACKAGES_PATH"/

pip install -r requirements.txt#optional
`

**Comment by Dralexgon** [comment]
[RESOLVED]

To use openrazer lib in venv, you need to link your system package to your venv package.
I made this script if anyone has the same issue.

```
#Change these variables to match your system
VENV_PATH=venv
PYTHON_VERSION=3.12

# This is the path where the packages are installed
PACKAGES_PATH=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
VENV_PACKAGES_PATH="$VENV_PATH"/lib/python"$PYTHON_VERSION"/site-packages

python3 -m venv "$VENV_PATH"
source "$VENV_PATH"/bin/activate

ln -s "$PACKAGES_PATH"/* "$VENV_PACKAGES_PATH"/

pip install -r requirements.txt#optional
```

**Comment by lah7** [comment]
Hi. I'm pretty sure the pip package published for `openrazer` and `openrazer-daemon` is a stub to prevent the name from being squatted for malicious intent, but technically OpenRazer was designed to be work with matching driver/daemon versions so it's not quite "portable" enough for PyPI. 

* https://github.com/openrazer/openrazer/issues/1879
* https://github.com/openrazer/openrazer/issues/711#issuecomment-437362414

The examples were designed to "just work" with the system libraries, assuming `python3-openrazer` is installed for your distro. e.g.

    python3 ./examples/basic_effect.py

It may work in a venv by symlinking the modules from the system, but OpenRazer doesn't support this kind of isolated virtual environment. OpenRazer's architecture was designed to work within the host. Messages get sent to the daemon via D-Bus (more venv dependencies may need to be installed) in which the daemon processes/relays to the driver (via a sysfs filesystem) or the [fake driver](https://github.com/openrazer/openrazer/blob/master/scripts/setup_fake_devices.sh).

> I'm trying to install the OpenRazer Python library as described in the [examples](https://github.com/openrazer/openrazer/tree/master/examples) using the command:

I can't see anywhere where `pip install` is suggested. You could say OpenRazer is (currently) very Linux specific, but so happens to be Python-based, distributed via Linux repositories rather then a Python repository.
